{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.identity",
    "module": "font-jar",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "font-jar-1.0.0.aar",
          "url": "font-jar-1.0.0.aar",
          "size": 276929,
          "sha512": "9829c4bc2dee053558499126d6617181c9ef7a7d1a0f34ff58aa242c321ea3031ee9b2bf5bcbde8a8474e7da7dfa1481068ea2603a75eef69f7494d618027937",
          "sha256": "69e68a756aa718a90f3d3614c207ac3823ffb6fbaa935f30c3cf9b4624a3f57b",
          "sha1": "4d09a317248e0bf8d0ff6c51abd964f1661834c6",
          "md5": "22f4a5c04a95e20546a59234dff8bffb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "font-jar-1.0.0.aar",
          "url": "font-jar-1.0.0.aar",
          "size": 276929,
          "sha512": "9829c4bc2dee053558499126d6617181c9ef7a7d1a0f34ff58aa242c321ea3031ee9b2bf5bcbde8a8474e7da7dfa1481068ea2603a75eef69f7494d618027937",
          "sha256": "69e68a756aa718a90f3d3614c207ac3823ffb6fbaa935f30c3cf9b4624a3f57b",
          "sha1": "4d09a317248e0bf8d0ff6c51abd964f1661834c6",
          "md5": "22f4a5c04a95e20546a59234dff8bffb"
        }
      ]
    }
  ]
}
