{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.component",
    "module": "identity-jar",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "resources",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "skin",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.extend",
          "module": "arms",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "skin.support",
          "module": "skin-support-appcompat",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "skin.support",
          "module": "skin-support-design",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "skin.support",
          "module": "skin-support-cardview",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "skin.support",
          "module": "skin-support-constraint-layout",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "identity-1.0.2.aar",
          "url": "identity-1.0.2.aar",
          "size": 79661,
          "sha512": "358e2b8626c1e4ec817b718930d349eafd14fb11e6e19ba04ecca4fbd10ef697696e528b18300cf336083ed7e6736d398b2750d089ed5c997991481671aff952",
          "sha256": "a0ea119bc706fae44ab7a344d9631b1afa53f79a432996ca716555f922a45006",
          "sha1": "a95c75e76da1ad9bed59e2ad0ba880416fbd0f60",
          "md5": "bcb9f988f1d571092277ad1e61c3d7f5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "resources",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "skin",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.extend",
          "module": "arms",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "skin.support",
          "module": "skin-support-appcompat",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "skin.support",
          "module": "skin-support-design",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "skin.support",
          "module": "skin-support-cardview",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "skin.support",
          "module": "skin-support-constraint-layout",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "identity-1.0.2.aar",
          "url": "identity-1.0.2.aar",
          "size": 79661,
          "sha512": "358e2b8626c1e4ec817b718930d349eafd14fb11e6e19ba04ecca4fbd10ef697696e528b18300cf336083ed7e6736d398b2750d089ed5c997991481671aff952",
          "sha256": "a0ea119bc706fae44ab7a344d9631b1afa53f79a432996ca716555f922a45006",
          "sha1": "a95c75e76da1ad9bed59e2ad0ba880416fbd0f60",
          "md5": "bcb9f988f1d571092277ad1e61c3d7f5"
        }
      ]
    }
  ]
}
