{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.component",
    "module": "identity-jar",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "resources",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "skin",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.extend",
          "module": "arms",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "skin.support",
          "module": "skin-support-appcompat",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "skin.support",
          "module": "skin-support-design",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "skin.support",
          "module": "skin-support-cardview",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "skin.support",
          "module": "skin-support-constraint-layout",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "identity-1.0.2.aar",
          "url": "identity-1.0.2.aar",
          "size": 81144,
          "sha512": "bef9411bab6431be0f32b5f831a637a66f80d49e0d7117d5182b053474c44913cf5cb49788ddf1fb8b901076921e427db858c294bd0763ed5450bf563d4099d8",
          "sha256": "56b02ee6807455161c38d855c6a4df4b42744f05b5857e9000b11eb7b11e7047",
          "sha1": "190cd69f0d764b0bc789e6bc4ab6c68a9c87db46",
          "md5": "4a915ac3be3f3cb1c3793af5abd1864b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "resources",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "skin",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.extend",
          "module": "arms",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "skin.support",
          "module": "skin-support-appcompat",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "skin.support",
          "module": "skin-support-design",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "skin.support",
          "module": "skin-support-cardview",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "skin.support",
          "module": "skin-support-constraint-layout",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "identity-1.0.2.aar",
          "url": "identity-1.0.2.aar",
          "size": 81144,
          "sha512": "bef9411bab6431be0f32b5f831a637a66f80d49e0d7117d5182b053474c44913cf5cb49788ddf1fb8b901076921e427db858c294bd0763ed5450bf563d4099d8",
          "sha256": "56b02ee6807455161c38d855c6a4df4b42744f05b5857e9000b11eb7b11e7047",
          "sha1": "190cd69f0d764b0bc789e6bc4ab6c68a9c87db46",
          "md5": "4a915ac3be3f3cb1c3793af5abd1864b"
        }
      ]
    }
  ]
}
