{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.data",
    "module": "bmob-jar",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.timecat.extend",
          "module": "arms",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "data",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "cn.leancloud",
          "module": "storage-android",
          "version": {
            "requires": "7.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "bmob-jar-1.1.0.aar",
          "url": "bmob-jar-1.1.0.aar",
          "size": 1708363,
          "sha512": "68389f99e183267e6815d5bdf2603f1526dc1dbf6e7d52274d0ea6007efa9a74fd5057ea07fcf6b103557589c13a5984d6eec226f1532b89f7c2f3883a3cc0f9",
          "sha256": "48d4966918fd2c593053451f31da12df58d88e3339df4f509aea7be76e0c5b6b",
          "sha1": "9f578fb54e90113cc74a0fe098814f2194ba5abb",
          "md5": "5babe6e2bf71085f0f91fe289644779e"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.timecat.extend",
          "module": "arms",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "data",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "cn.leancloud",
          "module": "storage-android",
          "version": {
            "requires": "7.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "bmob-jar-1.1.0.aar",
          "url": "bmob-jar-1.1.0.aar",
          "size": 1708363,
          "sha512": "68389f99e183267e6815d5bdf2603f1526dc1dbf6e7d52274d0ea6007efa9a74fd5057ea07fcf6b103557589c13a5984d6eec226f1532b89f7c2f3883a3cc0f9",
          "sha256": "48d4966918fd2c593053451f31da12df58d88e3339df4f509aea7be76e0c5b6b",
          "sha1": "9f578fb54e90113cc74a0fe098814f2194ba5abb",
          "md5": "5babe6e2bf71085f0f91fe289644779e"
        }
      ]
    }
  ]
}
