{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.data",
    "module": "bmob-jar",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.timecat.extend",
          "module": "arms",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "data",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.4"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "cn.leancloud",
          "module": "storage-android",
          "version": {
            "requires": "7.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.31"
          }
        }
      ],
      "files": [
        {
          "name": "bmob-jar-1.1.0.aar",
          "url": "bmob-jar-1.1.0.aar",
          "size": 1729197,
          "sha512": "bf209f6ef77eac8790483cbc3f7ceb491b1f85348dff84ad8273da095e764a40dfc58264eaf94300c8fbc261da678d91e3afa3c457bb7713140cd8e745aa4b48",
          "sha256": "1e887d7dc8eaadd9581af71ae9e8102f764e0ac3c9a3628065189c0c1a9618c3",
          "sha1": "ecab3da790b0b5a83a98078f12233d7057fb8a2e",
          "md5": "1dd2882db303367c737fb60035512a3a"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.timecat.extend",
          "module": "arms",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "data",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.4"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "cn.leancloud",
          "module": "storage-android",
          "version": {
            "requires": "7.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.31"
          }
        }
      ],
      "files": [
        {
          "name": "bmob-jar-1.1.0.aar",
          "url": "bmob-jar-1.1.0.aar",
          "size": 1729197,
          "sha512": "bf209f6ef77eac8790483cbc3f7ceb491b1f85348dff84ad8273da095e764a40dfc58264eaf94300c8fbc261da678d91e3afa3c457bb7713140cd8e745aa4b48",
          "sha256": "1e887d7dc8eaadd9581af71ae9e8102f764e0ac3c9a3628065189c0c1a9618c3",
          "sha1": "ecab3da790b0b5a83a98078f12233d7057fb8a2e",
          "md5": "1dd2882db303367c737fb60035512a3a"
        }
      ]
    }
  ]
}
