{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.data",
    "module": "bmob-jar",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.timecat.extend",
          "module": "arms",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "data",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.4"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "cn.leancloud",
          "module": "storage-android",
          "version": {
            "requires": "7.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "bmob-jar-1.1.0.aar",
          "url": "bmob-jar-1.1.0.aar",
          "size": 1709067,
          "sha512": "fb3070cba63efe1b62337cd93e718b03120e7f4a191e48bb10580565b9b6d554e690a981e55d0c6f9502d8c8443170dc5ccfb1453a1b00c8e3ddf9ca123e79f9",
          "sha256": "73d39e4ad8a32e07c3b83dfc73e64cc3a1d5eff65b4691e8197d5536af26b47a",
          "sha1": "3d72c65abbcba7ee5876d640ba16e1e634580d8a",
          "md5": "c4c6726a0e19591f36326f8ccea42d47"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.timecat.extend",
          "module": "arms",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "data",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.4"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "cn.leancloud",
          "module": "storage-android",
          "version": {
            "requires": "7.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "bmob-jar-1.1.0.aar",
          "url": "bmob-jar-1.1.0.aar",
          "size": 1709067,
          "sha512": "fb3070cba63efe1b62337cd93e718b03120e7f4a191e48bb10580565b9b6d554e690a981e55d0c6f9502d8c8443170dc5ccfb1453a1b00c8e3ddf9ca123e79f9",
          "sha256": "73d39e4ad8a32e07c3b83dfc73e64cc3a1d5eff65b4691e8197d5536af26b47a",
          "sha1": "3d72c65abbcba7ee5876d640ba16e1e634580d8a",
          "md5": "c4c6726a0e19591f36326f8ccea42d47"
        }
      ]
    }
  ]
}
