{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.module",
    "module": "module-scarlet-jar",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "com.timecat.extend",
          "module": "markdown",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "block",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "form",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.github.bijoysingh",
          "module": "android-basics",
          "version": {
            "requires": "5.1.0-x"
          }
        },
        {
          "group": "com.github.bijoysingh",
          "module": "ui-basics",
          "version": {
            "requires": "1.0.0-x"
          }
        },
        {
          "group": "com.github.bijoysingh",
          "module": "floating-bubble",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.evernote",
          "module": "android-job",
          "version": {
            "requires": "1.2.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.facebook.litho",
          "module": "litho-core",
          "version": {
            "requires": "0.31.0"
          }
        },
        {
          "group": "com.facebook.litho",
          "module": "litho-widget",
          "version": {
            "requires": "0.31.0"
          }
        },
        {
          "group": "com.facebook.soloader",
          "module": "soloader",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "module-scarlet-jar-1.1.0.aar",
          "url": "module-scarlet-jar-1.1.0.aar",
          "size": 3447873,
          "sha512": "15abbd9356816ee2d3c884fcbcc00e78a6fa6a366bfe4e6f7df6d45285268273820de19fd212541076455c7ac62a55406d1892c23bf3a951c0141a596612dae1",
          "sha256": "1fdfce79ae118ee32e14b1e4649a9cdedbc4a9d0bef5444199eeb15d71741ee7",
          "sha1": "5441ee7a35cf1019c73e5df22891e366d7137637",
          "md5": "91d59146dcce9d81717fa4247fbf392f"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "com.timecat.extend",
          "module": "markdown",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "block",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "form",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.github.bijoysingh",
          "module": "android-basics",
          "version": {
            "requires": "5.1.0-x"
          }
        },
        {
          "group": "com.github.bijoysingh",
          "module": "ui-basics",
          "version": {
            "requires": "1.0.0-x"
          }
        },
        {
          "group": "com.github.bijoysingh",
          "module": "floating-bubble",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.evernote",
          "module": "android-job",
          "version": {
            "requires": "1.2.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.facebook.litho",
          "module": "litho-core",
          "version": {
            "requires": "0.31.0"
          }
        },
        {
          "group": "com.facebook.litho",
          "module": "litho-widget",
          "version": {
            "requires": "0.31.0"
          }
        },
        {
          "group": "com.facebook.soloader",
          "module": "soloader",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "com.google.android",
          "module": "flexbox",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.github.jkwiecien",
          "module": "EasyImage",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "module-scarlet-jar-1.1.0.aar",
          "url": "module-scarlet-jar-1.1.0.aar",
          "size": 3447873,
          "sha512": "15abbd9356816ee2d3c884fcbcc00e78a6fa6a366bfe4e6f7df6d45285268273820de19fd212541076455c7ac62a55406d1892c23bf3a951c0141a596612dae1",
          "sha256": "1fdfce79ae118ee32e14b1e4649a9cdedbc4a9d0bef5444199eeb15d71741ee7",
          "sha1": "5441ee7a35cf1019c73e5df22891e366d7137637",
          "md5": "91d59146dcce9d81717fa4247fbf392f"
        }
      ]
    }
  ]
}
