{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.module",
    "module": "module-scarlet-jar",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "markdown",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "block",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "form",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.github.bijoysingh",
          "module": "android-basics",
          "version": {
            "requires": "5.1.0-x"
          }
        },
        {
          "group": "com.github.bijoysingh",
          "module": "ui-basics",
          "version": {
            "requires": "1.0.0-x"
          }
        },
        {
          "group": "com.github.bijoysingh",
          "module": "floating-bubble",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.evernote",
          "module": "android-job",
          "version": {
            "requires": "1.2.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.facebook.litho",
          "module": "litho-core",
          "version": {
            "requires": "0.31.0"
          }
        },
        {
          "group": "com.facebook.litho",
          "module": "litho-widget",
          "version": {
            "requires": "0.31.0"
          }
        },
        {
          "group": "com.facebook.soloader",
          "module": "soloader",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "module-scarlet-jar-1.1.0.aar",
          "url": "module-scarlet-jar-1.1.0.aar",
          "size": 3454641,
          "sha512": "d91b0fe851b2b0e45a9bcf0682ea3681d4566077b6d66b7b9655320837e4bc91b6502c2f05bbfb97fcb2cfea8bf769940940ad5cf6414e60966b2da5a5c64efc",
          "sha256": "b935df64b9f3b3d272d60d6040194cc4fc4c3d325d1e5f54ccf4dd095259128a",
          "sha1": "c19cf878bcad89c1bb976c30896d23380edc1961",
          "md5": "c12ec681ca6d8b004bd7fc10889e90b6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "markdown",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "block",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "form",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.github.bijoysingh",
          "module": "android-basics",
          "version": {
            "requires": "5.1.0-x"
          }
        },
        {
          "group": "com.github.bijoysingh",
          "module": "ui-basics",
          "version": {
            "requires": "1.0.0-x"
          }
        },
        {
          "group": "com.github.bijoysingh",
          "module": "floating-bubble",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.evernote",
          "module": "android-job",
          "version": {
            "requires": "1.2.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.facebook.litho",
          "module": "litho-core",
          "version": {
            "requires": "0.31.0"
          }
        },
        {
          "group": "com.facebook.litho",
          "module": "litho-widget",
          "version": {
            "requires": "0.31.0"
          }
        },
        {
          "group": "com.facebook.soloader",
          "module": "soloader",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "com.google.android",
          "module": "flexbox",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.github.jkwiecien",
          "module": "EasyImage",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "module-scarlet-jar-1.1.0.aar",
          "url": "module-scarlet-jar-1.1.0.aar",
          "size": 3454641,
          "sha512": "d91b0fe851b2b0e45a9bcf0682ea3681d4566077b6d66b7b9655320837e4bc91b6502c2f05bbfb97fcb2cfea8bf769940940ad5cf6414e60966b2da5a5c64efc",
          "sha256": "b935df64b9f3b3d272d60d6040194cc4fc4c3d325d1e5f54ccf4dd095259128a",
          "sha1": "c19cf878bcad89c1bb976c30896d23380edc1961",
          "md5": "c12ec681ca6d8b004bd7fc10889e90b6"
        }
      ]
    }
  ]
}
