{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.extend",
    "module": "arms-jar",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "rxjava"
            }
          ]
        },
        {
          "group": "com.github.VictorAlbertos.RxCache",
          "module": "runtime",
          "version": {
            "requires": "1.8.3-2.x"
          },
          "excludes": [
            {
              "group": "*",
              "module": "dagger"
            },
            {
              "group": "*",
              "module": "api"
            },
            {
              "group": "*",
              "module": "rxjava"
            }
          ]
        },
        {
          "group": "com.trello.rxlifecycle2",
          "module": "rxlifecycle",
          "version": {
            "requires": "2.2.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "jsr305"
            },
            {
              "group": "*",
              "module": "rxjava"
            }
          ]
        },
        {
          "group": "com.trello.rxlifecycle2",
          "module": "rxlifecycle-android",
          "version": {
            "requires": "2.2.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "annotation"
            },
            {
              "group": "*",
              "module": "rxandroid"
            },
            {
              "group": "*",
              "module": "rxlifecycle"
            },
            {
              "group": "*",
              "module": "rxjava"
            }
          ]
        },
        {
          "group": "me.jessyan",
          "module": "rxerrorhandler",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "com.tbruyelle.rxpermissions2",
          "module": "rxpermissions",
          "version": {
            "requires": "0.9.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "rxpermissions",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "okio"
            },
            {
              "group": "*",
              "module": "okhttp"
            }
          ]
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.22.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.8"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "4.7.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "arms-1.1.0.aar",
          "url": "arms-1.1.0.aar",
          "size": 141528,
          "sha512": "3cbc74a103768f0914e74bff7b48fb6246ff0e2b1ccc14470dfd8450123d9ea5e42ff8f7e47b3ce21bc6e50da6e89549dadd57e779a3b0bd6485d73a8434a409",
          "sha256": "60806436d36f46c73e931ac3017747394bba78618fa8b933fa213a6564ef7059",
          "sha1": "8fa6f3d32f8e4555290c5256f40d81883ccd246d",
          "md5": "0bb9c01b39ee89982be069022d9ddf76"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.VictorAlbertos.Jolyglot",
          "module": "gson",
          "version": {
            "requires": "0.0.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "gson"
            }
          ]
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "retrofit"
            },
            {
              "group": "*",
              "module": "okio"
            },
            {
              "group": "*",
              "module": "okhttp"
            },
            {
              "group": "*",
              "module": "gson"
            }
          ]
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.9.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "retrofit"
            },
            {
              "group": "*",
              "module": "okio"
            },
            {
              "group": "*",
              "module": "okhttp"
            },
            {
              "group": "*",
              "module": "rxjava"
            }
          ]
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "rxjava"
            }
          ]
        },
        {
          "group": "com.github.VictorAlbertos.RxCache",
          "module": "runtime",
          "version": {
            "requires": "1.8.3-2.x"
          },
          "excludes": [
            {
              "group": "*",
              "module": "dagger"
            },
            {
              "group": "*",
              "module": "api"
            },
            {
              "group": "*",
              "module": "rxjava"
            }
          ]
        },
        {
          "group": "com.trello.rxlifecycle2",
          "module": "rxlifecycle",
          "version": {
            "requires": "2.2.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "jsr305"
            },
            {
              "group": "*",
              "module": "rxjava"
            }
          ]
        },
        {
          "group": "com.trello.rxlifecycle2",
          "module": "rxlifecycle-android",
          "version": {
            "requires": "2.2.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "annotation"
            },
            {
              "group": "*",
              "module": "rxandroid"
            },
            {
              "group": "*",
              "module": "rxlifecycle"
            },
            {
              "group": "*",
              "module": "rxjava"
            }
          ]
        },
        {
          "group": "me.jessyan",
          "module": "rxerrorhandler",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "com.tbruyelle.rxpermissions2",
          "module": "rxpermissions",
          "version": {
            "requires": "0.9.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "rxpermissions",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "okio"
            },
            {
              "group": "*",
              "module": "okhttp"
            }
          ]
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.22.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.8"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "4.7.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "arms-1.1.0.aar",
          "url": "arms-1.1.0.aar",
          "size": 141528,
          "sha512": "3cbc74a103768f0914e74bff7b48fb6246ff0e2b1ccc14470dfd8450123d9ea5e42ff8f7e47b3ce21bc6e50da6e89549dadd57e779a3b0bd6485d73a8434a409",
          "sha256": "60806436d36f46c73e931ac3017747394bba78618fa8b933fa213a6564ef7059",
          "sha1": "8fa6f3d32f8e4555290c5256f40d81883ccd246d",
          "md5": "0bb9c01b39ee89982be069022d9ddf76"
        }
      ]
    }
  ]
}
