{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.extend",
    "module": "arms-jar",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "rxjava"
            }
          ]
        },
        {
          "group": "com.github.VictorAlbertos.RxCache",
          "module": "runtime",
          "version": {
            "requires": "1.8.3-2.x"
          },
          "excludes": [
            {
              "group": "*",
              "module": "dagger"
            },
            {
              "group": "*",
              "module": "api"
            },
            {
              "group": "*",
              "module": "rxjava"
            }
          ]
        },
        {
          "group": "com.trello.rxlifecycle2",
          "module": "rxlifecycle",
          "version": {
            "requires": "2.2.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "jsr305"
            },
            {
              "group": "*",
              "module": "rxjava"
            }
          ]
        },
        {
          "group": "com.trello.rxlifecycle2",
          "module": "rxlifecycle-android",
          "version": {
            "requires": "2.2.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "annotation"
            },
            {
              "group": "*",
              "module": "rxandroid"
            },
            {
              "group": "*",
              "module": "rxlifecycle"
            },
            {
              "group": "*",
              "module": "rxjava"
            }
          ]
        },
        {
          "group": "me.jessyan",
          "module": "rxerrorhandler",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "com.tbruyelle.rxpermissions2",
          "module": "rxpermissions",
          "version": {
            "requires": "0.9.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "rxpermissions",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "okio"
            },
            {
              "group": "*",
              "module": "okhttp"
            }
          ]
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.22.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.8"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "4.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "arms-1.1.0.aar",
          "url": "arms-1.1.0.aar",
          "size": 127897,
          "sha512": "31405f28b08fe90b4d16878b8dae2b488b107f0c2bb3c80f14cd243483c75d426ef364fd8f6f061c13d62ce94a1e0fd0bca3afb73ae400a39bc2be96dd898489",
          "sha256": "6db67d55d974d1ddc76fa57fc04177cbbe0303d9b968906af72341819db11a71",
          "sha1": "c52d357b6b855f614244996165196863e5333269",
          "md5": "dc2442d8f6d146f72fd60adaf20b6936"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.VictorAlbertos.Jolyglot",
          "module": "gson",
          "version": {
            "requires": "0.0.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "gson"
            }
          ]
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "retrofit"
            },
            {
              "group": "*",
              "module": "okio"
            },
            {
              "group": "*",
              "module": "okhttp"
            },
            {
              "group": "*",
              "module": "gson"
            }
          ]
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.9.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "retrofit"
            },
            {
              "group": "*",
              "module": "okio"
            },
            {
              "group": "*",
              "module": "okhttp"
            },
            {
              "group": "*",
              "module": "rxjava"
            }
          ]
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "rxjava"
            }
          ]
        },
        {
          "group": "com.github.VictorAlbertos.RxCache",
          "module": "runtime",
          "version": {
            "requires": "1.8.3-2.x"
          },
          "excludes": [
            {
              "group": "*",
              "module": "dagger"
            },
            {
              "group": "*",
              "module": "api"
            },
            {
              "group": "*",
              "module": "rxjava"
            }
          ]
        },
        {
          "group": "com.trello.rxlifecycle2",
          "module": "rxlifecycle",
          "version": {
            "requires": "2.2.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "jsr305"
            },
            {
              "group": "*",
              "module": "rxjava"
            }
          ]
        },
        {
          "group": "com.trello.rxlifecycle2",
          "module": "rxlifecycle-android",
          "version": {
            "requires": "2.2.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "annotation"
            },
            {
              "group": "*",
              "module": "rxandroid"
            },
            {
              "group": "*",
              "module": "rxlifecycle"
            },
            {
              "group": "*",
              "module": "rxjava"
            }
          ]
        },
        {
          "group": "me.jessyan",
          "module": "rxerrorhandler",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "com.tbruyelle.rxpermissions2",
          "module": "rxpermissions",
          "version": {
            "requires": "0.9.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "rxpermissions",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "okio"
            },
            {
              "group": "*",
              "module": "okhttp"
            }
          ]
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.22.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.8"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "4.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "arms-1.1.0.aar",
          "url": "arms-1.1.0.aar",
          "size": 127897,
          "sha512": "31405f28b08fe90b4d16878b8dae2b488b107f0c2bb3c80f14cd243483c75d426ef364fd8f6f061c13d62ce94a1e0fd0bca3afb73ae400a39bc2be96dd898489",
          "sha256": "6db67d55d974d1ddc76fa57fc04177cbbe0303d9b968906af72341819db11a71",
          "sha1": "c52d357b6b855f614244996165196863e5333269",
          "md5": "dc2442d8f6d146f72fd60adaf20b6936"
        }
      ]
    }
  ]
}
