{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.component",
    "module": "MView-ListView-jar",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "MView-ListView-1.0.0.aar",
          "url": "MView-ListView-1.0.0.aar",
          "size": 379991,
          "sha512": "82a0fd2b4ad49ea7890b5336b9136feae5b7594577a0f0de7558a492195ea495f2204ab71b4de1b99288f2925edfb689f8c8850d28f7783d768541a0c0ca102f",
          "sha256": "819b771fb20795e177227202bfe78873d74030b4685e181430b674a743c047cc",
          "sha1": "38ceaf910d8ced5bdd7b2c1bd58f5481ab7d9caf",
          "md5": "bb1100ac985cbebd561bda30cb20fce7"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "MView-ListView-1.0.0.aar",
          "url": "MView-ListView-1.0.0.aar",
          "size": 379991,
          "sha512": "82a0fd2b4ad49ea7890b5336b9136feae5b7594577a0f0de7558a492195ea495f2204ab71b4de1b99288f2925edfb689f8c8850d28f7783d768541a0c0ca102f",
          "sha256": "819b771fb20795e177227202bfe78873d74030b4685e181430b674a743c047cc",
          "sha1": "38ceaf910d8ced5bdd7b2c1bd58f5481ab7d9caf",
          "md5": "bb1100ac985cbebd561bda30cb20fce7"
        }
      ]
    }
  ]
}
