{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.middle",
    "module": "text-jar",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "block",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "text-1.0.0.aar",
          "url": "text-1.0.0.aar",
          "size": 153127,
          "sha512": "39fa8077408c18b6ba9e850561887135b19d7c56cd21137f5bf8f6f01356a2af5639f8c21a5724a3ab470e53172def3e83b75f349100551657e703eca74e4c74",
          "sha256": "f7916fd0228fe013cc2d377160dafd4c62311209fca7854dbc5310ca3a8ba63b",
          "sha1": "9f4982ca17bea336e970c9c9e8bfe38eea093002",
          "md5": "7fd33d70cc5e1746f893b24e16b88fc7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "block",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "text-1.0.0.aar",
          "url": "text-1.0.0.aar",
          "size": 153127,
          "sha512": "39fa8077408c18b6ba9e850561887135b19d7c56cd21137f5bf8f6f01356a2af5639f8c21a5724a3ab470e53172def3e83b75f349100551657e703eca74e4c74",
          "sha256": "f7916fd0228fe013cc2d377160dafd4c62311209fca7854dbc5310ca3a8ba63b",
          "sha1": "9f4982ca17bea336e970c9c9e8bfe38eea093002",
          "md5": "7fd33d70cc5e1746f893b24e16b88fc7"
        }
      ]
    }
  ]
}
