{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.shared",
    "module": "plugin-host-jar",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.timecat.component",
          "module": "router",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-host-jar-1.0.0.aar",
          "url": "plugin-host-jar-1.0.0.aar",
          "size": 18840,
          "sha512": "ba299cacf7cfd02018986fd5b32a05d5bffcc077afd181e5479924d0e142094fabbe69e8dd1b09557c97ec607a5e24a8e8a0ab1b54c269f8318074ea2df094c2",
          "sha256": "b6c571fa5fc8ad465b4f440fa28a286c6f4acdd18c399d9295337387791f29f5",
          "sha1": "2c12f2c78d44a5be075f247081a67833f4554437",
          "md5": "c6e9e25468e4caf5dc09d40009c0def1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.timecat.component",
          "module": "router",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-host-jar-1.0.0.aar",
          "url": "plugin-host-jar-1.0.0.aar",
          "size": 18840,
          "sha512": "ba299cacf7cfd02018986fd5b32a05d5bffcc077afd181e5479924d0e142094fabbe69e8dd1b09557c97ec607a5e24a8e8a0ab1b54c269f8318074ea2df094c2",
          "sha256": "b6c571fa5fc8ad465b4f440fa28a286c6f4acdd18c399d9295337387791f29f5",
          "sha1": "2c12f2c78d44a5be075f247081a67833f4554437",
          "md5": "c6e9e25468e4caf5dc09d40009c0def1"
        }
      ]
    }
  ]
}
