{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.extend",
    "module": "markdown-jar",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.31"
          }
        }
      ],
      "files": [
        {
          "name": "markdown-jar-1.0.0.aar",
          "url": "markdown-jar-1.0.0.aar",
          "size": 90667,
          "sha512": "123f3004233432d298f2bc36a0089cf76f352a4c68be40a90a7493916b15322d4315a6ee2c25ee1a0d3f1abcff5bc486f3e465de21b1ec91602c631ab01deda6",
          "sha256": "cab6aaff89eb35b78767011e0996527c5c48e47c1f41aeef26b566e47e2f2ffd",
          "sha1": "e2f1d33a563a19324a0434af237592fea2652a8d",
          "md5": "8d3967bf7272c339dac2a87d43048007"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "markdown-jar-1.0.0.aar",
          "url": "markdown-jar-1.0.0.aar",
          "size": 90667,
          "sha512": "123f3004233432d298f2bc36a0089cf76f352a4c68be40a90a7493916b15322d4315a6ee2c25ee1a0d3f1abcff5bc486f3e465de21b1ec91602c631ab01deda6",
          "sha256": "cab6aaff89eb35b78767011e0996527c5c48e47c1f41aeef26b566e47e2f2ffd",
          "sha1": "e2f1d33a563a19324a0434af237592fea2652a8d",
          "md5": "8d3967bf7272c339dac2a87d43048007"
        }
      ]
    }
  ]
}
