{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.data",
    "module": "greendao-jar",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "joda-time",
          "module": "joda-time",
          "version": {
            "requires": "2.10.10"
          }
        },
        {
          "group": "org.greenrobot",
          "module": "greendao",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "com.github.yuweiguocn",
          "module": "GreenDaoUpgradeHelper",
          "version": {
            "requires": "v2.1.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "greendao-1.0.0.aar",
          "url": "greendao-1.0.0.aar",
          "size": 29623,
          "sha512": "b43b31f0d5c48aa1005d43f5c736d99386063e28b187037678d2154817ec89c767a0f70e780ee7dabc2885d998c509504b196c67cda2c071fbe9bacc855f4a2c",
          "sha256": "e256a932dc57157451fdd1fd41d4719118d039bef7052381ab4f8cfa6fa2aa5b",
          "sha1": "af866d26f8968728b2276a3e03e7d5cf89d2c8ad",
          "md5": "13fb1fcc48bf88db3a6c4bd61c3c6d0c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "joda-time",
          "module": "joda-time",
          "version": {
            "requires": "2.10.10"
          }
        },
        {
          "group": "org.greenrobot",
          "module": "greendao",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "com.github.yuweiguocn",
          "module": "GreenDaoUpgradeHelper",
          "version": {
            "requires": "v2.1.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "greendao-1.0.0.aar",
          "url": "greendao-1.0.0.aar",
          "size": 29623,
          "sha512": "b43b31f0d5c48aa1005d43f5c736d99386063e28b187037678d2154817ec89c767a0f70e780ee7dabc2885d998c509504b196c67cda2c071fbe9bacc855f4a2c",
          "sha256": "e256a932dc57157451fdd1fd41d4719118d039bef7052381ab4f8cfa6fa2aa5b",
          "sha1": "af866d26f8968728b2276a3e03e7d5cf89d2c8ad",
          "md5": "13fb1fcc48bf88db3a6c4bd61c3c6d0c"
        }
      ]
    }
  ]
}
