{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.module",
    "module": "module-map-jar",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.timecat.identity",
          "module": "readonly",
          "version": {
            "requires": "+"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.timecat.middle",
          "module": "form",
          "version": {
            "requires": "+"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.timecat.middle",
          "module": "block",
          "version": {
            "requires": "+"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.timecat.middle",
          "module": "selector",
          "version": {
            "requires": "+"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "org.osmdroid",
          "module": "osmdroid-android",
          "version": {
            "requires": "6.1.11"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.0.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.0.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.0.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.0.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "module-map-jar-1.0.0.aar",
          "url": "module-map-jar-1.0.0.aar",
          "size": 214599,
          "sha512": "601d19dc2fe557df34820d4f68511c0ae48182c81099c10fde866177e78368fa4bf5ed649fa1e6f18423cc0964a9c04a10e73034b78e6d7fe1213d4b9b05e1a7",
          "sha256": "f06d80b8922bcf421eef87cfc279709df4840d3d49560bddd1f1172bcd561ce8",
          "sha1": "0d6f0295fa20c875061538e70aac511444914d77",
          "md5": "2ecbb46beb0dc4652586db6be3640796"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.timecat.identity",
          "module": "readonly",
          "version": {
            "requires": "+"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.timecat.middle",
          "module": "form",
          "version": {
            "requires": "+"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.timecat.middle",
          "module": "block",
          "version": {
            "requires": "+"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.timecat.middle",
          "module": "selector",
          "version": {
            "requires": "+"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "org.osmdroid",
          "module": "osmdroid-android",
          "version": {
            "requires": "6.1.11"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.0.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.0.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.0.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.0.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "module-map-jar-1.0.0.aar",
          "url": "module-map-jar-1.0.0.aar",
          "size": 214599,
          "sha512": "601d19dc2fe557df34820d4f68511c0ae48182c81099c10fde866177e78368fa4bf5ed649fa1e6f18423cc0964a9c04a10e73034b78e6d7fe1213d4b9b05e1a7",
          "sha256": "f06d80b8922bcf421eef87cfc279709df4840d3d49560bddd1f1172bcd561ce8",
          "sha1": "0d6f0295fa20c875061538e70aac511444914d77",
          "md5": "2ecbb46beb0dc4652586db6be3640796"
        }
      ]
    }
  ]
}
