{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.middle",
    "module": "middle-engine-jar",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "middle-engine-jar-1.0.0.aar",
          "url": "middle-engine-jar-1.0.0.aar",
          "size": 617797,
          "sha512": "58a04ed4eefb59599f9c3168a32768f4ed5fa97f5c2c7db6522f127f1fb988ac970eef795ebe730d70b013e01b13bdf7426aabf044979808e4a61bdb1131fdbe",
          "sha256": "1faab65fb0eebd5bf426ce6e34b6c6b684e45eb45d42f83b272c94691e517bce",
          "sha1": "b5f50427e623a50b345ef54e97915ac1bfa023da",
          "md5": "f3837200929bd984cac24ac96574e062"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "com.badlogicgames.gdx",
          "module": "gdx",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "com.badlogicgames.gdx",
          "module": "gdx-backend-android",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "com.badlogicgames.ashley",
          "module": "ashley",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "middle-engine-jar-1.0.0.aar",
          "url": "middle-engine-jar-1.0.0.aar",
          "size": 617797,
          "sha512": "58a04ed4eefb59599f9c3168a32768f4ed5fa97f5c2c7db6522f127f1fb988ac970eef795ebe730d70b013e01b13bdf7426aabf044979808e4a61bdb1131fdbe",
          "sha256": "1faab65fb0eebd5bf426ce6e34b6c6b684e45eb45d42f83b272c94691e517bce",
          "sha1": "b5f50427e623a50b345ef54e97915ac1bfa023da",
          "md5": "f3837200929bd984cac24ac96574e062"
        }
      ]
    }
  ]
}
