{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.module",
    "module": "module-user-jar",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "block",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "form",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "selector",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.data",
          "module": "bmob",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "readonly",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.layout",
          "module": "ui",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "service",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "router",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.makeramen",
          "module": "roundedimageview",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.akexorcist",
          "module": "round-corner-progress-bar",
          "version": {
            "requires": "2.1.2"
          }
        },
        {
          "group": "com.github.CarGuo.RickText",
          "module": "textUtilsLib",
          "version": {
            "requires": "v2.1.5"
          }
        },
        {
          "group": "com.github.razerdp",
          "module": "PhotoContents",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.github.razir.progressbutton",
          "module": "progressbutton",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.github.chengzhicao",
          "module": "ChannelView",
          "version": {
            "requires": "v1.1.0"
          }
        },
        {
          "group": "com.effective.android",
          "module": "panelSwitchHelper-androidx",
          "version": {
            "requires": "1.3.13"
          }
        }
      ],
      "files": [
        {
          "name": "module-user-jar-1.1.0.aar",
          "url": "module-user-jar-1.1.0.aar",
          "size": 3250551,
          "sha512": "9f4b0681c752178a26fb8a9de45ae26709d7dd4d7bc89f473ea1d855395abb1d3c74b1a3952ce90c59539772265f0d58b2e3f3b9db2331780b15dc2f9f7b7e5d",
          "sha256": "d7e900c20116562d0dc176b8ff01c1ef5df38bc61bd873be267b5c6977f14d45",
          "sha1": "f2167757767bd81d874f2f13d6ba86fcd13d8a21",
          "md5": "deec058c5714ba5bb5288b2a9b8deb49"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "block",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "form",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "selector",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.data",
          "module": "bmob",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "readonly",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.layout",
          "module": "ui",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "service",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "router",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.makeramen",
          "module": "roundedimageview",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.akexorcist",
          "module": "round-corner-progress-bar",
          "version": {
            "requires": "2.1.2"
          }
        },
        {
          "group": "com.github.CarGuo.RickText",
          "module": "textUtilsLib",
          "version": {
            "requires": "v2.1.5"
          }
        },
        {
          "group": "com.github.razerdp",
          "module": "PhotoContents",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.github.razir.progressbutton",
          "module": "progressbutton",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.github.chengzhicao",
          "module": "ChannelView",
          "version": {
            "requires": "v1.1.0"
          }
        },
        {
          "group": "com.effective.android",
          "module": "panelSwitchHelper-androidx",
          "version": {
            "requires": "1.3.13"
          }
        }
      ],
      "files": [
        {
          "name": "module-user-jar-1.1.0.aar",
          "url": "module-user-jar-1.1.0.aar",
          "size": 3250551,
          "sha512": "9f4b0681c752178a26fb8a9de45ae26709d7dd4d7bc89f473ea1d855395abb1d3c74b1a3952ce90c59539772265f0d58b2e3f3b9db2331780b15dc2f9f7b7e5d",
          "sha256": "d7e900c20116562d0dc176b8ff01c1ef5df38bc61bd873be267b5c6977f14d45",
          "sha1": "f2167757767bd81d874f2f13d6ba86fcd13d8a21",
          "md5": "deec058c5714ba5bb5288b2a9b8deb49"
        }
      ]
    }
  ]
}
