{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.module",
    "module": "module-user-jar",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "block",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "form",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.data",
          "module": "bmob",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "readonly",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.layout",
          "module": "ui",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "service",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "router",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.makeramen",
          "module": "roundedimageview",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.akexorcist",
          "module": "round-corner-progress-bar",
          "version": {
            "requires": "2.1.2"
          }
        },
        {
          "group": "com.github.CarGuo.RickText",
          "module": "textUtilsLib",
          "version": {
            "requires": "v2.1.5"
          }
        },
        {
          "group": "com.github.razerdp",
          "module": "PhotoContents",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.github.razir.progressbutton",
          "module": "progressbutton",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.github.chengzhicao",
          "module": "ChannelView",
          "version": {
            "requires": "v1.1.0"
          }
        },
        {
          "group": "com.effective.android",
          "module": "panelSwitchHelper-androidx",
          "version": {
            "requires": "1.3.13"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "module-user-jar-1.1.0.aar",
          "url": "module-user-jar-1.1.0.aar",
          "size": 3316331,
          "sha512": "299c6fecb6d4fa8add171453860c320dc7eafeab94419fe1e374fc8e8142facd81558e74377d6bcb665b6253f54dd02bef38359c7a224738fba8392f725154e7",
          "sha256": "7fa8603a6946904f5ea7cda838dc2fcf86196f71bacaa5f8a41684b536be920c",
          "sha1": "b1d030bc3b6c6e1feed1c0fc298e5af94a0ae684",
          "md5": "9ea62883bf8a9f33d14ba8512f0c3376"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "block",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "form",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.data",
          "module": "bmob",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "readonly",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.layout",
          "module": "ui",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "service",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "router",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.makeramen",
          "module": "roundedimageview",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.akexorcist",
          "module": "round-corner-progress-bar",
          "version": {
            "requires": "2.1.2"
          }
        },
        {
          "group": "com.github.CarGuo.RickText",
          "module": "textUtilsLib",
          "version": {
            "requires": "v2.1.5"
          }
        },
        {
          "group": "com.github.razerdp",
          "module": "PhotoContents",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.github.razir.progressbutton",
          "module": "progressbutton",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.github.chengzhicao",
          "module": "ChannelView",
          "version": {
            "requires": "v1.1.0"
          }
        },
        {
          "group": "com.effective.android",
          "module": "panelSwitchHelper-androidx",
          "version": {
            "requires": "1.3.13"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "module-user-jar-1.1.0.aar",
          "url": "module-user-jar-1.1.0.aar",
          "size": 3316331,
          "sha512": "299c6fecb6d4fa8add171453860c320dc7eafeab94419fe1e374fc8e8142facd81558e74377d6bcb665b6253f54dd02bef38359c7a224738fba8392f725154e7",
          "sha256": "7fa8603a6946904f5ea7cda838dc2fcf86196f71bacaa5f8a41684b536be920c",
          "sha1": "b1d030bc3b6c6e1feed1c0fc298e5af94a0ae684",
          "md5": "9ea62883bf8a9f33d14ba8512f0c3376"
        }
      ]
    }
  ]
}
