{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.module",
    "module": "module-user-jar",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "block",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "form",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "selector",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.data",
          "module": "bmob",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "readonly",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.layout",
          "module": "ui",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "service",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "router",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.makeramen",
          "module": "roundedimageview",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.akexorcist",
          "module": "round-corner-progress-bar",
          "version": {
            "requires": "2.1.2"
          }
        },
        {
          "group": "com.github.CarGuo.RickText",
          "module": "textUtilsLib",
          "version": {
            "requires": "v2.1.5"
          }
        },
        {
          "group": "com.github.razerdp",
          "module": "PhotoContents",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.github.razir.progressbutton",
          "module": "progressbutton",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.github.chengzhicao",
          "module": "ChannelView",
          "version": {
            "requires": "v1.1.0"
          }
        },
        {
          "group": "com.effective.android",
          "module": "panelSwitchHelper-androidx",
          "version": {
            "requires": "1.3.13"
          }
        }
      ],
      "files": [
        {
          "name": "module-user-jar-1.1.0.aar",
          "url": "module-user-jar-1.1.0.aar",
          "size": 3018642,
          "sha512": "ac11c0428ee0629f7c7efe678324735f0b40a9911c877775b3c10bcf512508ed815bcc277d706f2f8bc061dcb8a88a0ccb098f7d55af41eedd2d005f63710201",
          "sha256": "aea1be8bd800f44038dff60a4215f3d6e00de5ab580407362a058d7afbb5acaa",
          "sha1": "07b93cacf48a18c59c5a0b2858e3537c620a2d24",
          "md5": "ee051275334214466a0b01451545d76a"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "block",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "form",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "selector",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.data",
          "module": "bmob",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "readonly",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.layout",
          "module": "ui",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "service",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "router",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.makeramen",
          "module": "roundedimageview",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.akexorcist",
          "module": "round-corner-progress-bar",
          "version": {
            "requires": "2.1.2"
          }
        },
        {
          "group": "com.github.CarGuo.RickText",
          "module": "textUtilsLib",
          "version": {
            "requires": "v2.1.5"
          }
        },
        {
          "group": "com.github.razerdp",
          "module": "PhotoContents",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.github.razir.progressbutton",
          "module": "progressbutton",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.github.chengzhicao",
          "module": "ChannelView",
          "version": {
            "requires": "v1.1.0"
          }
        },
        {
          "group": "com.effective.android",
          "module": "panelSwitchHelper-androidx",
          "version": {
            "requires": "1.3.13"
          }
        }
      ],
      "files": [
        {
          "name": "module-user-jar-1.1.0.aar",
          "url": "module-user-jar-1.1.0.aar",
          "size": 3018642,
          "sha512": "ac11c0428ee0629f7c7efe678324735f0b40a9911c877775b3c10bcf512508ed815bcc277d706f2f8bc061dcb8a88a0ccb098f7d55af41eedd2d005f63710201",
          "sha256": "aea1be8bd800f44038dff60a4215f3d6e00de5ab580407362a058d7afbb5acaa",
          "sha1": "07b93cacf48a18c59c5a0b2858e3537c620a2d24",
          "md5": "ee051275334214466a0b01451545d76a"
        }
      ]
    }
  ]
}
