{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.middle",
    "module": "form-jar",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "router",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "readonly",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.page",
          "module": "base",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.layout",
          "module": "ui",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "form-jar-1.0.3.aar",
          "url": "form-jar-1.0.3.aar",
          "size": 106870,
          "sha512": "3fb15fb5d9a9a00479c55587eee7c7edaee18d8702f5836d179dcf61131a21984497286405d56ee8980e7cdc3e3dee5a8fde99d487c5e236037a6c6f8dc379ae",
          "sha256": "04b943224e04254e1d70a7b05d31d31b3dc3a255a90a5bdb26cb01314b25f424",
          "sha1": "cfb3561ce59dd916b78f3b9a26d9c09d095e8471",
          "md5": "a35c97f77ac442e574b81a2040e0323b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "router",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "readonly",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.page",
          "module": "base",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.layout",
          "module": "ui",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "form-jar-1.0.3.aar",
          "url": "form-jar-1.0.3.aar",
          "size": 106870,
          "sha512": "3fb15fb5d9a9a00479c55587eee7c7edaee18d8702f5836d179dcf61131a21984497286405d56ee8980e7cdc3e3dee5a8fde99d487c5e236037a6c6f8dc379ae",
          "sha256": "04b943224e04254e1d70a7b05d31d31b3dc3a255a90a5bdb26cb01314b25f424",
          "sha1": "cfb3561ce59dd916b78f3b9a26d9c09d095e8471",
          "md5": "a35c97f77ac442e574b81a2040e0323b"
        }
      ]
    }
  ]
}
