{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.identity",
    "module": "service-jar",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "service-1.0.2.aar",
          "url": "service-1.0.2.aar",
          "size": 10174,
          "sha512": "6d1dc7bbf949061c0ed9daf6d098ba8687da201844a11b17597e5bf91fb5d4178e9f1823046b0b9573dce28c96447e277afc8ebd6474bf1463b46ace2aa10ad5",
          "sha256": "86eb3a2e065ae151b4ff3dccfa04e2b25aba0acd2e76b72a88d963a44f504fa8",
          "sha1": "1897b6ecafdb22011ce9354d95e47b87f62d4def",
          "md5": "dfbabb4ef46d48e2a3d0143c24b05974"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "service-1.0.2.aar",
          "url": "service-1.0.2.aar",
          "size": 10174,
          "sha512": "6d1dc7bbf949061c0ed9daf6d098ba8687da201844a11b17597e5bf91fb5d4178e9f1823046b0b9573dce28c96447e277afc8ebd6474bf1463b46ace2aa10ad5",
          "sha256": "86eb3a2e065ae151b4ff3dccfa04e2b25aba0acd2e76b72a88d963a44f504fa8",
          "sha1": "1897b6ecafdb22011ce9354d95e47b87f62d4def",
          "md5": "dfbabb4ef46d48e2a3d0143c24b05974"
        }
      ]
    }
  ]
}
