{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.widget",
    "module": "board-jar",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.5.0-alpha01"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "androidx.dynamicanimation",
          "module": "dynamicanimation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "me.everything",
          "module": "overscroll-decor-android",
          "version": {
            "requires": "1.0.4"
          }
        },
        {
          "group": "jp.wasabeef",
          "module": "recyclerview-animators",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "board-1.0.0.aar",
          "url": "board-1.0.0.aar",
          "size": 258566,
          "sha512": "ae7435ab2324baff346cb0b8278b0adb82e6fc4482764a5bc9e6ef35e351ee5cbab30347b40cd241a35416fde91dbf07bd674572b99d3f1424c778334e546582",
          "sha256": "113a17fdb15141131479688dc2c3ea6979d985a3d0106bc278aa43a16e668f9b",
          "sha1": "018e7674215f1cc71488759311ce6533c17da09a",
          "md5": "f6a1ee2d65e13e518632defba88d02ac"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.5.0-alpha01"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "androidx.dynamicanimation",
          "module": "dynamicanimation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "me.everything",
          "module": "overscroll-decor-android",
          "version": {
            "requires": "1.0.4"
          }
        },
        {
          "group": "jp.wasabeef",
          "module": "recyclerview-animators",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "board-1.0.0.aar",
          "url": "board-1.0.0.aar",
          "size": 258566,
          "sha512": "ae7435ab2324baff346cb0b8278b0adb82e6fc4482764a5bc9e6ef35e351ee5cbab30347b40cd241a35416fde91dbf07bd674572b99d3f1424c778334e546582",
          "sha256": "113a17fdb15141131479688dc2c3ea6979d985a3d0106bc278aa43a16e668f9b",
          "sha1": "018e7674215f1cc71488759311ce6533c17da09a",
          "md5": "f6a1ee2d65e13e518632defba88d02ac"
        }
      ]
    }
  ]
}
