{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.module",
    "module": "module-bugly-jar",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.timecat.extend",
          "module": "arms",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "router",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "service",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "readonly",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.tencent.bugly",
          "module": "crashreport",
          "version": {
            "requires": "4.1.9"
          }
        },
        {
          "group": "com.umeng.umsdk",
          "module": "common",
          "version": {
            "requires": "9.5.3"
          }
        },
        {
          "group": "com.umeng.umsdk",
          "module": "asms",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "com.umeng.umsdk",
          "module": "apm",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "module-bugly-jar-1.1.0.aar",
          "url": "module-bugly-jar-1.1.0.aar",
          "size": 10985,
          "sha512": "14738ce5dd5b6f7ed82cd2a6f650d0b798f82fac5550cd1ca6769d1da4a14085fef1d7ed9b6a3a695c2c1c616d6be3d21098d1d26c7b0bdc3b713d51f09edcc0",
          "sha256": "ee453e6ec16a96eca92ee8d2b5ce76ddeebb356ddbc4b194c886f7be1592abad",
          "sha1": "223e6633e2ba965f7bca77a4597e926ac3f10a6f",
          "md5": "4e8ae072684ee23b57af0b5e9552ff06"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.timecat.extend",
          "module": "arms",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "router",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "service",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "readonly",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.tencent.bugly",
          "module": "crashreport",
          "version": {
            "requires": "4.1.9"
          }
        },
        {
          "group": "com.umeng.umsdk",
          "module": "common",
          "version": {
            "requires": "9.5.3"
          }
        },
        {
          "group": "com.umeng.umsdk",
          "module": "asms",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "com.umeng.umsdk",
          "module": "apm",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "module-bugly-jar-1.1.0.aar",
          "url": "module-bugly-jar-1.1.0.aar",
          "size": 10985,
          "sha512": "14738ce5dd5b6f7ed82cd2a6f650d0b798f82fac5550cd1ca6769d1da4a14085fef1d7ed9b6a3a695c2c1c616d6be3d21098d1d26c7b0bdc3b713d51f09edcc0",
          "sha256": "ee453e6ec16a96eca92ee8d2b5ce76ddeebb356ddbc4b194c886f7be1592abad",
          "sha1": "223e6633e2ba965f7bca77a4597e926ac3f10a6f",
          "md5": "4e8ae072684ee23b57af0b5e9552ff06"
        }
      ]
    }
  ]
}
