{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.module",
    "module": "module-plugin-jar",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.timecat.middle",
          "module": "form",
          "version": {
            "requires": "+"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.timecat.middle",
          "module": "block",
          "version": {
            "requires": "+"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.timecat.data",
          "module": "bmob",
          "version": {
            "requires": "+"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.timecat.identity",
          "module": "readonly",
          "version": {
            "requires": "+"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.timecat.plugin",
          "module": "record-api-holder",
          "version": {
            "requires": "+"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.timecat.shared",
          "module": "plugin-host",
          "version": {
            "requires": "+"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.tencent.shadow.dynamic",
          "module": "host",
          "version": {
            "requires": "2.0.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.timecat.middle",
          "module": "download",
          "version": {
            "requires": "+"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.0.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.0.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.0.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.0.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "module-plugin-1.0.0.aar",
          "url": "module-plugin-1.0.0.aar",
          "size": 304838,
          "sha512": "259bb1865f34403e559307c926777375ab19d61ac768d15e7d992314725d81a8966ffb28720719092b5d989402f4891b9d79fbf1492ab81ff0b4c7ba342c4d92",
          "sha256": "6227e0a48637921f86d89586d753194aa262e34b08e3057cf67a1df884f3b387",
          "sha1": "0fc02c8bcd1a51d9a133f5b876e417b34f897325",
          "md5": "0e8e956afd5e4c17cea3b9ac63299322"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.timecat.middle",
          "module": "form",
          "version": {
            "requires": "+"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.timecat.middle",
          "module": "block",
          "version": {
            "requires": "+"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.timecat.data",
          "module": "bmob",
          "version": {
            "requires": "+"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.timecat.identity",
          "module": "readonly",
          "version": {
            "requires": "+"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.timecat.plugin",
          "module": "record-api-holder",
          "version": {
            "requires": "+"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.timecat.shared",
          "module": "plugin-host",
          "version": {
            "requires": "+"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.tencent.shadow.dynamic",
          "module": "host",
          "version": {
            "requires": "2.0.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.timecat.middle",
          "module": "download",
          "version": {
            "requires": "+"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.0.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.0.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.0.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.0.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "module-plugin-1.0.0.aar",
          "url": "module-plugin-1.0.0.aar",
          "size": 304838,
          "sha512": "259bb1865f34403e559307c926777375ab19d61ac768d15e7d992314725d81a8966ffb28720719092b5d989402f4891b9d79fbf1492ab81ff0b4c7ba342c4d92",
          "sha256": "6227e0a48637921f86d89586d753194aa262e34b08e3057cf67a1df884f3b387",
          "sha1": "0fc02c8bcd1a51d9a133f5b876e417b34f897325",
          "md5": "0e8e956afd5e4c17cea3b9ac63299322"
        }
      ]
    }
  ]
}
