{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.module",
    "module": "module-plugin-jar",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.timecat.middle",
          "module": "form",
          "version": {
            "requires": "+"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.timecat.middle",
          "module": "block",
          "version": {
            "requires": "+"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.timecat.data",
          "module": "bmob",
          "version": {
            "requires": "+"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.timecat.identity",
          "module": "readonly",
          "version": {
            "requires": "+"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.timecat.plugin",
          "module": "record-api-holder",
          "version": {
            "requires": "+"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.timecat.shared",
          "module": "plugin-host",
          "version": {
            "requires": "+"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.tencent.shadow.dynamic",
          "module": "host",
          "version": {
            "requires": "+"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.github.Z-P-J",
          "module": "ZDownloader",
          "version": {
            "requires": "1.0.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.0.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.0.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.0.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.0.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "module-plugin-1.0.0.aar",
          "url": "module-plugin-1.0.0.aar",
          "size": 288938,
          "sha512": "6ff4f7a75e265ad32d2d70320853b67e2cd23f1356bb1378ba5225ae239909ad628e31f4015001c5d5b6d4f4b057b8cbe1be1c0b2a47f8c7a4f6f4676678fd45",
          "sha256": "36bba2dae4350d1ba42a970ea14d112375c04fcb161d3b4d3aa2f464f1f0cad4",
          "sha1": "a0b6826496ceff6bacbbeb5cab3ddf0a377d7820",
          "md5": "e7dc9079b69864653cbbfc19dbf5a0b6"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.timecat.middle",
          "module": "form",
          "version": {
            "requires": "+"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.timecat.middle",
          "module": "block",
          "version": {
            "requires": "+"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.timecat.data",
          "module": "bmob",
          "version": {
            "requires": "+"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.timecat.identity",
          "module": "readonly",
          "version": {
            "requires": "+"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.timecat.plugin",
          "module": "record-api-holder",
          "version": {
            "requires": "+"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.timecat.shared",
          "module": "plugin-host",
          "version": {
            "requires": "+"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.tencent.shadow.dynamic",
          "module": "host",
          "version": {
            "requires": "+"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.github.Z-P-J",
          "module": "ZDownloader",
          "version": {
            "requires": "1.0.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.0.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.0.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.0.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.0.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "module-plugin-1.0.0.aar",
          "url": "module-plugin-1.0.0.aar",
          "size": 288938,
          "sha512": "6ff4f7a75e265ad32d2d70320853b67e2cd23f1356bb1378ba5225ae239909ad628e31f4015001c5d5b6d4f4b057b8cbe1be1c0b2a47f8c7a4f6f4676678fd45",
          "sha256": "36bba2dae4350d1ba42a970ea14d112375c04fcb161d3b4d3aa2f464f1f0cad4",
          "sha1": "a0b6826496ceff6bacbbeb5cab3ddf0a377d7820",
          "md5": "e7dc9079b69864653cbbfc19dbf5a0b6"
        }
      ]
    }
  ]
}
