{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.module",
    "module": "module-plugin-jar",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.timecat.middle",
          "module": "form",
          "version": {
            "requires": "+"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.timecat.middle",
          "module": "block",
          "version": {
            "requires": "+"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.timecat.data",
          "module": "bmob",
          "version": {
            "requires": "+"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.timecat.identity",
          "module": "readonly",
          "version": {
            "requires": "+"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.timecat.plugin",
          "module": "record-api-holder",
          "version": {
            "requires": "+"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.timecat.shared",
          "module": "plugin-host",
          "version": {
            "requires": "+"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.tencent.shadow.dynamic",
          "module": "host",
          "version": {
            "requires": "2.0.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.timecat.middle",
          "module": "download",
          "version": {
            "requires": "+"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.0.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.0.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.0.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.0.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "module-plugin-1.0.0.aar",
          "url": "module-plugin-1.0.0.aar",
          "size": 304726,
          "sha512": "759874cd1bfcd10ab12e5f39964dd5431160d818e8163f9045860abbbe182001dceff2aad50fdbbe6c4f84a519fcf582a2ac5199519fe139c83a1906017712d6",
          "sha256": "db0335c986d47c8f052e0f90854f7d66eeaffc114e337e7409084b70c3725f72",
          "sha1": "b2fae60fcce0a0ec7089a24f854c15c2fea88123",
          "md5": "c2b8dddb695c3ed1a7f050da82f93a2d"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.timecat.middle",
          "module": "form",
          "version": {
            "requires": "+"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.timecat.middle",
          "module": "block",
          "version": {
            "requires": "+"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.timecat.data",
          "module": "bmob",
          "version": {
            "requires": "+"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.timecat.identity",
          "module": "readonly",
          "version": {
            "requires": "+"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.timecat.plugin",
          "module": "record-api-holder",
          "version": {
            "requires": "+"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.timecat.shared",
          "module": "plugin-host",
          "version": {
            "requires": "+"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.tencent.shadow.dynamic",
          "module": "host",
          "version": {
            "requires": "2.0.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.timecat.middle",
          "module": "download",
          "version": {
            "requires": "+"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.0.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.0.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.0.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.0.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "module-plugin-1.0.0.aar",
          "url": "module-plugin-1.0.0.aar",
          "size": 304726,
          "sha512": "759874cd1bfcd10ab12e5f39964dd5431160d818e8163f9045860abbbe182001dceff2aad50fdbbe6c4f84a519fcf582a2ac5199519fe139c83a1906017712d6",
          "sha256": "db0335c986d47c8f052e0f90854f7d66eeaffc114e337e7409084b70c3725f72",
          "sha1": "b2fae60fcce0a0ec7089a24f854c15c2fea88123",
          "md5": "c2b8dddb695c3ed1a7f050da82f93a2d"
        }
      ]
    }
  ]
}
