{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.identity",
    "module": "resources-jar",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "resources-1.0.0.aar",
          "url": "resources-1.0.0.aar",
          "size": 2173265,
          "sha512": "31dcd37c438ff57e68e9cac9b586f5bbb798826708c0fd881f682459d960de6ba740f7b391d6a38f3343cf0be84b6c0a34c82ed971cde62240e73a8815bd5fe3",
          "sha256": "eb9bb8989843c4d201c0156e76a3127b69bdbd2357369cd3b28ebfd89d50162b",
          "sha1": "bf329f619c077577d05492aa28bc96bdf9d376a2",
          "md5": "8ba533bb5ed4741d666b2bc3b3521194"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "resources-1.0.0.aar",
          "url": "resources-1.0.0.aar",
          "size": 2173265,
          "sha512": "31dcd37c438ff57e68e9cac9b586f5bbb798826708c0fd881f682459d960de6ba740f7b391d6a38f3343cf0be84b6c0a34c82ed971cde62240e73a8815bd5fe3",
          "sha256": "eb9bb8989843c4d201c0156e76a3127b69bdbd2357369cd3b28ebfd89d50162b",
          "sha1": "bf329f619c077577d05492aa28bc96bdf9d376a2",
          "md5": "8ba533bb5ed4741d666b2bc3b3521194"
        }
      ]
    }
  ]
}
