{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.identity",
    "module": "resources-jar",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "resources-1.0.0.aar",
          "url": "resources-1.0.0.aar",
          "size": 2172884,
          "sha512": "e7229cf2d487d9c422d7f004fb330ebec7d18aac6bd3c415a3dd782d4f4796d87fc47ebad382c6489505e233e14566fce8995b0d10ed1d8ad70ea0cdf6a0d072",
          "sha256": "48c1070d82d7465dd881061d03d4c7da1ed70e6dcdde18c003da718e7a26f8d2",
          "sha1": "bd709769adab104a60b42f51d7a2239605192d0b",
          "md5": "762e6766ccf9e4925c9d05bd990862dc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "resources-1.0.0.aar",
          "url": "resources-1.0.0.aar",
          "size": 2172884,
          "sha512": "e7229cf2d487d9c422d7f004fb330ebec7d18aac6bd3c415a3dd782d4f4796d87fc47ebad382c6489505e233e14566fce8995b0d10ed1d8ad70ea0cdf6a0d072",
          "sha256": "48c1070d82d7465dd881061d03d4c7da1ed70e6dcdde18c003da718e7a26f8d2",
          "sha1": "bd709769adab104a60b42f51d7a2239605192d0b",
          "md5": "762e6766ccf9e4925c9d05bd990862dc"
        }
      ]
    }
  ]
}
