{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.component",
    "module": "template-jar",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.timecat.component",
          "module": "identity",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.data",
          "module": "system",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "sdk",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.element",
          "module": "listview",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.5.0-alpha01"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "androidx.dynamicanimation",
          "module": "dynamicanimation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.github.markomilos",
          "module": "paginate",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "4.1.0"
          }
        },
        {
          "group": "de.hdodenhof",
          "module": "circleimageview",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.github.CymChad",
          "module": "BaseRecyclerViewAdapterHelper",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "com.github.duanhong169",
          "module": "drawabletoolbox",
          "version": {
            "requires": "1.0.7"
          }
        },
        {
          "group": "com.github.sephiroth74",
          "module": "NumberSlidingPicker",
          "version": {
            "requires": "v1.0.3"
          }
        },
        {
          "group": "com.afollestad",
          "module": "vvalidator",
          "version": {
            "requires": "0.5.2"
          }
        },
        {
          "group": "eu.davidea",
          "module": "flipview",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.iwgang",
          "module": "countdownview",
          "version": {
            "requires": "2.1.6"
          }
        },
        {
          "group": "com.haibin",
          "module": "calendarview",
          "version": {
            "requires": "3.2.7"
          }
        },
        {
          "group": "com.github.chenBingX",
          "module": "SuperTextView",
          "version": {
            "requires": "v3.2.5"
          }
        },
        {
          "group": "com.github.zagum",
          "module": "Android-ExpandIcon",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.github.githubwing",
          "module": "ByeBurger",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "com.github.florent37",
          "module": "viewtooltip",
          "version": {
            "requires": "1.1.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0.aar",
          "url": "template-1.0.0.aar",
          "size": 233941,
          "sha512": "bf5b063c0d190fdca167ad0b2785479994412721902be40bdf14043d97f66eb526d42725f48e9414fa10d3099f1c1f054310cbeeef13e29949af063361c629e7",
          "sha256": "082c2dd3f7f0f27f1a18c26a04509ffdfe6ed80290cf19a93df2c7e9c2cbaba1",
          "sha1": "0e0dcddb631fec67cc68c933a8824e3dcf743e36",
          "md5": "aea689924919de0ec9d8954aebdb2b24"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "identity",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.data",
          "module": "system",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "sdk",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.element",
          "module": "listview",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.5.0-alpha01"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "androidx.dynamicanimation",
          "module": "dynamicanimation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.github.markomilos",
          "module": "paginate",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "4.1.0"
          }
        },
        {
          "group": "de.hdodenhof",
          "module": "circleimageview",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.github.CymChad",
          "module": "BaseRecyclerViewAdapterHelper",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "com.github.duanhong169",
          "module": "drawabletoolbox",
          "version": {
            "requires": "1.0.7"
          }
        },
        {
          "group": "com.github.sephiroth74",
          "module": "NumberSlidingPicker",
          "version": {
            "requires": "v1.0.3"
          }
        },
        {
          "group": "com.afollestad",
          "module": "vvalidator",
          "version": {
            "requires": "0.5.2"
          }
        },
        {
          "group": "eu.davidea",
          "module": "flipview",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.iwgang",
          "module": "countdownview",
          "version": {
            "requires": "2.1.6"
          }
        },
        {
          "group": "com.haibin",
          "module": "calendarview",
          "version": {
            "requires": "3.2.7"
          }
        },
        {
          "group": "com.github.chenBingX",
          "module": "SuperTextView",
          "version": {
            "requires": "v3.2.5"
          }
        },
        {
          "group": "com.github.zagum",
          "module": "Android-ExpandIcon",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.github.githubwing",
          "module": "ByeBurger",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "com.github.florent37",
          "module": "viewtooltip",
          "version": {
            "requires": "1.1.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "template-1.0.0.aar",
          "url": "template-1.0.0.aar",
          "size": 233941,
          "sha512": "bf5b063c0d190fdca167ad0b2785479994412721902be40bdf14043d97f66eb526d42725f48e9414fa10d3099f1c1f054310cbeeef13e29949af063361c629e7",
          "sha256": "082c2dd3f7f0f27f1a18c26a04509ffdfe6ed80290cf19a93df2c7e9c2cbaba1",
          "sha1": "0e0dcddb631fec67cc68c933a8824e3dcf743e36",
          "md5": "aea689924919de0ec9d8954aebdb2b24"
        }
      ]
    }
  ]
}
