{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.layout",
    "module": "ui-jar",
    "version": "1.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "identity",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.data",
          "module": "system",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "sdk",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.element",
          "module": "listview",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "androidx.dynamicanimation",
          "module": "dynamicanimation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.github.markomilos",
          "module": "paginate",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "4.1.0"
          }
        },
        {
          "group": "de.hdodenhof",
          "module": "circleimageview",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.github.CymChad",
          "module": "BaseRecyclerViewAdapterHelper",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "com.github.duanhong169",
          "module": "drawabletoolbox",
          "version": {
            "requires": "1.0.7"
          }
        },
        {
          "group": "com.github.sephiroth74",
          "module": "NumberSlidingPicker",
          "version": {
            "requires": "v1.0.3"
          }
        },
        {
          "group": "com.afollestad",
          "module": "vvalidator",
          "version": {
            "requires": "0.5.2"
          }
        },
        {
          "group": "eu.davidea",
          "module": "flipview",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.iwgang",
          "module": "countdownview",
          "version": {
            "requires": "2.1.6"
          }
        },
        {
          "group": "com.haibin",
          "module": "calendarview",
          "version": {
            "requires": "3.2.7"
          }
        },
        {
          "group": "com.github.githubwing",
          "module": "ByeBurger",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "com.github.florent37",
          "module": "viewtooltip",
          "version": {
            "requires": "1.1.8"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ui-1.0.7.aar",
          "url": "ui-1.0.7.aar",
          "size": 1048528,
          "sha512": "04ff5d2c6cb94a20df1d6e0b115c531b46d9bf53369f7f851921904cc402b59f94378770062d21e0ebc45fcff02f1aa5f14009f0d5b8a72cc77c67900c1f4b5e",
          "sha256": "74ef13356beb6f394ae6e292dcdaeded788beeed1a9612faedff2ac2999cca2d",
          "sha1": "683b074a5aa0183907a9b47752dbeaacee2f21d9",
          "md5": "bf8f0d46f012d464135a5accf80fac3e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "identity",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.data",
          "module": "system",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "sdk",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.element",
          "module": "listview",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "androidx.dynamicanimation",
          "module": "dynamicanimation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.github.markomilos",
          "module": "paginate",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "4.1.0"
          }
        },
        {
          "group": "de.hdodenhof",
          "module": "circleimageview",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.github.CymChad",
          "module": "BaseRecyclerViewAdapterHelper",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "com.github.duanhong169",
          "module": "drawabletoolbox",
          "version": {
            "requires": "1.0.7"
          }
        },
        {
          "group": "com.github.sephiroth74",
          "module": "NumberSlidingPicker",
          "version": {
            "requires": "v1.0.3"
          }
        },
        {
          "group": "com.afollestad",
          "module": "vvalidator",
          "version": {
            "requires": "0.5.2"
          }
        },
        {
          "group": "eu.davidea",
          "module": "flipview",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.iwgang",
          "module": "countdownview",
          "version": {
            "requires": "2.1.6"
          }
        },
        {
          "group": "com.haibin",
          "module": "calendarview",
          "version": {
            "requires": "3.2.7"
          }
        },
        {
          "group": "com.github.githubwing",
          "module": "ByeBurger",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "com.github.florent37",
          "module": "viewtooltip",
          "version": {
            "requires": "1.1.8"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ui-1.0.7.aar",
          "url": "ui-1.0.7.aar",
          "size": 1048528,
          "sha512": "04ff5d2c6cb94a20df1d6e0b115c531b46d9bf53369f7f851921904cc402b59f94378770062d21e0ebc45fcff02f1aa5f14009f0d5b8a72cc77c67900c1f4b5e",
          "sha256": "74ef13356beb6f394ae6e292dcdaeded788beeed1a9612faedff2ac2999cca2d",
          "sha1": "683b074a5aa0183907a9b47752dbeaacee2f21d9",
          "md5": "bf8f0d46f012d464135a5accf80fac3e"
        }
      ]
    }
  ]
}
