{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.show",
    "module": "window-jar",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "window-1.0.1.aar",
          "url": "window-1.0.1.aar",
          "size": 59446,
          "sha512": "2dc3834d2ad0d16c8e16741efa6bd4a1503040138b5e2c977aae2b526f4fcca8506cd58f355b101f185b860011d21a781626cf58139503a3cf71839932f1e925",
          "sha256": "2f796622236997e25f08e8f3f1e9e29cff37faa2e1209270480a854ac43a19e0",
          "sha1": "6416958d465ded2b4ac248dbd35d7891d240c0a3",
          "md5": "7152afc4fc2ad34e3f9e549b46019a1e"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "window-1.0.1.aar",
          "url": "window-1.0.1.aar",
          "size": 59446,
          "sha512": "2dc3834d2ad0d16c8e16741efa6bd4a1503040138b5e2c977aae2b526f4fcca8506cd58f355b101f185b860011d21a781626cf58139503a3cf71839932f1e925",
          "sha256": "2f796622236997e25f08e8f3f1e9e29cff37faa2e1209270480a854ac43a19e0",
          "sha1": "6416958d465ded2b4ac248dbd35d7891d240c0a3",
          "md5": "7152afc4fc2ad34e3f9e549b46019a1e"
        }
      ]
    }
  ]
}
