{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.data",
    "module": "bmob-jar",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.timecat.extend",
          "module": "arms",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "data",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "cn.leancloud",
          "module": "storage-android",
          "version": {
            "requires": "7.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "bmob-1.1.0.aar",
          "url": "bmob-1.1.0.aar",
          "size": 1708384,
          "sha512": "979e70ee0dc11f53522ab108a36a1f6a344947af18fa6bfd70a3c61921eeec4637f4a06d512ae2ddf4f92b1e21a4e3f5989ac816eda85ced83bc3be700a3e3f2",
          "sha256": "a790569678fb7314a9c7bb0539e23932c407be7f0b6483b7e72b91b499698c7a",
          "sha1": "1b9947e688cd1f6d344b3c87e1dfd8b04f9ea9bb",
          "md5": "c3be6db0105dec76fc843c1a21caaf1a"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.timecat.extend",
          "module": "arms",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "data",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "cn.leancloud",
          "module": "storage-android",
          "version": {
            "requires": "7.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "bmob-1.1.0.aar",
          "url": "bmob-1.1.0.aar",
          "size": 1708384,
          "sha512": "979e70ee0dc11f53522ab108a36a1f6a344947af18fa6bfd70a3c61921eeec4637f4a06d512ae2ddf4f92b1e21a4e3f5989ac816eda85ced83bc3be700a3e3f2",
          "sha256": "a790569678fb7314a9c7bb0539e23932c407be7f0b6483b7e72b91b499698c7a",
          "sha1": "1b9947e688cd1f6d344b3c87e1dfd8b04f9ea9bb",
          "md5": "c3be6db0105dec76fc843c1a21caaf1a"
        }
      ]
    }
  ]
}
