{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.plugin",
    "module": "record-api-holder-jar",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.timecat.plugin",
          "module": "record-api",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.tencent.shadow.core",
          "module": "utils",
          "version": {
            "requires": "2.0.5"
          }
        },
        {
          "group": "com.tencent.shadow.core",
          "module": "common",
          "version": {
            "requires": "2.0.5"
          }
        },
        {
          "group": "com.tencent.shadow.dynamic",
          "module": "apk",
          "version": {
            "requires": "2.0.5"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "record-api-holder-1.0.0.aar",
          "url": "record-api-holder-1.0.0.aar",
          "size": 113250,
          "sha512": "501a95cdbae8db0cde40c64d3f88290235c9b97ccd42bf1e89c8b8c091c0d8dd5e5a2c647954f9f8e9a78a2da31a68f68b87c99d258cf9cbc96872df4192454d",
          "sha256": "ee56421bfaaa53abc7886fba2dc29481200ac1dc752bf2e3db8cdc300f5a24f9",
          "sha1": "62026c0ca5b435335cefa89cdddaba0203450c32",
          "md5": "71058a96ac7b18f49982236070936271"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.timecat.plugin",
          "module": "record-api",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.tencent.shadow.core",
          "module": "utils",
          "version": {
            "requires": "2.0.5"
          }
        },
        {
          "group": "com.tencent.shadow.core",
          "module": "common",
          "version": {
            "requires": "2.0.5"
          }
        },
        {
          "group": "com.tencent.shadow.dynamic",
          "module": "apk",
          "version": {
            "requires": "2.0.5"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "record-api-holder-1.0.0.aar",
          "url": "record-api-holder-1.0.0.aar",
          "size": 113250,
          "sha512": "501a95cdbae8db0cde40c64d3f88290235c9b97ccd42bf1e89c8b8c091c0d8dd5e5a2c647954f9f8e9a78a2da31a68f68b87c99d258cf9cbc96872df4192454d",
          "sha256": "ee56421bfaaa53abc7886fba2dc29481200ac1dc752bf2e3db8cdc300f5a24f9",
          "sha1": "62026c0ca5b435335cefa89cdddaba0203450c32",
          "md5": "71058a96ac7b18f49982236070936271"
        }
      ]
    }
  ]
}
