{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.plugin",
    "module": "record-api-holder-jar",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.timecat.plugin",
          "module": "record-api",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.tencent.shadow.core",
          "module": "utils",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "com.tencent.shadow.core",
          "module": "common",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "com.tencent.shadow.dynamic",
          "module": "apk",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "record-api-holder-1.0.0.aar",
          "url": "record-api-holder-1.0.0.aar",
          "size": 102523,
          "sha512": "c716cde0e0c6772d8928e6de1b632f042203873a7b8204cf877c1dc3503a5a5e9dfff76473306fd41e7bb0557d39450f496351d106c1ac3666673a8b81fc6600",
          "sha256": "9cfa1d6ee0d06a7764cc49e6b251f8a16cab9f64120c033d4e80514a7823fec3",
          "sha1": "0e2a9cbb524536702d684080c25636e66e888cf1",
          "md5": "67ec33c61c9d0777bf327c929a07dfc8"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.timecat.plugin",
          "module": "record-api",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.tencent.shadow.core",
          "module": "utils",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "com.tencent.shadow.core",
          "module": "common",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "com.tencent.shadow.dynamic",
          "module": "apk",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "record-api-holder-1.0.0.aar",
          "url": "record-api-holder-1.0.0.aar",
          "size": 102523,
          "sha512": "c716cde0e0c6772d8928e6de1b632f042203873a7b8204cf877c1dc3503a5a5e9dfff76473306fd41e7bb0557d39450f496351d106c1ac3666673a8b81fc6600",
          "sha256": "9cfa1d6ee0d06a7764cc49e6b251f8a16cab9f64120c033d4e80514a7823fec3",
          "sha1": "0e2a9cbb524536702d684080c25636e66e888cf1",
          "md5": "67ec33c61c9d0777bf327c929a07dfc8"
        }
      ]
    }
  ]
}
