{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.plugin",
    "module": "record-api-holder-jar",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.timecat.plugin",
          "module": "record-api",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.tencent.shadow.core",
          "module": "utils",
          "version": {
            "requires": "2.0.5"
          }
        },
        {
          "group": "com.tencent.shadow.core",
          "module": "common",
          "version": {
            "requires": "2.0.5"
          }
        },
        {
          "group": "com.tencent.shadow.dynamic",
          "module": "apk",
          "version": {
            "requires": "2.0.5"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "record-api-holder-1.0.0.aar",
          "url": "record-api-holder-1.0.0.aar",
          "size": 121456,
          "sha512": "8407d5a704d6c0d65713f5790aafe3c36e4fe54b478b81f55b14a2c7637463b91e12171c2b5da834d8e466c512249a58c6b2d93e970c6336db1ad160c8399fff",
          "sha256": "528cf7fe9c7e6b990f52239d49415ddbb39789b05088c09a8d88abbf3ffc717a",
          "sha1": "0005506a923efdc34234a0d42e1c9b61920acac3",
          "md5": "cf9c715901bd2c2cfe78d8602fa1a91a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.timecat.plugin",
          "module": "record-api",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.tencent.shadow.core",
          "module": "utils",
          "version": {
            "requires": "2.0.5"
          }
        },
        {
          "group": "com.tencent.shadow.core",
          "module": "common",
          "version": {
            "requires": "2.0.5"
          }
        },
        {
          "group": "com.tencent.shadow.dynamic",
          "module": "apk",
          "version": {
            "requires": "2.0.5"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "record-api-holder-1.0.0.aar",
          "url": "record-api-holder-1.0.0.aar",
          "size": 121456,
          "sha512": "8407d5a704d6c0d65713f5790aafe3c36e4fe54b478b81f55b14a2c7637463b91e12171c2b5da834d8e466c512249a58c6b2d93e970c6336db1ad160c8399fff",
          "sha256": "528cf7fe9c7e6b990f52239d49415ddbb39789b05088c09a8d88abbf3ffc717a",
          "sha1": "0005506a923efdc34234a0d42e1c9b61920acac3",
          "md5": "cf9c715901bd2c2cfe78d8602fa1a91a"
        }
      ]
    }
  ]
}
