{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.module",
    "module": "module-master-jar",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "block",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "form",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "selector",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "font",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "readonly",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "sdk",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "data",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.data",
          "module": "room",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "MView-same",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "MView-font",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "MLang",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "com.timecat.widget",
          "module": "board",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.widget",
          "module": "table",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.22.1"
          }
        },
        {
          "group": "com.github.chengzhicao",
          "module": "ChannelView",
          "version": {
            "requires": "v1.1.0"
          }
        },
        {
          "group": "com.otaliastudios",
          "module": "autocomplete",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.github.florent37",
          "module": "expansionpanel",
          "version": {
            "requires": "1.0.7"
          }
        },
        {
          "group": "com.akexorcist",
          "module": "round-corner-progress-bar",
          "version": {
            "requires": "2.1.2"
          }
        },
        {
          "group": "com.github.iwgang",
          "module": "countdownview",
          "version": {
            "requires": "2.1.6"
          }
        },
        {
          "group": "io.github.razerdp",
          "module": "BasePopup",
          "version": {
            "requires": "3.1.4"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.mikepenz",
          "module": "materialdrawer",
          "version": {
            "requires": "8.0.3"
          }
        },
        {
          "group": "com.hyman",
          "module": "flowlayout-lib",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "com.github.applikeysolutions",
          "module": "cosmocalendar",
          "version": {
            "requires": "1.0.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "androidx.lifecycle"
            },
            {
              "group": "androidx.lifecycle",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.flyco.roundview",
          "module": "FlycoRoundView_Lib",
          "version": {
            "requires": "1.1.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "FlycoRoundView_Lib",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "com.github.florent37",
          "module": "viewtooltip",
          "version": {
            "requires": "1.1.8"
          }
        },
        {
          "group": "com.getkeepsafe.taptargetview",
          "module": "taptargetview",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.effective.android",
          "module": "panelSwitchHelper-androidx",
          "version": {
            "requires": "1.3.13"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "module-master-jar-1.1.0.aar",
          "url": "module-master-jar-1.1.0.aar",
          "size": 4118039,
          "sha512": "2e82387f56ef51edda4497304e242bfe0266ff10890f8b3a63226928c59b34150eb2281f9c704bec2f77f454e3b2c3d09cb89121d7daa85d73900d3267b2e074",
          "sha256": "6d2e160030be6c250a5834cb8842df2f162f1b7caebaff48ee49617efe369fa2",
          "sha1": "d3cca265a565dade42062961ba8ef5548715a681",
          "md5": "a6c961b2c50ad46e09c99de03e28d9db"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "block",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "form",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "selector",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "font",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "readonly",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "sdk",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "data",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.data",
          "module": "room",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "MView-same",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "MView-font",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "MLang",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "com.timecat.widget",
          "module": "board",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.widget",
          "module": "table",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.22.1"
          }
        },
        {
          "group": "com.github.chengzhicao",
          "module": "ChannelView",
          "version": {
            "requires": "v1.1.0"
          }
        },
        {
          "group": "com.otaliastudios",
          "module": "autocomplete",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.github.florent37",
          "module": "expansionpanel",
          "version": {
            "requires": "1.0.7"
          }
        },
        {
          "group": "com.akexorcist",
          "module": "round-corner-progress-bar",
          "version": {
            "requires": "2.1.2"
          }
        },
        {
          "group": "com.github.iwgang",
          "module": "countdownview",
          "version": {
            "requires": "2.1.6"
          }
        },
        {
          "group": "io.github.razerdp",
          "module": "BasePopup",
          "version": {
            "requires": "3.1.4"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.mikepenz",
          "module": "materialdrawer",
          "version": {
            "requires": "8.0.3"
          }
        },
        {
          "group": "com.hyman",
          "module": "flowlayout-lib",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "com.github.applikeysolutions",
          "module": "cosmocalendar",
          "version": {
            "requires": "1.0.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "androidx.lifecycle"
            },
            {
              "group": "androidx.lifecycle",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.flyco.roundview",
          "module": "FlycoRoundView_Lib",
          "version": {
            "requires": "1.1.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "FlycoRoundView_Lib",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "com.github.florent37",
          "module": "viewtooltip",
          "version": {
            "requires": "1.1.8"
          }
        },
        {
          "group": "com.getkeepsafe.taptargetview",
          "module": "taptargetview",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.effective.android",
          "module": "panelSwitchHelper-androidx",
          "version": {
            "requires": "1.3.13"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "module-master-jar-1.1.0.aar",
          "url": "module-master-jar-1.1.0.aar",
          "size": 4118039,
          "sha512": "2e82387f56ef51edda4497304e242bfe0266ff10890f8b3a63226928c59b34150eb2281f9c704bec2f77f454e3b2c3d09cb89121d7daa85d73900d3267b2e074",
          "sha256": "6d2e160030be6c250a5834cb8842df2f162f1b7caebaff48ee49617efe369fa2",
          "sha1": "d3cca265a565dade42062961ba8ef5548715a681",
          "md5": "a6c961b2c50ad46e09c99de03e28d9db"
        }
      ]
    }
  ]
}
