{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.component",
    "module": "router-jar",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.timecat.extend",
          "module": "arms",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.github.xiaojinzi123.Component",
          "module": "component-impl",
          "version": {
            "requires": "v1.9.2-androidx-java8"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "router-jar-1.1.0.aar",
          "url": "router-jar-1.1.0.aar",
          "size": 34309,
          "sha512": "21ae31ec351b6dabe085e91acc94936f400393699586895e751a389aff2e548e66244097df6d4aa73df79d73e04ce4e98c29dc55f34d91de7863fec6fd5a56ae",
          "sha256": "d92fcbc5c21b1bcdcbde450ca8c8b57e434b8ba61ec77c15fcc4d9ae1e383704",
          "sha1": "85c2171916557c59d41bde3236524db9e09e24b4",
          "md5": "6271fae9c7f6704b4b005a5bf976ebdb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.timecat.extend",
          "module": "arms",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.github.xiaojinzi123.Component",
          "module": "component-impl",
          "version": {
            "requires": "v1.9.2-androidx-java8"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "router-jar-1.1.0.aar",
          "url": "router-jar-1.1.0.aar",
          "size": 34309,
          "sha512": "21ae31ec351b6dabe085e91acc94936f400393699586895e751a389aff2e548e66244097df6d4aa73df79d73e04ce4e98c29dc55f34d91de7863fec6fd5a56ae",
          "sha256": "d92fcbc5c21b1bcdcbde450ca8c8b57e434b8ba61ec77c15fcc4d9ae1e383704",
          "sha1": "85c2171916557c59d41bde3236524db9e09e24b4",
          "md5": "6271fae9c7f6704b4b005a5bf976ebdb"
        }
      ]
    }
  ]
}
