{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.identity",
    "module": "readonly-jar",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "readonly-jar-1.1.0.aar",
          "url": "readonly-jar-1.1.0.aar",
          "size": 27121,
          "sha512": "644a34b66391f41a2c74dfc70711f4a902b081aa5bf0d84c94d00b380275059ce54d0d0e474027a7feed293a40635e93e28f1062fefff6e5a721aeecaeec32af",
          "sha256": "e3f5ad56ebfd05136bc6ce9f6184e807dbb4ad244301b5d9fde666695a0c4fe8",
          "sha1": "1614e537bee51a0008f338a1b4b4d21dc78f1a29",
          "md5": "983de1c61ac122e7769e99f13115e598"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "readonly-jar-1.1.0.aar",
          "url": "readonly-jar-1.1.0.aar",
          "size": 27121,
          "sha512": "644a34b66391f41a2c74dfc70711f4a902b081aa5bf0d84c94d00b380275059ce54d0d0e474027a7feed293a40635e93e28f1062fefff6e5a721aeecaeec32af",
          "sha256": "e3f5ad56ebfd05136bc6ce9f6184e807dbb4ad244301b5d9fde666695a0c4fe8",
          "sha1": "1614e537bee51a0008f338a1b4b4d21dc78f1a29",
          "md5": "983de1c61ac122e7769e99f13115e598"
        }
      ]
    }
  ]
}
