{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.identity",
    "module": "readonly-jar",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "readonly-jar-1.1.0.aar",
          "url": "readonly-jar-1.1.0.aar",
          "size": 27217,
          "sha512": "96af3844377ed3835d9d7c6f94f44e608d003a1674a2290eed106a447b1dcae3f3e9b878f41c06a7c62e4a2e20c353f8d5cf91ae5edbdb4609d55e754a447f26",
          "sha256": "03dc0727c11e6695012344693022fbf3998942dd713868ff6e806af57a5c78ed",
          "sha1": "1003eb930946c6a2054152fd060839c2db1b3025",
          "md5": "819bb9fb4ddaf508b38f947be60b1913"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "readonly-jar-1.1.0.aar",
          "url": "readonly-jar-1.1.0.aar",
          "size": 27217,
          "sha512": "96af3844377ed3835d9d7c6f94f44e608d003a1674a2290eed106a447b1dcae3f3e9b878f41c06a7c62e4a2e20c353f8d5cf91ae5edbdb4609d55e754a447f26",
          "sha256": "03dc0727c11e6695012344693022fbf3998942dd713868ff6e806af57a5c78ed",
          "sha1": "1003eb930946c6a2054152fd060839c2db1b3025",
          "md5": "819bb9fb4ddaf508b38f947be60b1913"
        }
      ]
    }
  ]
}
