{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.identity",
    "module": "readonly-jar",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "readonly-jar-1.1.0.aar",
          "url": "readonly-jar-1.1.0.aar",
          "size": 24875,
          "sha512": "f9e47b1063977f6e40f59419469d8591614a5d871cd0f40f5988a37bad885cc2d34bc2137a2a16ca70cdde966ec0231a25625ce1b5eed29425dcae3bad24093f",
          "sha256": "252276c76aad7e8aeb3a276b60cde6a21ac2d97d3d435a17c363dab779ca549e",
          "sha1": "fe3583f35af83333dfd33da6ce3c25dd10b5ba33",
          "md5": "5c5341bc7026ea377cf8ab9349341f82"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "readonly-jar-1.1.0.aar",
          "url": "readonly-jar-1.1.0.aar",
          "size": 24875,
          "sha512": "f9e47b1063977f6e40f59419469d8591614a5d871cd0f40f5988a37bad885cc2d34bc2137a2a16ca70cdde966ec0231a25625ce1b5eed29425dcae3bad24093f",
          "sha256": "252276c76aad7e8aeb3a276b60cde6a21ac2d97d3d435a17c363dab779ca549e",
          "sha1": "fe3583f35af83333dfd33da6ce3c25dd10b5ba33",
          "md5": "5c5341bc7026ea377cf8ab9349341f82"
        }
      ]
    }
  ]
}
