{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.page",
    "module": "ui-jar",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.timecat.page",
          "module": "scene",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.page",
          "module": "navigation",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ui-1.0.1.aar",
          "url": "ui-1.0.1.aar",
          "size": 94049,
          "sha512": "c5024cf910adb738dbf13f73d96ac1a8eda6f120969963bac15e33db63b0a4bb1af31f21d0a8a48593cc9a3699fa80ffcab35b1dabace3e4a5333cdbd9b437f2",
          "sha256": "3192d429926348d36b418c37ab87e8673e6d08e90b2a611741e5dc2a662835ba",
          "sha1": "b06f0c64e62d5f28b4646acd293f2ffb02743f76",
          "md5": "84f3d5e2bdc9c05081fbd77723df3d48"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.timecat.page",
          "module": "scene",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.page",
          "module": "navigation",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ui-1.0.1.aar",
          "url": "ui-1.0.1.aar",
          "size": 94049,
          "sha512": "c5024cf910adb738dbf13f73d96ac1a8eda6f120969963bac15e33db63b0a4bb1af31f21d0a8a48593cc9a3699fa80ffcab35b1dabace3e4a5333cdbd9b437f2",
          "sha256": "3192d429926348d36b418c37ab87e8673e6d08e90b2a611741e5dc2a662835ba",
          "sha1": "b06f0c64e62d5f28b4646acd293f2ffb02743f76",
          "md5": "84f3d5e2bdc9c05081fbd77723df3d48"
        }
      ]
    }
  ]
}
