{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.page",
    "module": "base-jar",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "identity",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "setting",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.element",
          "module": "listview",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.element",
          "module": "alert",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.github.gturedi",
          "module": "stateful-layout",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.billy.android",
          "module": "smart-swipe",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "com.billy.android",
          "module": "smart-swipe-x",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.22.1"
          }
        },
        {
          "group": "joda-time",
          "module": "joda-time",
          "version": {
            "requires": "2.10.10"
          }
        },
        {
          "group": "com.trello.rxlifecycle2",
          "module": "rxlifecycle",
          "version": {
            "requires": "2.2.2"
          }
        },
        {
          "group": "com.trello.rxlifecycle2",
          "module": "rxlifecycle-components",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "com.trello.rxlifecycle2",
          "module": "rxlifecycle-navi",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "com.trello.rxlifecycle2",
          "module": "rxlifecycle-kotlin",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "io.reactivex",
          "module": "rxandroid",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "io.reactivex",
          "module": "rxjava",
          "version": {
            "requires": "1.3.8"
          }
        },
        {
          "group": "me.yokeyword",
          "module": "fragmentationx-core",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "me.yokeyword",
          "module": "eventbus-activity-scope",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "base-1.0.1.aar",
          "url": "base-1.0.1.aar",
          "size": 221372,
          "sha512": "2ced0324f7d8e7f4ffd7d881acc3cc67631e31b1cdd58827f6452487f54ca758a5b905ae975a8d19e8413d7469a79078a2efd19d4fb2edaf5c40bc089018b355",
          "sha256": "020cdce0ca9b52122ec90c7560c7cc6603883264d8eaacb1d04ac4c8f1abb8b3",
          "sha1": "e27f5bc1de04fba8c6db55bdf2ae90de31f7047c",
          "md5": "1d52cc779d9cac4b6616599b354a3cac"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "identity",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "setting",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.element",
          "module": "listview",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.element",
          "module": "alert",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.github.gturedi",
          "module": "stateful-layout",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.billy.android",
          "module": "smart-swipe",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "com.billy.android",
          "module": "smart-swipe-x",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.22.1"
          }
        },
        {
          "group": "joda-time",
          "module": "joda-time",
          "version": {
            "requires": "2.10.10"
          }
        },
        {
          "group": "com.trello.rxlifecycle2",
          "module": "rxlifecycle",
          "version": {
            "requires": "2.2.2"
          }
        },
        {
          "group": "com.trello.rxlifecycle2",
          "module": "rxlifecycle-components",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "com.trello.rxlifecycle2",
          "module": "rxlifecycle-navi",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "com.trello.rxlifecycle2",
          "module": "rxlifecycle-kotlin",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "io.reactivex",
          "module": "rxandroid",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "io.reactivex",
          "module": "rxjava",
          "version": {
            "requires": "1.3.8"
          }
        },
        {
          "group": "me.yokeyword",
          "module": "fragmentationx-core",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "me.yokeyword",
          "module": "eventbus-activity-scope",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "base-1.0.1.aar",
          "url": "base-1.0.1.aar",
          "size": 221372,
          "sha512": "2ced0324f7d8e7f4ffd7d881acc3cc67631e31b1cdd58827f6452487f54ca758a5b905ae975a8d19e8413d7469a79078a2efd19d4fb2edaf5c40bc089018b355",
          "sha256": "020cdce0ca9b52122ec90c7560c7cc6603883264d8eaacb1d04ac4c8f1abb8b3",
          "sha1": "e27f5bc1de04fba8c6db55bdf2ae90de31f7047c",
          "md5": "1d52cc779d9cac4b6616599b354a3cac"
        }
      ]
    }
  ]
}
