{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.page",
    "module": "base-jar",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.timecat.component",
          "module": "identity",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "setting",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.element",
          "module": "listview",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.element",
          "module": "alert",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.github.gturedi",
          "module": "stateful-layout",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.billy.android",
          "module": "smart-swipe",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "com.billy.android",
          "module": "smart-swipe-x",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.22.1"
          }
        },
        {
          "group": "joda-time",
          "module": "joda-time",
          "version": {
            "requires": "2.10.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "com.trello.rxlifecycle2",
          "module": "rxlifecycle",
          "version": {
            "requires": "2.2.2"
          }
        },
        {
          "group": "com.trello.rxlifecycle2",
          "module": "rxlifecycle-components",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "com.trello.rxlifecycle2",
          "module": "rxlifecycle-navi",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "com.trello.rxlifecycle2",
          "module": "rxlifecycle-kotlin",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "io.reactivex",
          "module": "rxandroid",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "io.reactivex",
          "module": "rxjava",
          "version": {
            "requires": "1.3.8"
          }
        },
        {
          "group": "me.yokeyword",
          "module": "fragmentationx-core",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "me.yokeyword",
          "module": "eventbus-activity-scope",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-extensions",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "base-1.0.1.aar",
          "url": "base-1.0.1.aar",
          "size": 212767,
          "sha512": "ae70b4155860a6bfb688d83cb5734b1b2d903961da89ed73125c1636ac3c5570b4f7739df44288b128952c235c19529d68e4a5369daaf9e493a928268ba643ca",
          "sha256": "7c851c294ab0116c265777f01a9a8a76f9444761d9bcb60a90240ad99a0be2e1",
          "sha1": "11325e64cbe33a9c125f3e97fba8ebceba18a769",
          "md5": "3e6807d1d7113d21693b61b06530151f"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.timecat.component",
          "module": "identity",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "setting",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.element",
          "module": "listview",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.element",
          "module": "alert",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.github.gturedi",
          "module": "stateful-layout",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.billy.android",
          "module": "smart-swipe",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "com.billy.android",
          "module": "smart-swipe-x",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.22.1"
          }
        },
        {
          "group": "joda-time",
          "module": "joda-time",
          "version": {
            "requires": "2.10.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "com.trello.rxlifecycle2",
          "module": "rxlifecycle",
          "version": {
            "requires": "2.2.2"
          }
        },
        {
          "group": "com.trello.rxlifecycle2",
          "module": "rxlifecycle-components",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "com.trello.rxlifecycle2",
          "module": "rxlifecycle-navi",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "com.trello.rxlifecycle2",
          "module": "rxlifecycle-kotlin",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "io.reactivex",
          "module": "rxandroid",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "io.reactivex",
          "module": "rxjava",
          "version": {
            "requires": "1.3.8"
          }
        },
        {
          "group": "me.yokeyword",
          "module": "fragmentationx-core",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "me.yokeyword",
          "module": "eventbus-activity-scope",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-extensions",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "base-1.0.1.aar",
          "url": "base-1.0.1.aar",
          "size": 212767,
          "sha512": "ae70b4155860a6bfb688d83cb5734b1b2d903961da89ed73125c1636ac3c5570b4f7739df44288b128952c235c19529d68e4a5369daaf9e493a928268ba643ca",
          "sha256": "7c851c294ab0116c265777f01a9a8a76f9444761d9bcb60a90240ad99a0be2e1",
          "sha1": "11325e64cbe33a9c125f3e97fba8ebceba18a769",
          "md5": "3e6807d1d7113d21693b61b06530151f"
        }
      ]
    }
  ]
}
