{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.page",
    "module": "base-jar",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.timecat.component",
          "module": "identity",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "setting",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.element",
          "module": "listview",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.element",
          "module": "alert",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.github.gturedi",
          "module": "stateful-layout",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.billy.android",
          "module": "smart-swipe",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "com.billy.android",
          "module": "smart-swipe-x",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.22.1"
          }
        },
        {
          "group": "joda-time",
          "module": "joda-time",
          "version": {
            "requires": "2.10.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "com.trello.rxlifecycle2",
          "module": "rxlifecycle",
          "version": {
            "requires": "2.2.2"
          }
        },
        {
          "group": "com.trello.rxlifecycle2",
          "module": "rxlifecycle-components",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "com.trello.rxlifecycle2",
          "module": "rxlifecycle-navi",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "com.trello.rxlifecycle2",
          "module": "rxlifecycle-kotlin",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "io.reactivex",
          "module": "rxandroid",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "io.reactivex",
          "module": "rxjava",
          "version": {
            "requires": "1.3.8"
          }
        },
        {
          "group": "me.yokeyword",
          "module": "fragmentationx-core",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "me.yokeyword",
          "module": "eventbus-activity-scope",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-extensions",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "base-1.0.1.aar",
          "url": "base-1.0.1.aar",
          "size": 212517,
          "sha512": "c203ca9408de105cd24ac4c38c84876bbecc0009b1ba6488f75bf389dca82d1b697da0ebf6b56d69bedc88f486860b3fb3456bd51a1d395e0d41a64b42306692",
          "sha256": "ade356b7442f639c94edca5b256373404d0d461e7ec8cb1128f855e43cbba20e",
          "sha1": "0e7d7c931a963ed1ba787a35429b536552dae33c",
          "md5": "ad3e8277827996e5f5738646a13be81a"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.timecat.component",
          "module": "identity",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "setting",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.element",
          "module": "listview",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.element",
          "module": "alert",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.github.gturedi",
          "module": "stateful-layout",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.billy.android",
          "module": "smart-swipe",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "com.billy.android",
          "module": "smart-swipe-x",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android-support",
          "version": {
            "requires": "2.22.1"
          }
        },
        {
          "group": "joda-time",
          "module": "joda-time",
          "version": {
            "requires": "2.10.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "com.trello.rxlifecycle2",
          "module": "rxlifecycle",
          "version": {
            "requires": "2.2.2"
          }
        },
        {
          "group": "com.trello.rxlifecycle2",
          "module": "rxlifecycle-components",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "com.trello.rxlifecycle2",
          "module": "rxlifecycle-navi",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "com.trello.rxlifecycle2",
          "module": "rxlifecycle-kotlin",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "io.reactivex",
          "module": "rxandroid",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "io.reactivex",
          "module": "rxjava",
          "version": {
            "requires": "1.3.8"
          }
        },
        {
          "group": "me.yokeyword",
          "module": "fragmentationx-core",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "me.yokeyword",
          "module": "eventbus-activity-scope",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-extensions",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "base-1.0.1.aar",
          "url": "base-1.0.1.aar",
          "size": 212517,
          "sha512": "c203ca9408de105cd24ac4c38c84876bbecc0009b1ba6488f75bf389dca82d1b697da0ebf6b56d69bedc88f486860b3fb3456bd51a1d395e0d41a64b42306692",
          "sha256": "ade356b7442f639c94edca5b256373404d0d461e7ec8cb1128f855e43cbba20e",
          "sha1": "0e7d7c931a963ed1ba787a35429b536552dae33c",
          "md5": "ad3e8277827996e5f5738646a13be81a"
        }
      ]
    }
  ]
}
