{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.module",
    "module": "module-controller-jar",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "block",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "form",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "selector",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "setting",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "SelfBaidu",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.show",
          "module": "window",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "MView-same",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.youth.banner",
          "module": "banner",
          "version": {
            "requires": "2.0.11"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "module-controller-jar-1.1.0.aar",
          "url": "module-controller-jar-1.1.0.aar",
          "size": 2069758,
          "sha512": "afb5c21fe269127d26d4c9b66a62cad6f0a7aefa1aee883f969737f33dc9c442c57bd303aecb9a95447619c62588335df2d27c997aae51d8c3d536aad112d90d",
          "sha256": "7a4407d6f09a287cc2b60465c296e2d6a387c0b66696ebc8700df56433796342",
          "sha1": "ff73f8b47d85de55f0b0264492bc363d9ef90f2d",
          "md5": "d705630a53b40f5874692ae3c9236475"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "block",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "form",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "selector",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "setting",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "SelfBaidu",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.show",
          "module": "window",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "MView-same",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.youth.banner",
          "module": "banner",
          "version": {
            "requires": "2.0.11"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.palette",
          "module": "palette",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.github.florent37",
          "module": "expansionpanel",
          "version": {
            "requires": "1.0.7"
          }
        },
        {
          "group": "com.larswerkman",
          "module": "HoloColorPicker",
          "version": {
            "requires": "1.5"
          }
        },
        {
          "group": "org.greenrobot",
          "module": "greendao",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "com.github.yuweiguocn",
          "module": "GreenDaoUpgradeHelper",
          "version": {
            "requires": "v2.1.0"
          }
        },
        {
          "group": "com.github.czy1121",
          "module": "settingscompat",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.ramotion.foldingcell",
          "module": "folding-cell",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "br.com.simplepass",
          "module": "loading-button-android",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "devlight.io",
          "module": "navigationtabbar",
          "version": {
            "requires": "1.2.5"
          }
        },
        {
          "group": "com.github.devlight",
          "module": "infinitecycleviewpager",
          "version": {
            "requires": "1.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "module-controller-jar-1.1.0.aar",
          "url": "module-controller-jar-1.1.0.aar",
          "size": 2069758,
          "sha512": "afb5c21fe269127d26d4c9b66a62cad6f0a7aefa1aee883f969737f33dc9c442c57bd303aecb9a95447619c62588335df2d27c997aae51d8c3d536aad112d90d",
          "sha256": "7a4407d6f09a287cc2b60465c296e2d6a387c0b66696ebc8700df56433796342",
          "sha1": "ff73f8b47d85de55f0b0264492bc363d9ef90f2d",
          "md5": "d705630a53b40f5874692ae3c9236475"
        }
      ]
    }
  ]
}
