{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.extend",
    "module": "arms-jar",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.4"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "rxjava"
            }
          ]
        },
        {
          "group": "com.github.VictorAlbertos.RxCache",
          "module": "runtime",
          "version": {
            "requires": "1.8.3-2.x"
          },
          "excludes": [
            {
              "group": "*",
              "module": "dagger"
            },
            {
              "group": "*",
              "module": "api"
            },
            {
              "group": "*",
              "module": "rxjava"
            }
          ]
        },
        {
          "group": "com.trello.rxlifecycle2",
          "module": "rxlifecycle",
          "version": {
            "requires": "2.2.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "jsr305"
            },
            {
              "group": "*",
              "module": "rxjava"
            }
          ]
        },
        {
          "group": "com.trello.rxlifecycle2",
          "module": "rxlifecycle-android",
          "version": {
            "requires": "2.2.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "annotation"
            },
            {
              "group": "*",
              "module": "rxandroid"
            },
            {
              "group": "*",
              "module": "rxlifecycle"
            },
            {
              "group": "*",
              "module": "rxjava"
            }
          ]
        },
        {
          "group": "me.jessyan",
          "module": "rxerrorhandler",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "com.tbruyelle.rxpermissions2",
          "module": "rxpermissions",
          "version": {
            "requires": "0.9.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "rxpermissions",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "okio"
            },
            {
              "group": "*",
              "module": "okhttp"
            }
          ]
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.5.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.22.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "4.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "arms-jar-1.1.0.aar",
          "url": "arms-jar-1.1.0.aar",
          "size": 127460,
          "sha512": "95bc2ca131b45ba5b1a2ef0af29401c22618cc2619aa0472a95884d1f4631669c0a54ff5f03e389cae3f50f12d2a801843d2c3a1eea295c66243ee1dcd25a07a",
          "sha256": "ac8a5866318c8ab5ae6431d1aa513b8ffb3b078c4db8360f5e907c4a4e14ab2c",
          "sha1": "b1d33dcdd8dbfede70ee5c1e82f46dab95c203e9",
          "md5": "9773a59e1841a0d4d2625449af075b96"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.VictorAlbertos.Jolyglot",
          "module": "gson",
          "version": {
            "requires": "0.0.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "gson"
            }
          ]
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "retrofit"
            },
            {
              "group": "*",
              "module": "okio"
            },
            {
              "group": "*",
              "module": "okhttp"
            },
            {
              "group": "*",
              "module": "gson"
            }
          ]
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.9.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "retrofit"
            },
            {
              "group": "*",
              "module": "okio"
            },
            {
              "group": "*",
              "module": "okhttp"
            },
            {
              "group": "*",
              "module": "rxjava"
            }
          ]
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.4"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "rxjava"
            }
          ]
        },
        {
          "group": "com.github.VictorAlbertos.RxCache",
          "module": "runtime",
          "version": {
            "requires": "1.8.3-2.x"
          },
          "excludes": [
            {
              "group": "*",
              "module": "dagger"
            },
            {
              "group": "*",
              "module": "api"
            },
            {
              "group": "*",
              "module": "rxjava"
            }
          ]
        },
        {
          "group": "com.trello.rxlifecycle2",
          "module": "rxlifecycle",
          "version": {
            "requires": "2.2.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "jsr305"
            },
            {
              "group": "*",
              "module": "rxjava"
            }
          ]
        },
        {
          "group": "com.trello.rxlifecycle2",
          "module": "rxlifecycle-android",
          "version": {
            "requires": "2.2.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "annotation"
            },
            {
              "group": "*",
              "module": "rxandroid"
            },
            {
              "group": "*",
              "module": "rxlifecycle"
            },
            {
              "group": "*",
              "module": "rxjava"
            }
          ]
        },
        {
          "group": "me.jessyan",
          "module": "rxerrorhandler",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "com.tbruyelle.rxpermissions2",
          "module": "rxpermissions",
          "version": {
            "requires": "0.9.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "rxpermissions",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "okio"
            },
            {
              "group": "*",
              "module": "okhttp"
            }
          ]
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.5.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.22.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "4.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "arms-jar-1.1.0.aar",
          "url": "arms-jar-1.1.0.aar",
          "size": 127460,
          "sha512": "95bc2ca131b45ba5b1a2ef0af29401c22618cc2619aa0472a95884d1f4631669c0a54ff5f03e389cae3f50f12d2a801843d2c3a1eea295c66243ee1dcd25a07a",
          "sha256": "ac8a5866318c8ab5ae6431d1aa513b8ffb3b078c4db8360f5e907c4a4e14ab2c",
          "sha1": "b1d33dcdd8dbfede70ee5c1e82f46dab95c203e9",
          "md5": "9773a59e1841a0d4d2625449af075b96"
        }
      ]
    }
  ]
}
