{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.extend",
    "module": "arms-jar",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.4"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "rxjava"
            }
          ]
        },
        {
          "group": "com.github.VictorAlbertos.RxCache",
          "module": "runtime",
          "version": {
            "requires": "1.8.3-2.x"
          },
          "excludes": [
            {
              "group": "*",
              "module": "dagger"
            },
            {
              "group": "*",
              "module": "api"
            },
            {
              "group": "*",
              "module": "rxjava"
            }
          ]
        },
        {
          "group": "com.trello.rxlifecycle2",
          "module": "rxlifecycle",
          "version": {
            "requires": "2.2.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "jsr305"
            },
            {
              "group": "*",
              "module": "rxjava"
            }
          ]
        },
        {
          "group": "com.trello.rxlifecycle2",
          "module": "rxlifecycle-android",
          "version": {
            "requires": "2.2.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "annotation"
            },
            {
              "group": "*",
              "module": "rxandroid"
            },
            {
              "group": "*",
              "module": "rxlifecycle"
            },
            {
              "group": "*",
              "module": "rxjava"
            }
          ]
        },
        {
          "group": "me.jessyan",
          "module": "rxerrorhandler",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "okio"
            },
            {
              "group": "*",
              "module": "okhttp"
            }
          ]
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.5.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.22.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "4.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "arms-jar-1.1.0.aar",
          "url": "arms-jar-1.1.0.aar",
          "size": 127487,
          "sha512": "3c7ac075488384a95aa5d1319848ceb80df46048f325d84eef91319498ed6655b13a49ffe537df84627ca0c3811699befa626a7f0543b59013000d4c34e4d963",
          "sha256": "595044e500cddefc0281786ecd250b81fa0cd40663168a700eef9f97614840e7",
          "sha1": "de9bcf7138466b28976fca261be0cdd6ac0b7dcc",
          "md5": "e6432db9d251e6e443ffc2a7a72c1aae"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.VictorAlbertos.Jolyglot",
          "module": "gson",
          "version": {
            "requires": "0.0.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "gson"
            }
          ]
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "retrofit"
            },
            {
              "group": "*",
              "module": "okio"
            },
            {
              "group": "*",
              "module": "okhttp"
            },
            {
              "group": "*",
              "module": "gson"
            }
          ]
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.9.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "retrofit"
            },
            {
              "group": "*",
              "module": "okio"
            },
            {
              "group": "*",
              "module": "okhttp"
            },
            {
              "group": "*",
              "module": "rxjava"
            }
          ]
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.4"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "rxjava"
            }
          ]
        },
        {
          "group": "com.github.VictorAlbertos.RxCache",
          "module": "runtime",
          "version": {
            "requires": "1.8.3-2.x"
          },
          "excludes": [
            {
              "group": "*",
              "module": "dagger"
            },
            {
              "group": "*",
              "module": "api"
            },
            {
              "group": "*",
              "module": "rxjava"
            }
          ]
        },
        {
          "group": "com.trello.rxlifecycle2",
          "module": "rxlifecycle",
          "version": {
            "requires": "2.2.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "jsr305"
            },
            {
              "group": "*",
              "module": "rxjava"
            }
          ]
        },
        {
          "group": "com.trello.rxlifecycle2",
          "module": "rxlifecycle-android",
          "version": {
            "requires": "2.2.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "annotation"
            },
            {
              "group": "*",
              "module": "rxandroid"
            },
            {
              "group": "*",
              "module": "rxlifecycle"
            },
            {
              "group": "*",
              "module": "rxjava"
            }
          ]
        },
        {
          "group": "me.jessyan",
          "module": "rxerrorhandler",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "okio"
            },
            {
              "group": "*",
              "module": "okhttp"
            }
          ]
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.5.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.22.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "4.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "arms-jar-1.1.0.aar",
          "url": "arms-jar-1.1.0.aar",
          "size": 127487,
          "sha512": "3c7ac075488384a95aa5d1319848ceb80df46048f325d84eef91319498ed6655b13a49ffe537df84627ca0c3811699befa626a7f0543b59013000d4c34e4d963",
          "sha256": "595044e500cddefc0281786ecd250b81fa0cd40663168a700eef9f97614840e7",
          "sha1": "de9bcf7138466b28976fca261be0cdd6ac0b7dcc",
          "md5": "e6432db9d251e6e443ffc2a7a72c1aae"
        }
      ]
    }
  ]
}
