{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.module",
    "module": "module-controller-jar",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "androidx.media",
          "module": "media",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.palette",
          "module": "palette",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.yanzhenjie",
          "module": "recyclerview-swipe",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "block",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "form",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "setting",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "SelfBaidu",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.show",
          "module": "window",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "MView-same",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "module-controller-1.1.0.aar",
          "url": "module-controller-1.1.0.aar",
          "size": 1938266,
          "sha512": "50f5817e43ba50b1231c6f04e27d025b94bf9067add1ef091327c2a367818b54042effbebf34857cc41e38e96af2d3b0dcb4a34acdad02c11382ba9766523bd4",
          "sha256": "923a103f15d4452315629150dee1b6a89887aff8943905d9abda486473b420c5",
          "sha1": "87d5ecf55a89bc8e93df924f955a9e11435d4fb3",
          "md5": "eedd9f0e37ef4ef99f6014122218248e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "androidx.media",
          "module": "media",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.palette",
          "module": "palette",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.yanzhenjie",
          "module": "recyclerview-swipe",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "block",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "form",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "setting",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "SelfBaidu",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.show",
          "module": "window",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "MView-same",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "com.larswerkman",
          "module": "HoloColorPicker",
          "version": {
            "requires": "1.5"
          }
        },
        {
          "group": "org.greenrobot",
          "module": "greendao",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "com.github.yuweiguocn",
          "module": "GreenDaoUpgradeHelper",
          "version": {
            "requires": "v2.1.0"
          }
        },
        {
          "group": "com.github.czy1121",
          "module": "settingscompat",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.ramotion.foldingcell",
          "module": "folding-cell",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "br.com.simplepass",
          "module": "loading-button-android",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "devlight.io",
          "module": "navigationtabbar",
          "version": {
            "requires": "1.2.5"
          }
        },
        {
          "group": "com.github.devlight",
          "module": "infinitecycleviewpager",
          "version": {
            "requires": "1.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "module-controller-1.1.0.aar",
          "url": "module-controller-1.1.0.aar",
          "size": 1938266,
          "sha512": "50f5817e43ba50b1231c6f04e27d025b94bf9067add1ef091327c2a367818b54042effbebf34857cc41e38e96af2d3b0dcb4a34acdad02c11382ba9766523bd4",
          "sha256": "923a103f15d4452315629150dee1b6a89887aff8943905d9abda486473b420c5",
          "sha1": "87d5ecf55a89bc8e93df924f955a9e11435d4fb3",
          "md5": "eedd9f0e37ef4ef99f6014122218248e"
        }
      ]
    }
  ]
}
