{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.module",
    "module": "module-controller-jar",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "androidx.media",
          "module": "media",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.palette",
          "module": "palette",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.yanzhenjie",
          "module": "recyclerview-swipe",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "block",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "form",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "selector",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "setting",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "SelfBaidu",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.show",
          "module": "window",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "MView-same",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "module-controller-1.1.0.aar",
          "url": "module-controller-1.1.0.aar",
          "size": 1956359,
          "sha512": "5f079a3271a12be256e30535bd384245d9b9bd95e5f0954b8ac726c255e72f95e5d2a9d93452232deab2cb246eb7d918dfc15b5b2b99a31fcb747f7d8cf7f4c8",
          "sha256": "cb2140755fad1000b832d2257e2c7a34e622f2ccc392657929d8d6839e2a9f36",
          "sha1": "f95f32e0e047f154ffe94407103e4da2d2d65e5c",
          "md5": "43432234df015ae17886b228b1557f46"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "androidx.media",
          "module": "media",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.palette",
          "module": "palette",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.yanzhenjie",
          "module": "recyclerview-swipe",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "block",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "form",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "selector",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "setting",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "SelfBaidu",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.show",
          "module": "window",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "MView-same",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "com.larswerkman",
          "module": "HoloColorPicker",
          "version": {
            "requires": "1.5"
          }
        },
        {
          "group": "org.greenrobot",
          "module": "greendao",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "com.github.yuweiguocn",
          "module": "GreenDaoUpgradeHelper",
          "version": {
            "requires": "v2.1.0"
          }
        },
        {
          "group": "com.github.czy1121",
          "module": "settingscompat",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.ramotion.foldingcell",
          "module": "folding-cell",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "br.com.simplepass",
          "module": "loading-button-android",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "devlight.io",
          "module": "navigationtabbar",
          "version": {
            "requires": "1.2.5"
          }
        },
        {
          "group": "com.github.devlight",
          "module": "infinitecycleviewpager",
          "version": {
            "requires": "1.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "module-controller-1.1.0.aar",
          "url": "module-controller-1.1.0.aar",
          "size": 1956359,
          "sha512": "5f079a3271a12be256e30535bd384245d9b9bd95e5f0954b8ac726c255e72f95e5d2a9d93452232deab2cb246eb7d918dfc15b5b2b99a31fcb747f7d8cf7f4c8",
          "sha256": "cb2140755fad1000b832d2257e2c7a34e622f2ccc392657929d8d6839e2a9f36",
          "sha1": "f95f32e0e047f154ffe94407103e4da2d2d65e5c",
          "md5": "43432234df015ae17886b228b1557f46"
        }
      ]
    }
  ]
}
