{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.module",
    "module": "module-controller-jar",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "androidx.media",
          "module": "media",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.palette",
          "module": "palette",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "com.yanzhenjie",
          "module": "recyclerview-swipe",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "block",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "form",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "setting",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.extend",
          "module": "baidu",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.show",
          "module": "window",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "MView-same",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "module-controller-1.1.0.aar",
          "url": "module-controller-1.1.0.aar",
          "size": 1920726,
          "sha512": "8fb5bfa11e44557a84a5eec988d74118ebaa57ad63342770427f605322798a44008c7a0f7c6a16552dbb7002bf121b528387623d7755fdb56f0c08ad5ebc3972",
          "sha256": "a225b5096090de46287d9a5be9d45f5a73af807dc14ecd16e219ae2eadb13027",
          "sha1": "8c7d29e079c595875937600d44b72c116a06a101",
          "md5": "4a25aac4b8b33ed2395ad7bdfd5c862b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "androidx.media",
          "module": "media",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.palette",
          "module": "palette",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "com.yanzhenjie",
          "module": "recyclerview-swipe",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "block",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "form",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "setting",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.extend",
          "module": "baidu",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.show",
          "module": "window",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "MView-same",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "com.larswerkman",
          "module": "HoloColorPicker",
          "version": {
            "requires": "1.5"
          }
        },
        {
          "group": "org.greenrobot",
          "module": "greendao",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "com.github.yuweiguocn",
          "module": "GreenDaoUpgradeHelper",
          "version": {
            "requires": "v2.1.0"
          }
        },
        {
          "group": "com.github.czy1121",
          "module": "settingscompat",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "br.com.simplepass",
          "module": "loading-button-android",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "devlight.io",
          "module": "navigationtabbar",
          "version": {
            "requires": "1.2.5"
          }
        }
      ],
      "files": [
        {
          "name": "module-controller-1.1.0.aar",
          "url": "module-controller-1.1.0.aar",
          "size": 1920726,
          "sha512": "8fb5bfa11e44557a84a5eec988d74118ebaa57ad63342770427f605322798a44008c7a0f7c6a16552dbb7002bf121b528387623d7755fdb56f0c08ad5ebc3972",
          "sha256": "a225b5096090de46287d9a5be9d45f5a73af807dc14ecd16e219ae2eadb13027",
          "sha1": "8c7d29e079c595875937600d44b72c116a06a101",
          "md5": "4a25aac4b8b33ed2395ad7bdfd5c862b"
        }
      ]
    }
  ]
}
