{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.middle",
    "module": "form-jar",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "router",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "readonly",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.page",
          "module": "base",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.layout",
          "module": "ui",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "form-1.0.3.aar",
          "url": "form-1.0.3.aar",
          "size": 111207,
          "sha512": "be331929e32551df4b008a59372754470414fb910aadf3398a825ef4d1795ec91df1077c8eb56434287f08d161276256981fd04f6abc3956f572496f549a873d",
          "sha256": "424a751617d2deea50efa25b84a1ac59fd0f4fccef503924055702433c05efe8",
          "sha1": "ea51694df39815ad36989716970ca9cf069062c4",
          "md5": "571648dc7043d50fc7a0a672d8bf6c90"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "router",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "readonly",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.page",
          "module": "base",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.layout",
          "module": "ui",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "form-1.0.3.aar",
          "url": "form-1.0.3.aar",
          "size": 111207,
          "sha512": "be331929e32551df4b008a59372754470414fb910aadf3398a825ef4d1795ec91df1077c8eb56434287f08d161276256981fd04f6abc3956f572496f549a873d",
          "sha256": "424a751617d2deea50efa25b84a1ac59fd0f4fccef503924055702433c05efe8",
          "sha1": "ea51694df39815ad36989716970ca9cf069062c4",
          "md5": "571648dc7043d50fc7a0a672d8bf6c90"
        }
      ]
    }
  ]
}
