{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.component",
    "module": "router-jar",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.timecat.extend",
          "module": "arms",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.github.xiaojinzi123.Component",
          "module": "component-impl",
          "version": {
            "requires": "v1.9.2-androidx-java8"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "router-1.1.0.aar",
          "url": "router-1.1.0.aar",
          "size": 34241,
          "sha512": "8cca116e4254c485ea355755a0baef7cbb6e533c44c6b3ec2563429d4beb55b14979f34dfd1f4659a3e4fe3aac775db44dca962cc55fa5c227bb36727e3c782d",
          "sha256": "f7e6b9548c4b7d94d8da688ce1d0e56db7af0b22458558e19513aa20a8dac78e",
          "sha1": "e3779d8be231a6a30835a5902a6825e8fc7869f2",
          "md5": "1b25918e72722f05a912ff460532f01e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.timecat.extend",
          "module": "arms",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.github.xiaojinzi123.Component",
          "module": "component-impl",
          "version": {
            "requires": "v1.9.2-androidx-java8"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "router-1.1.0.aar",
          "url": "router-1.1.0.aar",
          "size": 34241,
          "sha512": "8cca116e4254c485ea355755a0baef7cbb6e533c44c6b3ec2563429d4beb55b14979f34dfd1f4659a3e4fe3aac775db44dca962cc55fa5c227bb36727e3c782d",
          "sha256": "f7e6b9548c4b7d94d8da688ce1d0e56db7af0b22458558e19513aa20a8dac78e",
          "sha1": "e3779d8be231a6a30835a5902a6825e8fc7869f2",
          "md5": "1b25918e72722f05a912ff460532f01e"
        }
      ]
    }
  ]
}
