{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.module",
    "module": "module-bugly-jar",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.timecat.extend",
          "module": "arms",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "router",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "service",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "readonly",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.tencent.bugly",
          "module": "crashreport_upgrade",
          "version": {
            "requires": "1.3.8"
          }
        },
        {
          "group": "com.tencent.bugly",
          "module": "nativecrashreport",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "com.umeng.umsdk",
          "module": "common",
          "version": {
            "requires": "9.4.2"
          }
        },
        {
          "group": "com.umeng.umsdk",
          "module": "asms",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.umeng.umsdk",
          "module": "apm",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "module-bugly-1.1.0.aar",
          "url": "module-bugly-1.1.0.aar",
          "size": 10884,
          "sha512": "63f80251a13f6af6a97b27289d451cdb4594dfa12d85b1e2f5853e78c72d4e6c8878ff3e4070bb74283dd5f1222e3998d1bb9850967e8a061dc234e5200044d6",
          "sha256": "7faa77a9a24c4a8d1fccfb43819c3a26b981ce0def9efe34679b73efdfd74ea0",
          "sha1": "1ad07175bdeeecc4489c4041a275d0da5ccae296",
          "md5": "19e875cf4b3cdcfcb6027285436c3605"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.timecat.extend",
          "module": "arms",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "router",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "service",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "readonly",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.tencent.bugly",
          "module": "crashreport_upgrade",
          "version": {
            "requires": "1.3.8"
          }
        },
        {
          "group": "com.tencent.bugly",
          "module": "nativecrashreport",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "com.umeng.umsdk",
          "module": "common",
          "version": {
            "requires": "9.4.2"
          }
        },
        {
          "group": "com.umeng.umsdk",
          "module": "asms",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.umeng.umsdk",
          "module": "apm",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "module-bugly-1.1.0.aar",
          "url": "module-bugly-1.1.0.aar",
          "size": 10884,
          "sha512": "63f80251a13f6af6a97b27289d451cdb4594dfa12d85b1e2f5853e78c72d4e6c8878ff3e4070bb74283dd5f1222e3998d1bb9850967e8a061dc234e5200044d6",
          "sha256": "7faa77a9a24c4a8d1fccfb43819c3a26b981ce0def9efe34679b73efdfd74ea0",
          "sha1": "1ad07175bdeeecc4489c4041a275d0da5ccae296",
          "md5": "19e875cf4b3cdcfcb6027285436c3605"
        }
      ]
    }
  ]
}
