{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.module",
    "module": "module-bugly-jar",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "com.timecat.extend",
          "module": "arms",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "router",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "service",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "readonly",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.tencent.bugly",
          "module": "crashreport_upgrade",
          "version": {
            "requires": "1.3.8"
          }
        },
        {
          "group": "com.tencent.bugly",
          "module": "nativecrashreport",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "com.umeng.umsdk",
          "module": "common",
          "version": {
            "requires": "9.4.2"
          }
        },
        {
          "group": "com.umeng.umsdk",
          "module": "asms",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.umeng.umsdk",
          "module": "apm",
          "version": {
            "requires": "1.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "module-bugly-1.1.0.aar",
          "url": "module-bugly-1.1.0.aar",
          "size": 6775,
          "sha512": "332fd8e9d18bca6d9a1f2e72aa69100ad4be0b8820cc241edf6ffe124075b5042ea067229b93c86770bc987c2d5f0c13f59a5381ca777a5aaa8ded74394dbaf5",
          "sha256": "8880e9d6410644ab6349a8e1a24ed096fca6cdcb8fd01dc8ed690e54facd30d3",
          "sha1": "881f8d7de3baff9c4f302b58842284fcaf8c9820",
          "md5": "a9df8e0f854b8ffb8346efbe278ccbcb"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "com.timecat.extend",
          "module": "arms",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "router",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "service",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "readonly",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.tencent.bugly",
          "module": "crashreport_upgrade",
          "version": {
            "requires": "1.3.8"
          }
        },
        {
          "group": "com.tencent.bugly",
          "module": "nativecrashreport",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "com.umeng.umsdk",
          "module": "common",
          "version": {
            "requires": "9.4.2"
          }
        },
        {
          "group": "com.umeng.umsdk",
          "module": "asms",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.umeng.umsdk",
          "module": "apm",
          "version": {
            "requires": "1.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "module-bugly-1.1.0.aar",
          "url": "module-bugly-1.1.0.aar",
          "size": 6775,
          "sha512": "332fd8e9d18bca6d9a1f2e72aa69100ad4be0b8820cc241edf6ffe124075b5042ea067229b93c86770bc987c2d5f0c13f59a5381ca777a5aaa8ded74394dbaf5",
          "sha256": "8880e9d6410644ab6349a8e1a24ed096fca6cdcb8fd01dc8ed690e54facd30d3",
          "sha1": "881f8d7de3baff9c4f302b58842284fcaf8c9820",
          "md5": "a9df8e0f854b8ffb8346efbe278ccbcb"
        }
      ]
    }
  ]
}
