{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.extend",
    "module": "image-jar",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.timecat.extend",
          "module": "image-preview",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "io.github.lucksiege",
          "module": "pictureselector",
          "version": {
            "requires": "v3.10.6"
          }
        },
        {
          "group": "io.github.lucksiege",
          "module": "compress",
          "version": {
            "requires": "v3.10.6"
          }
        },
        {
          "group": "io.github.lucksiege",
          "module": "ucrop",
          "version": {
            "requires": "v3.10.6"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "image-jar-1.1.0.aar",
          "url": "image-jar-1.1.0.aar",
          "size": 66856,
          "sha512": "4e6b371c58e544c44d1500b589f4d56c7f731a5d91e4893e880687e79214be1e16d65b2a553e32903d863de904df96dcbc71214a9dad1a57c319869375208dd1",
          "sha256": "8678c029fb74bd3c46820218cde9b96b20f784d2831ad96fb3f5a2d4039bf685",
          "sha1": "c3ed776e0a61113910bb92f0a44a867cdf9f3bdd",
          "md5": "36b11caa0f9a2633a6cf5a51d3954d25"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.timecat.extend",
          "module": "image-preview",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "io.github.lucksiege",
          "module": "pictureselector",
          "version": {
            "requires": "v3.10.6"
          }
        },
        {
          "group": "io.github.lucksiege",
          "module": "compress",
          "version": {
            "requires": "v3.10.6"
          }
        },
        {
          "group": "io.github.lucksiege",
          "module": "ucrop",
          "version": {
            "requires": "v3.10.6"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "image-jar-1.1.0.aar",
          "url": "image-jar-1.1.0.aar",
          "size": 66856,
          "sha512": "4e6b371c58e544c44d1500b589f4d56c7f731a5d91e4893e880687e79214be1e16d65b2a553e32903d863de904df96dcbc71214a9dad1a57c319869375208dd1",
          "sha256": "8678c029fb74bd3c46820218cde9b96b20f784d2831ad96fb3f5a2d4039bf685",
          "sha1": "c3ed776e0a61113910bb92f0a44a867cdf9f3bdd",
          "md5": "36b11caa0f9a2633a6cf5a51d3954d25"
        }
      ]
    }
  ]
}
