{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.extend",
    "module": "image-jar",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.timecat.extend",
          "module": "image-preview",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "io.github.lucksiege",
          "module": "pictureselector",
          "version": {
            "requires": "v2.7.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "image-jar-1.1.0.aar",
          "url": "image-jar-1.1.0.aar",
          "size": 49740,
          "sha512": "d554133321f1d0e9d4cfef4a0d648ef67c3c6b931cb90af38efc80f826561c77683be13318545c705166e0ed49f3f190a70cb4e85bb243c4442dee90f9734bd2",
          "sha256": "85b72568d14f6ec2f5654eb6420de5a2cbd942c649b771259aaccb31b7c4d563",
          "sha1": "99784657aba630e6767a0d0bf154c6fffa2323aa",
          "md5": "4932267977520ebaa22a66184da5affd"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.timecat.extend",
          "module": "image-preview",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "io.github.lucksiege",
          "module": "pictureselector",
          "version": {
            "requires": "v2.7.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "image-jar-1.1.0.aar",
          "url": "image-jar-1.1.0.aar",
          "size": 49740,
          "sha512": "d554133321f1d0e9d4cfef4a0d648ef67c3c6b931cb90af38efc80f826561c77683be13318545c705166e0ed49f3f190a70cb4e85bb243c4442dee90f9734bd2",
          "sha256": "85b72568d14f6ec2f5654eb6420de5a2cbd942c649b771259aaccb31b7c4d563",
          "sha1": "99784657aba630e6767a0d0bf154c6fffa2323aa",
          "md5": "4932267977520ebaa22a66184da5affd"
        }
      ]
    }
  ]
}
