{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.module",
    "module": "module-welcome-jar",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "com.timecat.page",
          "module": "base",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.layout",
          "module": "ui",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.data",
          "module": "system",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "router",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "service",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "anim",
          "version": {
            "requires": "+"
          }
        }
      ],
      "files": [
        {
          "name": "module-welcome-1.1.0.aar",
          "url": "module-welcome-1.1.0.aar",
          "size": 180173,
          "sha512": "f95340a09338f56047cd51682ffaf6f56665e2844a79046d299c026291fc0be80a54a0bc84471da242747dcba58b83a5876394013f0fa3321efa4c99ab50bebe",
          "sha256": "1f74feee9c94675c9b2a5f16a52687f4c0898223b4ac06fe2fbd8cdfa0c99625",
          "sha1": "a98b77bcef809f9ff9f65779aced9411c7691ae5",
          "md5": "f5306b0222ad217ee336204e9adf6a92"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "com.timecat.page",
          "module": "base",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.layout",
          "module": "ui",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.data",
          "module": "system",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "router",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "service",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "anim",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.jaredrummler",
          "module": "animated-svg-view",
          "version": {
            "requires": "1.0.5"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "MView-core",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "MView-intro",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "MView-font",
          "version": {
            "requires": "+"
          }
        }
      ],
      "files": [
        {
          "name": "module-welcome-1.1.0.aar",
          "url": "module-welcome-1.1.0.aar",
          "size": 180173,
          "sha512": "f95340a09338f56047cd51682ffaf6f56665e2844a79046d299c026291fc0be80a54a0bc84471da242747dcba58b83a5876394013f0fa3321efa4c99ab50bebe",
          "sha256": "1f74feee9c94675c9b2a5f16a52687f4c0898223b4ac06fe2fbd8cdfa0c99625",
          "sha1": "a98b77bcef809f9ff9f65779aced9411c7691ae5",
          "md5": "f5306b0222ad217ee336204e9adf6a92"
        }
      ]
    }
  ]
}
