{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.extend",
    "module": "image-jar",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "com.github.SherlockGougou",
          "module": "BigImageViewPager",
          "version": {
            "requires": "v4_6.0.0"
          }
        },
        {
          "group": "io.github.lucksiege",
          "module": "pictureselector",
          "version": {
            "requires": "v2.7.2"
          }
        }
      ],
      "files": [
        {
          "name": "image-1.1.0.aar",
          "url": "image-1.1.0.aar",
          "size": 33532,
          "sha512": "9027237af6162c177811b5377ad6d541786f2f7222d72a608707c80986f9cf76151a9ca0ca952c08af23e9a91f2b1ba16e5611c8c97623076253f6f4027e3c04",
          "sha256": "09a1c5f32c70b7269484216cd924ccd6c6f07278c0b6a0329ce1fae040a0e577",
          "sha1": "2edf23fe98d7b45b6fb0f8418de14d4679054ff2",
          "md5": "17ca7421359fd20a2ee82d64bda268c3"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "com.github.SherlockGougou",
          "module": "BigImageViewPager",
          "version": {
            "requires": "v4_6.0.0"
          }
        },
        {
          "group": "io.github.lucksiege",
          "module": "pictureselector",
          "version": {
            "requires": "v2.7.2"
          }
        }
      ],
      "files": [
        {
          "name": "image-1.1.0.aar",
          "url": "image-1.1.0.aar",
          "size": 33532,
          "sha512": "9027237af6162c177811b5377ad6d541786f2f7222d72a608707c80986f9cf76151a9ca0ca952c08af23e9a91f2b1ba16e5611c8c97623076253f6f4027e3c04",
          "sha256": "09a1c5f32c70b7269484216cd924ccd6c6f07278c0b6a0329ce1fae040a0e577",
          "sha1": "2edf23fe98d7b45b6fb0f8418de14d4679054ff2",
          "md5": "17ca7421359fd20a2ee82d64bda268c3"
        }
      ]
    }
  ]
}
