{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.extend",
    "module": "image-jar",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.timecat.extend",
          "module": "image-preview",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "io.github.lucksiege",
          "module": "pictureselector",
          "version": {
            "requires": "v2.7.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "image-1.1.0.aar",
          "url": "image-1.1.0.aar",
          "size": 49835,
          "sha512": "44edce0b4f0240ad8769f8d420947ba080ab739e58c8b0bd6692499073dabc2dc69665c6cd7fa9b60cf7e822e405dd10a45c0b86286197837b82591d18618844",
          "sha256": "dbe46bb7d2b60ca09763c59d3a162405533ff3d0ef31e36ce63b8693bf981695",
          "sha1": "8fa1f070706702f248ee38f631d1967532e43a68",
          "md5": "43d7e97288dbee6759390d7b86f1f929"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.timecat.extend",
          "module": "image-preview",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "io.github.lucksiege",
          "module": "pictureselector",
          "version": {
            "requires": "v2.7.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "image-1.1.0.aar",
          "url": "image-1.1.0.aar",
          "size": 49835,
          "sha512": "44edce0b4f0240ad8769f8d420947ba080ab739e58c8b0bd6692499073dabc2dc69665c6cd7fa9b60cf7e822e405dd10a45c0b86286197837b82591d18618844",
          "sha256": "dbe46bb7d2b60ca09763c59d3a162405533ff3d0ef31e36ce63b8693bf981695",
          "sha1": "8fa1f070706702f248ee38f631d1967532e43a68",
          "md5": "43d7e97288dbee6759390d7b86f1f929"
        }
      ]
    }
  ]
}
