{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.extend",
    "module": "image-jar",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "com.github.SherlockGougou",
          "module": "BigImageViewPager",
          "version": {
            "requires": "v4_6.0.0"
          }
        },
        {
          "group": "io.github.lucksiege",
          "module": "pictureselector",
          "version": {
            "requires": "v2.7.2"
          }
        }
      ],
      "files": [
        {
          "name": "image-1.1.0.aar",
          "url": "image-1.1.0.aar",
          "size": 32391,
          "sha512": "8afb2e503eccb3352c9a9f4908c11d4757d9d11b4e924a47875fc343ee4cd47813ebcb7a062135d2eaf0b4d8ed7d97d272227dcd48ba01640309ed8fb6293114",
          "sha256": "739d7d4b859b0aa8e661a250428a9710725e248c7beeb009f501e5cbe846409b",
          "sha1": "e8620be9fdce2de0bb04623a96189f299533ec73",
          "md5": "8f02f21a3239daf314f5e8d50cb8634a"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "com.github.SherlockGougou",
          "module": "BigImageViewPager",
          "version": {
            "requires": "v4_6.0.0"
          }
        },
        {
          "group": "io.github.lucksiege",
          "module": "pictureselector",
          "version": {
            "requires": "v2.7.2"
          }
        }
      ],
      "files": [
        {
          "name": "image-1.1.0.aar",
          "url": "image-1.1.0.aar",
          "size": 32391,
          "sha512": "8afb2e503eccb3352c9a9f4908c11d4757d9d11b4e924a47875fc343ee4cd47813ebcb7a062135d2eaf0b4d8ed7d97d272227dcd48ba01640309ed8fb6293114",
          "sha256": "739d7d4b859b0aa8e661a250428a9710725e248c7beeb009f501e5cbe846409b",
          "sha1": "e8620be9fdce2de0bb04623a96189f299533ec73",
          "md5": "8f02f21a3239daf314f5e8d50cb8634a"
        }
      ]
    }
  ]
}
