{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.identity",
    "module": "service-jar",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "service-jar-1.0.2.aar",
          "url": "service-jar-1.0.2.aar",
          "size": 26336,
          "sha512": "1be568bb16be4f209301a2035b14d16bf81275b421c2a1f9a5a3e5d7c239b74816bea000cc621782687cffdfb33dcd1bd36510ddfe27eb44321dee2182bb4b20",
          "sha256": "067875a86e3572e9fd98e502b18f1a88004d2a4dc80f4c9870e22ef32f6816ca",
          "sha1": "2053ed8d1cd5e67644b75092cf5574eb4256291a",
          "md5": "4587b831d9d2f55634a75ef2e1c05e8a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "service-jar-1.0.2.aar",
          "url": "service-jar-1.0.2.aar",
          "size": 26336,
          "sha512": "1be568bb16be4f209301a2035b14d16bf81275b421c2a1f9a5a3e5d7c239b74816bea000cc621782687cffdfb33dcd1bd36510ddfe27eb44321dee2182bb4b20",
          "sha256": "067875a86e3572e9fd98e502b18f1a88004d2a4dc80f4c9870e22ef32f6816ca",
          "sha1": "2053ed8d1cd5e67644b75092cf5574eb4256291a",
          "md5": "4587b831d9d2f55634a75ef2e1c05e8a"
        }
      ]
    }
  ]
}
