{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.identity",
    "module": "service-jar",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "service-jar-1.0.2.aar",
          "url": "service-jar-1.0.2.aar",
          "size": 10096,
          "sha512": "88e77b899ad453e891959fe134348d0ed3d9248122c35845377010aceca022c37ef27c7bd011829654b049578483f4bdbdc89a48697cc4b11924f885a7d301d2",
          "sha256": "a7807297baf6c1fd27dc4333de832f1831dc08842b5b90ee22a7992739c9b103",
          "sha1": "ac1b1bf62a38dc4b79d30109a407973b28ced174",
          "md5": "29dd6fe625a7d08a666b0f7ee01f83f8"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "service-jar-1.0.2.aar",
          "url": "service-jar-1.0.2.aar",
          "size": 10096,
          "sha512": "88e77b899ad453e891959fe134348d0ed3d9248122c35845377010aceca022c37ef27c7bd011829654b049578483f4bdbdc89a48697cc4b11924f885a7d301d2",
          "sha256": "a7807297baf6c1fd27dc4333de832f1831dc08842b5b90ee22a7992739c9b103",
          "sha1": "ac1b1bf62a38dc4b79d30109a407973b28ced174",
          "md5": "29dd6fe625a7d08a666b0f7ee01f83f8"
        }
      ]
    }
  ]
}
