{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.plugin",
    "module": "record-api-mock-jar",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.timecat.plugin",
          "module": "record-api",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.plugin",
          "module": "record-api-holder",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "record-api-mock-jar-1.0.0.aar",
          "url": "record-api-mock-jar-1.0.0.aar",
          "size": 115208,
          "sha512": "49e16915d75bae7d5337f2c08bed15718d68d2ef77ac3db3914629930f15062371786ba29bd673369fb6061bbab3c898833b4e134cd2f82a75b4d089167bce98",
          "sha256": "4f335ccb15818d2951dd2fb8a60fb1c5f5743468f1b18ebf6fbe990d5094579b",
          "sha1": "b439b809ed3b58beced958369b2c525e71842bbb",
          "md5": "ebbcd687bf60d01afbf6d6980c81b020"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.timecat.plugin",
          "module": "record-api",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.plugin",
          "module": "record-api-holder",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "record-api-mock-jar-1.0.0.aar",
          "url": "record-api-mock-jar-1.0.0.aar",
          "size": 115208,
          "sha512": "49e16915d75bae7d5337f2c08bed15718d68d2ef77ac3db3914629930f15062371786ba29bd673369fb6061bbab3c898833b4e134cd2f82a75b4d089167bce98",
          "sha256": "4f335ccb15818d2951dd2fb8a60fb1c5f5743468f1b18ebf6fbe990d5094579b",
          "sha1": "b439b809ed3b58beced958369b2c525e71842bbb",
          "md5": "ebbcd687bf60d01afbf6d6980c81b020"
        }
      ]
    }
  ]
}
