{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.plugin",
    "module": "record-api-mock-jar",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.timecat.plugin",
          "module": "record-api",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.plugin",
          "module": "record-api-holder",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "record-api-mock-jar-1.0.0.aar",
          "url": "record-api-mock-jar-1.0.0.aar",
          "size": 115203,
          "sha512": "3959081ed6221f471a1a060aa1a41e8d3872f3869aa10cbe57c0e9b49cc9cf4bb30eb7f9a83e0e7970183afc4ce6fe63771a101a5c8ea6b49f56081ff11c1914",
          "sha256": "648b6fea0c629e706813abb5268b2262f99a9f8303395a30694742874e71da07",
          "sha1": "e653e671397b98c3fe8d380b4a22a5272694cd32",
          "md5": "f7d6c1fefc92625c7a4f650a391485db"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.timecat.plugin",
          "module": "record-api",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.plugin",
          "module": "record-api-holder",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "record-api-mock-jar-1.0.0.aar",
          "url": "record-api-mock-jar-1.0.0.aar",
          "size": 115203,
          "sha512": "3959081ed6221f471a1a060aa1a41e8d3872f3869aa10cbe57c0e9b49cc9cf4bb30eb7f9a83e0e7970183afc4ce6fe63771a101a5c8ea6b49f56081ff11c1914",
          "sha256": "648b6fea0c629e706813abb5268b2262f99a9f8303395a30694742874e71da07",
          "sha1": "e653e671397b98c3fe8d380b4a22a5272694cd32",
          "md5": "f7d6c1fefc92625c7a4f650a391485db"
        }
      ]
    }
  ]
}
