{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.middle",
    "module": "text-jar",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "block",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "text-jar-1.0.0.aar",
          "url": "text-jar-1.0.0.aar",
          "size": 151459,
          "sha512": "2d1892ec4a64cf00fbafd5200d679fc4567de0e03b7b6c40dbe532883e05d8f83430c40a139d3a8561f7cc0e52c5f6c1beab5ccef93534dfe3ae728c4de3edc6",
          "sha256": "73be27341bc02979d448f7a5bf1c4005a8137ed7cf0fe2f287975210c85445ef",
          "sha1": "aca7703eba5d50e666cb8e496e9a851b43187c21",
          "md5": "2b9a9d58585dd4b593d4b8d537dfbfae"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "block",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "text-jar-1.0.0.aar",
          "url": "text-jar-1.0.0.aar",
          "size": 151459,
          "sha512": "2d1892ec4a64cf00fbafd5200d679fc4567de0e03b7b6c40dbe532883e05d8f83430c40a139d3a8561f7cc0e52c5f6c1beab5ccef93534dfe3ae728c4de3edc6",
          "sha256": "73be27341bc02979d448f7a5bf1c4005a8137ed7cf0fe2f287975210c85445ef",
          "sha1": "aca7703eba5d50e666cb8e496e9a851b43187c21",
          "md5": "2b9a9d58585dd4b593d4b8d537dfbfae"
        }
      ]
    }
  ]
}
