{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.middle",
    "module": "text-jar",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "block",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "text-jar-1.0.0.aar",
          "url": "text-jar-1.0.0.aar",
          "size": 153132,
          "sha512": "d07c528e0d8ef40ce5110ce83e8796a613cc94848631940395735eb26bc21ca84c4590c2fb1c5d855c70119504b62b14c231017dfa641e5257289863cf9e893d",
          "sha256": "facd0832378f18f2cffd84e65d51eeb990f86f0d409f0d9bf328eadb67700eb4",
          "sha1": "9baae2d795af711dd00363f8f50a49c2d70b3df9",
          "md5": "8aaa484634f315f1eee6b2c68c5066e9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "block",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "text-jar-1.0.0.aar",
          "url": "text-jar-1.0.0.aar",
          "size": 153132,
          "sha512": "d07c528e0d8ef40ce5110ce83e8796a613cc94848631940395735eb26bc21ca84c4590c2fb1c5d855c70119504b62b14c231017dfa641e5257289863cf9e893d",
          "sha256": "facd0832378f18f2cffd84e65d51eeb990f86f0d409f0d9bf328eadb67700eb4",
          "sha1": "9baae2d795af711dd00363f8f50a49c2d70b3df9",
          "md5": "8aaa484634f315f1eee6b2c68c5066e9"
        }
      ]
    }
  ]
}
