{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.identity",
    "module": "readonly-jar",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "readonly-1.1.0.aar",
          "url": "readonly-1.1.0.aar",
          "size": 24568,
          "sha512": "caf91bc6f4076530c9e6049c1a9058f654979de3a051fc8384b58626fd80b89fcea194716916015cb33216ca395e23613b07b195cd3878de09b3188cbe26ab8a",
          "sha256": "014e12586223c8ccd7deb66e0e74a368452ae5f4dba50f45173c05270b3dc518",
          "sha1": "b029238861238e6b80626b58b51889621fc07167",
          "md5": "f19368a3096607e561f828b4b6f72fdc"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "readonly-1.1.0.aar",
          "url": "readonly-1.1.0.aar",
          "size": 24568,
          "sha512": "caf91bc6f4076530c9e6049c1a9058f654979de3a051fc8384b58626fd80b89fcea194716916015cb33216ca395e23613b07b195cd3878de09b3188cbe26ab8a",
          "sha256": "014e12586223c8ccd7deb66e0e74a368452ae5f4dba50f45173c05270b3dc518",
          "sha1": "b029238861238e6b80626b58b51889621fc07167",
          "md5": "f19368a3096607e561f828b4b6f72fdc"
        }
      ]
    }
  ]
}
