{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.identity",
    "module": "readonly-jar",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "readonly-1.1.0.aar",
          "url": "readonly-1.1.0.aar",
          "size": 43540,
          "sha512": "2304bfc35e49f021ef8cb13bdda2a95ba9739aaf7e4102471dbd484bebc2b9f71d10f298b8169baac4d3afc8ef52f23b785b1128412ef35e3df2e59110c95a6d",
          "sha256": "a2899757b3bf849bccc42ae06a0dfac2a64c3635b4c44591db4f1f34fe1cd9a5",
          "sha1": "17a8c58f92958304168e6633b7cad88891a49373",
          "md5": "6518ad0c592a897ac68b331b9be669e1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "readonly-1.1.0.aar",
          "url": "readonly-1.1.0.aar",
          "size": 43540,
          "sha512": "2304bfc35e49f021ef8cb13bdda2a95ba9739aaf7e4102471dbd484bebc2b9f71d10f298b8169baac4d3afc8ef52f23b785b1128412ef35e3df2e59110c95a6d",
          "sha256": "a2899757b3bf849bccc42ae06a0dfac2a64c3635b4c44591db4f1f34fe1cd9a5",
          "sha1": "17a8c58f92958304168e6633b7cad88891a49373",
          "md5": "6518ad0c592a897ac68b331b9be669e1"
        }
      ]
    }
  ]
}
