{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.identity",
    "module": "readonly-jar",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "readonly-1.1.0.aar",
          "url": "readonly-1.1.0.aar",
          "size": 27167,
          "sha512": "53cdd36eb5182e0043071022621fdd76aeb39d56eb5398fcf4d92a18dde8b513386e408fcd9f6a767e9f85dfab737cf9bd8129cbad7045c86c65e7fa1c08f4b6",
          "sha256": "5c5da6717c9f1ef7f0d283b55b5f6a6606577e9595e98e87b198773f0a146337",
          "sha1": "636cd912987d49d9c61fbf0addf137b76032a5a5",
          "md5": "372ac8cc63e04588962ffe977226a2f6"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "readonly-1.1.0.aar",
          "url": "readonly-1.1.0.aar",
          "size": 27167,
          "sha512": "53cdd36eb5182e0043071022621fdd76aeb39d56eb5398fcf4d92a18dde8b513386e408fcd9f6a767e9f85dfab737cf9bd8129cbad7045c86c65e7fa1c08f4b6",
          "sha256": "5c5da6717c9f1ef7f0d283b55b5f6a6606577e9595e98e87b198773f0a146337",
          "sha1": "636cd912987d49d9c61fbf0addf137b76032a5a5",
          "md5": "372ac8cc63e04588962ffe977226a2f6"
        }
      ]
    }
  ]
}
