{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.extend",
    "module": "image-preview-jar",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "com.davemorrissey.labs",
          "module": "subsampling-scale-image-view",
          "version": {
            "requires": "3.10.0"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "okhttp3-integration",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "image-preview-1.0.0.aar",
          "url": "image-preview-1.0.0.aar",
          "size": 228335,
          "sha512": "e48ff045952e75a48dd46fdfd77832885ed395083d96af83cf50d1255982fd38edfea02075859ea069c83338d8ef95efafef5b56813bc6120ddbe02783cf1738",
          "sha256": "c69fe0c45e522f67f9fcba1333e8c73ea82e308035964234ed99c811c797a150",
          "sha1": "9d3ea48972d51538006b58c7d1f518ec3c7252c3",
          "md5": "41a7b61abfef680bdc927a827ad015b1"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "com.davemorrissey.labs",
          "module": "subsampling-scale-image-view",
          "version": {
            "requires": "3.10.0"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "okhttp3-integration",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "image-preview-1.0.0.aar",
          "url": "image-preview-1.0.0.aar",
          "size": 228335,
          "sha512": "e48ff045952e75a48dd46fdfd77832885ed395083d96af83cf50d1255982fd38edfea02075859ea069c83338d8ef95efafef5b56813bc6120ddbe02783cf1738",
          "sha256": "c69fe0c45e522f67f9fcba1333e8c73ea82e308035964234ed99c811c797a150",
          "sha1": "9d3ea48972d51538006b58c7d1f518ec3c7252c3",
          "md5": "41a7b61abfef680bdc927a827ad015b1"
        }
      ]
    }
  ]
}
