{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.extend",
    "module": "image-preview-jar",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "com.davemorrissey.labs",
          "module": "subsampling-scale-image-view",
          "version": {
            "requires": "3.10.0"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "okhttp3-integration",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "image-preview-1.0.0.aar",
          "url": "image-preview-1.0.0.aar",
          "size": 218875,
          "sha512": "ffd9c76c82b72bb583a7a9002c84ce481c9ef3535411dca9b3793ecbf123044d6782e5767f6c9952a972305e682ac31e9b84af304770e0932f223591d46d65db",
          "sha256": "5f4d3fbf1d39e8738229e07947daf31b112a4af4b835fc8089d58493c1f0f285",
          "sha1": "a2c3eaffd0ec46bd95ae092ba49d824fb5b4c5a7",
          "md5": "97ac84bad9141fe0966e9913cbfe0a49"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "com.davemorrissey.labs",
          "module": "subsampling-scale-image-view",
          "version": {
            "requires": "3.10.0"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "okhttp3-integration",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "image-preview-1.0.0.aar",
          "url": "image-preview-1.0.0.aar",
          "size": 218875,
          "sha512": "ffd9c76c82b72bb583a7a9002c84ce481c9ef3535411dca9b3793ecbf123044d6782e5767f6c9952a972305e682ac31e9b84af304770e0932f223591d46d65db",
          "sha256": "5f4d3fbf1d39e8738229e07947daf31b112a4af4b835fc8089d58493c1f0f285",
          "sha1": "a2c3eaffd0ec46bd95ae092ba49d824fb5b4c5a7",
          "md5": "97ac84bad9141fe0966e9913cbfe0a49"
        }
      ]
    }
  ]
}
