{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.component",
    "module": "identity-jar",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.timecat.identity",
          "module": "resources",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "skin",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.extend",
          "module": "arms",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "skin.support",
          "module": "skin-support-appcompat",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "skin.support",
          "module": "skin-support-design",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "skin.support",
          "module": "skin-support-cardview",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "skin.support",
          "module": "skin-support-constraint-layout",
          "version": {
            "requires": "+"
          }
        }
      ],
      "files": [
        {
          "name": "identity-jar-1.0.2.aar",
          "url": "identity-jar-1.0.2.aar",
          "size": 71937,
          "sha512": "d0e30b7966735cce094f980a6e6962a635f0f829f84c0f521e4935f203821fee0dfab8f9505a7d6bc91cab44619e0469c0be95b89a2c0b75550c4352ef651c27",
          "sha256": "277f2f46734b1f0c380748dd29c40d6eb7ef9be4ae4f1bad6aa8887c19e7bd48",
          "sha1": "edfed5e666e12d45609d23bd6a90acd24a0599d0",
          "md5": "6622f1c8d7bbf81f3c46956419c1553b"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.timecat.identity",
          "module": "resources",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "skin",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.extend",
          "module": "arms",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "skin.support",
          "module": "skin-support-appcompat",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "skin.support",
          "module": "skin-support-design",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "skin.support",
          "module": "skin-support-cardview",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "skin.support",
          "module": "skin-support-constraint-layout",
          "version": {
            "requires": "+"
          }
        }
      ],
      "files": [
        {
          "name": "identity-jar-1.0.2.aar",
          "url": "identity-jar-1.0.2.aar",
          "size": 71937,
          "sha512": "d0e30b7966735cce094f980a6e6962a635f0f829f84c0f521e4935f203821fee0dfab8f9505a7d6bc91cab44619e0469c0be95b89a2c0b75550c4352ef651c27",
          "sha256": "277f2f46734b1f0c380748dd29c40d6eb7ef9be4ae4f1bad6aa8887c19e7bd48",
          "sha1": "edfed5e666e12d45609d23bd6a90acd24a0599d0",
          "md5": "6622f1c8d7bbf81f3c46956419c1553b"
        }
      ]
    }
  ]
}
