{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.component",
    "module": "identity-jar",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "resources",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "skin",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.extend",
          "module": "arms",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "skin.support",
          "module": "skin-support-appcompat",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "skin.support",
          "module": "skin-support-design",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "skin.support",
          "module": "skin-support-cardview",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "skin.support",
          "module": "skin-support-constraint-layout",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "identity-jar-1.0.2.aar",
          "url": "identity-jar-1.0.2.aar",
          "size": 79721,
          "sha512": "fa1d3f1e5d25ffadf7b077b52426fabffd35066a9817eabca467e1947c19023e486d790a6308f816d73445045ad5f5f9f05444ae477bf9ce1dce3e084e6d0b28",
          "sha256": "2bcad8f3dff6de3b01bfe05a4c443e0f42196719984eb0d93bfd20c38cb6973d",
          "sha1": "5f04e7b7bd8cdf00a1ef03b0c44c03997871f53c",
          "md5": "df3276dc4269ee6045dcd96bee6a50f2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "resources",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "skin",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.extend",
          "module": "arms",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "skin.support",
          "module": "skin-support-appcompat",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "skin.support",
          "module": "skin-support-design",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "skin.support",
          "module": "skin-support-cardview",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "skin.support",
          "module": "skin-support-constraint-layout",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "identity-jar-1.0.2.aar",
          "url": "identity-jar-1.0.2.aar",
          "size": 79721,
          "sha512": "fa1d3f1e5d25ffadf7b077b52426fabffd35066a9817eabca467e1947c19023e486d790a6308f816d73445045ad5f5f9f05444ae477bf9ce1dce3e084e6d0b28",
          "sha256": "2bcad8f3dff6de3b01bfe05a4c443e0f42196719984eb0d93bfd20c38cb6973d",
          "sha1": "5f04e7b7bd8cdf00a1ef03b0c44c03997871f53c",
          "md5": "df3276dc4269ee6045dcd96bee6a50f2"
        }
      ]
    }
  ]
}
