{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.module",
    "module": "module-about-jar",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.timecat.page",
          "module": "base",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.layout",
          "module": "ui",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "router",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.github.daniel-stoneuk",
          "module": "material-about-library",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "module-about-1.1.0.aar",
          "url": "module-about-1.1.0.aar",
          "size": 178837,
          "sha512": "1082625ddb67add78336e52ab78dcdae8700b14a352ad6a92d01e602e12d789fbe890a4b8c22eccc86a32ae4b9fc7b17a843eab088e038805e77ada77c6d2f4d",
          "sha256": "8fc40def1e30b09093ddda06000710dd153c718667522af75a32cbf23cfb1b84",
          "sha1": "cef59ce589078f05cb01d679b5e09ba0bcf8c33c",
          "md5": "0a61855175d1dfa4aa14e6eca3a79cd2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.timecat.page",
          "module": "base",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.layout",
          "module": "ui",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "router",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.github.daniel-stoneuk",
          "module": "material-about-library",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "com.drakeet.about",
          "module": "about",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "com.drakeet.multitype",
          "module": "multitype",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "com.heinrichreimersoftware",
          "module": "material-intro",
          "version": {
            "requires": "1.6"
          }
        },
        {
          "group": "com.mikepenz",
          "module": "aboutlibraries",
          "version": {
            "requires": "5.2.5"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "aboutlibraries",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "com.makeramen",
          "module": "roundedimageview",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "module-about-1.1.0.aar",
          "url": "module-about-1.1.0.aar",
          "size": 178837,
          "sha512": "1082625ddb67add78336e52ab78dcdae8700b14a352ad6a92d01e602e12d789fbe890a4b8c22eccc86a32ae4b9fc7b17a843eab088e038805e77ada77c6d2f4d",
          "sha256": "8fc40def1e30b09093ddda06000710dd153c718667522af75a32cbf23cfb1b84",
          "sha1": "cef59ce589078f05cb01d679b5e09ba0bcf8c33c",
          "md5": "0a61855175d1dfa4aa14e6eca3a79cd2"
        }
      ]
    }
  ]
}
