{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.module",
    "module": "module-about-jar",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "com.timecat.page",
          "module": "base",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.layout",
          "module": "ui",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "router",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.github.daniel-stoneuk",
          "module": "material-about-library",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "module-about-1.1.0.aar",
          "url": "module-about-1.1.0.aar",
          "size": 174316,
          "sha512": "af8f59ed6690cd740891fa75b4a31ad27131f54f44268f69f3968fc23373af74984a3d268b613c8dd332f230624405ddce0dead6d7528f6794d32d67f50caffc",
          "sha256": "d99432080fad24c6b00971d9f71f608ebeac04b3f354d35fc182921048b391d4",
          "sha1": "f0be5086b52f639823a41f05c7fa13f95a31fb8e",
          "md5": "a06acbac3c9339ee0a9d441e73586063"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "com.timecat.page",
          "module": "base",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.layout",
          "module": "ui",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "router",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.github.daniel-stoneuk",
          "module": "material-about-library",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "com.drakeet.about",
          "module": "about",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "com.drakeet.multitype",
          "module": "multitype",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "com.heinrichreimersoftware",
          "module": "material-intro",
          "version": {
            "requires": "1.6"
          }
        },
        {
          "group": "com.mikepenz",
          "module": "aboutlibraries",
          "version": {
            "requires": "5.2.5"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "aboutlibraries",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "com.makeramen",
          "module": "roundedimageview",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "module-about-1.1.0.aar",
          "url": "module-about-1.1.0.aar",
          "size": 174316,
          "sha512": "af8f59ed6690cd740891fa75b4a31ad27131f54f44268f69f3968fc23373af74984a3d268b613c8dd332f230624405ddce0dead6d7528f6794d32d67f50caffc",
          "sha256": "d99432080fad24c6b00971d9f71f608ebeac04b3f354d35fc182921048b391d4",
          "sha1": "f0be5086b52f639823a41f05c7fa13f95a31fb8e",
          "md5": "a06acbac3c9339ee0a9d441e73586063"
        }
      ]
    }
  ]
}
