{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.module",
    "module": "module-guide-jar",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.timecat.page",
          "module": "base",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.layout",
          "module": "ui",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.data",
          "module": "system",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "router",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "service",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "anim",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "guide-api",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "guide-view",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.tbuonomo.andrui",
          "module": "viewpagerdotsindicator",
          "version": {
            "requires": "4.1.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "module-guide-1.0.0.aar",
          "url": "module-guide-1.0.0.aar",
          "size": 210928,
          "sha512": "729950763d0d061775d2663f0a387c083ad48dd987ea77aaca1c90962397ffe5e570709a23e430439c51e6dddf65c6d4d408bb63a653324cda74166ef0389d05",
          "sha256": "6a4974e27401a08cd887d970613ecba7e4a33e2562068461b733b7ec872cf0d1",
          "sha1": "a33f31e73f60ce679503592bd02a270ad32a83d3",
          "md5": "d0bb5344ab022d11426353f3b5ee6793"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.timecat.page",
          "module": "base",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.layout",
          "module": "ui",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.data",
          "module": "system",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "router",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "service",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "anim",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "guide-api",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "guide-view",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.tbuonomo.andrui",
          "module": "viewpagerdotsindicator",
          "version": {
            "requires": "4.1.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "module-guide-1.0.0.aar",
          "url": "module-guide-1.0.0.aar",
          "size": 210928,
          "sha512": "729950763d0d061775d2663f0a387c083ad48dd987ea77aaca1c90962397ffe5e570709a23e430439c51e6dddf65c6d4d408bb63a653324cda74166ef0389d05",
          "sha256": "6a4974e27401a08cd887d970613ecba7e4a33e2562068461b733b7ec872cf0d1",
          "sha1": "a33f31e73f60ce679503592bd02a270ad32a83d3",
          "md5": "d0bb5344ab022d11426353f3b5ee6793"
        }
      ]
    }
  ]
}
