{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.component",
    "module": "setting-jar",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "readonly",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.extend",
          "module": "arms",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "com.tencent",
          "module": "mmkv",
          "version": {
            "requires": "1.2.9"
          }
        }
      ],
      "files": [
        {
          "name": "setting-1.1.0.aar",
          "url": "setting-1.1.0.aar",
          "size": 86895,
          "sha512": "0065ff39add097aa185a0e1ce6e2ff3f47c96da493f47880a3d556eeb0026dd6bdaaaf5c44351513c63d95aee3c9347359295d44700d2e9807ad039359f64f81",
          "sha256": "d27686f36c43addec7995df311f42cbfb40c242f2445669afa99ce9b6bd5b7eb",
          "sha1": "6994b12fdf3569eaf5ed9123a5f0dad56e4d65eb",
          "md5": "380b451e6c608b0d3ba99d02531fcfe9"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "readonly",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.extend",
          "module": "arms",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "com.tencent",
          "module": "mmkv",
          "version": {
            "requires": "1.2.9"
          }
        }
      ],
      "files": [
        {
          "name": "setting-1.1.0.aar",
          "url": "setting-1.1.0.aar",
          "size": 86895,
          "sha512": "0065ff39add097aa185a0e1ce6e2ff3f47c96da493f47880a3d556eeb0026dd6bdaaaf5c44351513c63d95aee3c9347359295d44700d2e9807ad039359f64f81",
          "sha256": "d27686f36c43addec7995df311f42cbfb40c242f2445669afa99ce9b6bd5b7eb",
          "sha1": "6994b12fdf3569eaf5ed9123a5f0dad56e4d65eb",
          "md5": "380b451e6c608b0d3ba99d02531fcfe9"
        }
      ]
    }
  ]
}
