{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.module",
    "module": "module-skin-jar",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "form",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "block",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.data",
          "module": "bmob",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "readonly",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "download",
          "version": {
            "requires": "+"
          }
        }
      ],
      "files": [
        {
          "name": "module-skin-1.0.0.aar",
          "url": "module-skin-1.0.0.aar",
          "size": 304349,
          "sha512": "f78472000ecd906797bf1872ada8aaa67789888191d7841a6108c53eeafafc13a5f05d0c5212c0e9c59fba772e535ab7190b7b03569dc6a09198be5736b9af00",
          "sha256": "ad0fac8c23914c2e8b2eafd1f9468c0b1b33a9fe9cb6bf1409d9725010b0bb31",
          "sha1": "53cb5e906a06392b57d12b9f3d4b077df2187e0f",
          "md5": "801fbc5953be9d1449b6d11de2c2e6f9"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "form",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "block",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.data",
          "module": "bmob",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "readonly",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "download",
          "version": {
            "requires": "+"
          }
        }
      ],
      "files": [
        {
          "name": "module-skin-1.0.0.aar",
          "url": "module-skin-1.0.0.aar",
          "size": 304349,
          "sha512": "f78472000ecd906797bf1872ada8aaa67789888191d7841a6108c53eeafafc13a5f05d0c5212c0e9c59fba772e535ab7190b7b03569dc6a09198be5736b9af00",
          "sha256": "ad0fac8c23914c2e8b2eafd1f9468c0b1b33a9fe9cb6bf1409d9725010b0bb31",
          "sha1": "53cb5e906a06392b57d12b9f3d4b077df2187e0f",
          "md5": "801fbc5953be9d1449b6d11de2c2e6f9"
        }
      ]
    }
  ]
}
