{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.module",
    "module": "module-skin-jar",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "form",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "block",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.data",
          "module": "bmob",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "readonly",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "download",
          "version": {
            "requires": "+"
          }
        }
      ],
      "files": [
        {
          "name": "module-skin-1.0.0.aar",
          "url": "module-skin-1.0.0.aar",
          "size": 299855,
          "sha512": "8e05ad2bb05b7950ea47a63bedbc2a12119bd644a410f08b6f33d1644cf8476caa85a40fc54bbe42d23d95d45b0337196fb37dcf78c127fbd8ac4b7c9de652f9",
          "sha256": "ce6ac6066ce35de49e2f2eba2508d357f9fc196c7d3daf15df6049fa361bdf16",
          "sha1": "05d8738b1e318467508e86bba107a9c7aba71c67",
          "md5": "149bde1efdcbb228263db6719316b1aa"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "form",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "block",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.data",
          "module": "bmob",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "readonly",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "download",
          "version": {
            "requires": "+"
          }
        }
      ],
      "files": [
        {
          "name": "module-skin-1.0.0.aar",
          "url": "module-skin-1.0.0.aar",
          "size": 299855,
          "sha512": "8e05ad2bb05b7950ea47a63bedbc2a12119bd644a410f08b6f33d1644cf8476caa85a40fc54bbe42d23d95d45b0337196fb37dcf78c127fbd8ac4b7c9de652f9",
          "sha256": "ce6ac6066ce35de49e2f2eba2508d357f9fc196c7d3daf15df6049fa361bdf16",
          "sha1": "05d8738b1e318467508e86bba107a9c7aba71c67",
          "md5": "149bde1efdcbb228263db6719316b1aa"
        }
      ]
    }
  ]
}
