{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.module",
    "module": "module-skin-jar",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "form",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "block",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.data",
          "module": "bmob",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "readonly",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "download",
          "version": {
            "requires": "+"
          }
        }
      ],
      "files": [
        {
          "name": "module-skin-1.0.0.aar",
          "url": "module-skin-1.0.0.aar",
          "size": 299854,
          "sha512": "8761603f9a6fd0df6f1072fbd32ebfa8447be9a8893b6c71015f44c5134968afba084c472cb960276129514d0a77e2f2ee0421ce257df68a51172947f3d66e7f",
          "sha256": "daba7f1d997505641986d984045bd2c2df9e1a04c72d9a11711353d0f3bb3b37",
          "sha1": "19bd9e16f1d00c2ff1bc02aaf4a870ede74795d6",
          "md5": "727f5de1452ca3497f7214bc99696597"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "form",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "block",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.data",
          "module": "bmob",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "readonly",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "download",
          "version": {
            "requires": "+"
          }
        }
      ],
      "files": [
        {
          "name": "module-skin-1.0.0.aar",
          "url": "module-skin-1.0.0.aar",
          "size": 299854,
          "sha512": "8761603f9a6fd0df6f1072fbd32ebfa8447be9a8893b6c71015f44c5134968afba084c472cb960276129514d0a77e2f2ee0421ce257df68a51172947f3d66e7f",
          "sha256": "daba7f1d997505641986d984045bd2c2df9e1a04c72d9a11711353d0f3bb3b37",
          "sha1": "19bd9e16f1d00c2ff1bc02aaf4a870ede74795d6",
          "md5": "727f5de1452ca3497f7214bc99696597"
        }
      ]
    }
  ]
}
