{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.plugin",
    "module": "record-api-jar",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "block",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "record-api-1.0.0.aar",
          "url": "record-api-1.0.0.aar",
          "size": 115767,
          "sha512": "a773ea78cb708b16ed4d2e9896f875149213ad8e3632ea1a916ec2057e6e7056150d96086dca0fc60d95b45f171cfd87a00193090c5cf95fd1f1232b62f103f6",
          "sha256": "0144bb4ea14a101ae936b129bc2997eefc5ea88a9cc489fc84a06230daa3bd41",
          "sha1": "f066ebffa176254f96eb20cf7d02b28473bd955b",
          "md5": "bc4b08c55091e9c74b5fd99414407606"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "block",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "record-api-1.0.0.aar",
          "url": "record-api-1.0.0.aar",
          "size": 115767,
          "sha512": "a773ea78cb708b16ed4d2e9896f875149213ad8e3632ea1a916ec2057e6e7056150d96086dca0fc60d95b45f171cfd87a00193090c5cf95fd1f1232b62f103f6",
          "sha256": "0144bb4ea14a101ae936b129bc2997eefc5ea88a9cc489fc84a06230daa3bd41",
          "sha1": "f066ebffa176254f96eb20cf7d02b28473bd955b",
          "md5": "bc4b08c55091e9c74b5fd99414407606"
        }
      ]
    }
  ]
}
