{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.plugin",
    "module": "record-api-jar",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "block",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "record-api-1.0.0.aar",
          "url": "record-api-1.0.0.aar",
          "size": 107752,
          "sha512": "d73484f6893cf299589b55bf647d7003ba2ab89833301e5049b5a9c71d31155bf177da2df4b01f2e3206bbca2c54c95d91a1388afb4a13cb3012ae461151cdb4",
          "sha256": "02bdf6f907d95f786955ef532308dac33a177587447bd21a80052a9b6a423ebf",
          "sha1": "22504d725458790bc884edf9989e3a36d230ae6a",
          "md5": "76a4e5e8e68bb975e2af4a8324edb1d3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "block",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "record-api-1.0.0.aar",
          "url": "record-api-1.0.0.aar",
          "size": 107752,
          "sha512": "d73484f6893cf299589b55bf647d7003ba2ab89833301e5049b5a9c71d31155bf177da2df4b01f2e3206bbca2c54c95d91a1388afb4a13cb3012ae461151cdb4",
          "sha256": "02bdf6f907d95f786955ef532308dac33a177587447bd21a80052a9b6a423ebf",
          "sha1": "22504d725458790bc884edf9989e3a36d230ae6a",
          "md5": "76a4e5e8e68bb975e2af4a8324edb1d3"
        }
      ]
    }
  ]
}
