{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.identity",
    "module": "skin-jar",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "skin.support",
          "module": "skin-support",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "skin-1.0.1.aar",
          "url": "skin-1.0.1.aar",
          "size": 19789,
          "sha512": "edeac884445233926f3686ce9c9a0f4765fe9b47b68657cec96c3559f931a3daeca8d0351ec7143418f473d34ff1bc2b41050e0e5986517060ebd6e1e5ee7732",
          "sha256": "a5b188d2a899382059ecd5fc2a1f5aea2335be58e7db0c18a3ca5e71c1c91329",
          "sha1": "50b8412942222947a3a48b9284657d75df030d11",
          "md5": "6f09c6580429b21a7fb7945e373a18b9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "skin.support",
          "module": "skin-support",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "skin-1.0.1.aar",
          "url": "skin-1.0.1.aar",
          "size": 19789,
          "sha512": "edeac884445233926f3686ce9c9a0f4765fe9b47b68657cec96c3559f931a3daeca8d0351ec7143418f473d34ff1bc2b41050e0e5986517060ebd6e1e5ee7732",
          "sha256": "a5b188d2a899382059ecd5fc2a1f5aea2335be58e7db0c18a3ca5e71c1c91329",
          "sha1": "50b8412942222947a3a48b9284657d75df030d11",
          "md5": "6f09c6580429b21a7fb7945e373a18b9"
        }
      ]
    }
  ]
}
