{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.module",
    "module": "module-login-jar",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "com.timecat.page",
          "module": "base",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.layout",
          "module": "ui",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.data",
          "module": "bmob",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.data",
          "module": "system",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "router",
          "version": {
            "requires": "+"
          }
        }
      ],
      "files": [
        {
          "name": "module-login-1.1.0.aar",
          "url": "module-login-1.1.0.aar",
          "size": 192446,
          "sha512": "b8ddc9853c9b3f6791c69a5283f58f2d05349726959a5c14b3236fef54d5262b532eb4cac86fe7ff6b715e488c0fcf7fafd633a68ec8569f92783539a6fb54e6",
          "sha256": "29bfde73ae2d01de2e34329ac9e2632526d4da7ce6aa542e524eadb879d04a54",
          "sha1": "d6f68031f82a36c9d79f8cc31b2e7a6cf800db6e",
          "md5": "01d97743e8d387fd51e91eafe0dc0486"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "com.timecat.page",
          "module": "base",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.layout",
          "module": "ui",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.data",
          "module": "bmob",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.data",
          "module": "system",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "router",
          "version": {
            "requires": "+"
          }
        }
      ],
      "files": [
        {
          "name": "module-login-1.1.0.aar",
          "url": "module-login-1.1.0.aar",
          "size": 192446,
          "sha512": "b8ddc9853c9b3f6791c69a5283f58f2d05349726959a5c14b3236fef54d5262b532eb4cac86fe7ff6b715e488c0fcf7fafd633a68ec8569f92783539a6fb54e6",
          "sha256": "29bfde73ae2d01de2e34329ac9e2632526d4da7ce6aa542e524eadb879d04a54",
          "sha1": "d6f68031f82a36c9d79f8cc31b2e7a6cf800db6e",
          "md5": "01d97743e8d387fd51e91eafe0dc0486"
        }
      ]
    }
  ]
}
