{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.identity",
    "module": "anim-jar",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "anim-jar-1.0.1.aar",
          "url": "anim-jar-1.0.1.aar",
          "size": 43345,
          "sha512": "127e6657cc73aeb94c672cce9353303e4620627828f7e957e733a63f6bfb6eb742c4f09effd840d1bfc348802681eb8938ac3593bae0deb9504ee12c58d68435",
          "sha256": "e96707c308e62e240c85c2b5a06297e943f99f4d5d753744706b086e5ae27ae7",
          "sha1": "5accc93100ffc8919ab0ec2c7aed62e5f3d89dab",
          "md5": "55e8c2892b24a2f39a5452640b581d68"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "anim-jar-1.0.1.aar",
          "url": "anim-jar-1.0.1.aar",
          "size": 43345,
          "sha512": "127e6657cc73aeb94c672cce9353303e4620627828f7e957e733a63f6bfb6eb742c4f09effd840d1bfc348802681eb8938ac3593bae0deb9504ee12c58d68435",
          "sha256": "e96707c308e62e240c85c2b5a06297e943f99f4d5d753744706b086e5ae27ae7",
          "sha1": "5accc93100ffc8919ab0ec2c7aed62e5f3d89dab",
          "md5": "55e8c2892b24a2f39a5452640b581d68"
        }
      ]
    }
  ]
}
