{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.identity",
    "module": "anim-jar",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.31"
          }
        }
      ],
      "files": [
        {
          "name": "anim-jar-1.0.1.aar",
          "url": "anim-jar-1.0.1.aar",
          "size": 27839,
          "sha512": "a1b87802c167442d520921d3de50f40d6755bd9eef271014eed6d0df8792d3f674512a518c67d69d14c083301f4df7cde4245676fda100fa647b7ed30fe463fa",
          "sha256": "d1c26bc59570d15f497b11f3c6408b1d7244e6884dc76a53a4ba37235a71faf3",
          "sha1": "5a6308d18b26ad8a52faa814f11ade86574b8439",
          "md5": "4053636b35bf57eefbc601a1691d97df"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.31"
          }
        }
      ],
      "files": [
        {
          "name": "anim-jar-1.0.1.aar",
          "url": "anim-jar-1.0.1.aar",
          "size": 27839,
          "sha512": "a1b87802c167442d520921d3de50f40d6755bd9eef271014eed6d0df8792d3f674512a518c67d69d14c083301f4df7cde4245676fda100fa647b7ed30fe463fa",
          "sha256": "d1c26bc59570d15f497b11f3c6408b1d7244e6884dc76a53a4ba37235a71faf3",
          "sha1": "5a6308d18b26ad8a52faa814f11ade86574b8439",
          "md5": "4053636b35bf57eefbc601a1691d97df"
        }
      ]
    }
  ]
}
