{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.element",
    "module": "alert-jar",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.timecat.extend",
          "module": "arms",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.afollestad.material-dialogs",
          "module": "core",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "com.afollestad.material-dialogs",
          "module": "input",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "com.afollestad.material-dialogs",
          "module": "lifecycle",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "com.afollestad.material-dialogs",
          "module": "datetime",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "com.afollestad.material-dialogs",
          "module": "color",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "com.afollestad.material-dialogs",
          "module": "files",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "com.afollestad.material-dialogs",
          "module": "bottomsheets",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "com.github.GrenderG",
          "module": "Toasty",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "com.nispok",
          "module": "snackbar",
          "version": {
            "requires": "2.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "alert-jar-1.0.0.aar",
          "url": "alert-jar-1.0.0.aar",
          "size": 38849,
          "sha512": "091ce09dc007284c0eba98c014e3956967764c524b74bc481a5580331767d69bc36f06a72e94b5f1de0aa9eb9b143a9ffdd3f38075027aad6c1d8fe09b0aaca1",
          "sha256": "e8c314f895fb6b565eb7b1d90477088a2be8048a02a66fbbe5876d9462ffb9e2",
          "sha1": "3f15cdff9b90d809b6c1fd53016d8fe168eaefcd",
          "md5": "a16796fbc1cef6b65600981294f6672e"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.timecat.extend",
          "module": "arms",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.afollestad.material-dialogs",
          "module": "core",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "com.afollestad.material-dialogs",
          "module": "input",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "com.afollestad.material-dialogs",
          "module": "lifecycle",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "com.afollestad.material-dialogs",
          "module": "datetime",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "com.afollestad.material-dialogs",
          "module": "color",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "com.afollestad.material-dialogs",
          "module": "files",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "com.afollestad.material-dialogs",
          "module": "bottomsheets",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "com.github.GrenderG",
          "module": "Toasty",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "com.nispok",
          "module": "snackbar",
          "version": {
            "requires": "2.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "alert-jar-1.0.0.aar",
          "url": "alert-jar-1.0.0.aar",
          "size": 38849,
          "sha512": "091ce09dc007284c0eba98c014e3956967764c524b74bc481a5580331767d69bc36f06a72e94b5f1de0aa9eb9b143a9ffdd3f38075027aad6c1d8fe09b0aaca1",
          "sha256": "e8c314f895fb6b565eb7b1d90477088a2be8048a02a66fbbe5876d9462ffb9e2",
          "sha1": "3f15cdff9b90d809b6c1fd53016d8fe168eaefcd",
          "md5": "a16796fbc1cef6b65600981294f6672e"
        }
      ]
    }
  ]
}
