{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.page",
    "module": "navigation-jar",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.timecat.page",
          "module": "scene",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-jar-1.0.1.aar",
          "url": "navigation-jar-1.0.1.aar",
          "size": 188240,
          "sha512": "c185b6d39925363a4416e13cd7c5bf53aa9cb97ce62a218f75e1e7fd0c1f7e5e8265d79e6dd55256e3ecfdfaa5526e572288475c8b830617b72bbb0bdd59c9c7",
          "sha256": "3f0f067b055914dca466e09c03a915a0a9946ec88df7588305a47090f8c7cd76",
          "sha1": "f3e0513a48d6a759f87b58179bdce6e40830f9ac",
          "md5": "ee3085bedecd9c4737497e850c335bed"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.timecat.page",
          "module": "scene",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-jar-1.0.1.aar",
          "url": "navigation-jar-1.0.1.aar",
          "size": 188240,
          "sha512": "c185b6d39925363a4416e13cd7c5bf53aa9cb97ce62a218f75e1e7fd0c1f7e5e8265d79e6dd55256e3ecfdfaa5526e572288475c8b830617b72bbb0bdd59c9c7",
          "sha256": "3f0f067b055914dca466e09c03a915a0a9946ec88df7588305a47090f8c7cd76",
          "sha1": "f3e0513a48d6a759f87b58179bdce6e40830f9ac",
          "md5": "ee3085bedecd9c4737497e850c335bed"
        }
      ]
    }
  ]
}
