{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.middle",
    "module": "selector-jar",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.timecat.extend",
          "module": "image",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "readonly",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.page",
          "module": "base",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.layout",
          "module": "ui",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "selector-1.1.0.aar",
          "url": "selector-1.1.0.aar",
          "size": 129849,
          "sha512": "4f4d8eb97b4ccc03b38e6c7a4a1dfcd517c3f5312783f0b14e0311d5b7d283afef2f00eecbac1d70ab95666e5a73678117023aee15bc004392f4d171ae9abffc",
          "sha256": "ebbe26e697146a08c8269e6be4b5622f5f55a0618e159eb47bc03de3e2f7ca14",
          "sha1": "8fa17a61433da05b4c63bf9502daf5e9bd864564",
          "md5": "bad27ef9b37aaa701dee1ae6d6d1ac85"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.timecat.extend",
          "module": "image",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "readonly",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.page",
          "module": "base",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.layout",
          "module": "ui",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "selector-1.1.0.aar",
          "url": "selector-1.1.0.aar",
          "size": 129849,
          "sha512": "4f4d8eb97b4ccc03b38e6c7a4a1dfcd517c3f5312783f0b14e0311d5b7d283afef2f00eecbac1d70ab95666e5a73678117023aee15bc004392f4d171ae9abffc",
          "sha256": "ebbe26e697146a08c8269e6be4b5622f5f55a0618e159eb47bc03de3e2f7ca14",
          "sha1": "8fa17a61433da05b4c63bf9502daf5e9bd864564",
          "md5": "bad27ef9b37aaa701dee1ae6d6d1ac85"
        }
      ]
    }
  ]
}
