{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.middle",
    "module": "selector-jar",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.timecat.extend",
          "module": "image",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "readonly",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.page",
          "module": "base",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.layout",
          "module": "ui",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "selector-1.1.0.aar",
          "url": "selector-1.1.0.aar",
          "size": 122423,
          "sha512": "a848b38b335384bca215d05d233b6a3e2a5c3630d42d36b4b49e5ea6b557cedf346f41bdd87d35f75edfc6c2f2fbb7878e0da53cef4c9f16f3daf5006a34beb7",
          "sha256": "f3606c1214df895d781340dca4d9444d3d1c19e7cc4b68db87447fac7dbcf2cf",
          "sha1": "4c027eb61943b689cbe7fcc9b43e351a56a4c1dd",
          "md5": "e2ae6f1df258cb7cb629b1166bf58bdd"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.timecat.extend",
          "module": "image",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "readonly",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.page",
          "module": "base",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.layout",
          "module": "ui",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "selector-1.1.0.aar",
          "url": "selector-1.1.0.aar",
          "size": 122423,
          "sha512": "a848b38b335384bca215d05d233b6a3e2a5c3630d42d36b4b49e5ea6b557cedf346f41bdd87d35f75edfc6c2f2fbb7878e0da53cef4c9f16f3daf5006a34beb7",
          "sha256": "f3606c1214df895d781340dca4d9444d3d1c19e7cc4b68db87447fac7dbcf2cf",
          "sha1": "4c027eb61943b689cbe7fcc9b43e351a56a4c1dd",
          "md5": "e2ae6f1df258cb7cb629b1166bf58bdd"
        }
      ]
    }
  ]
}
