{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.extend",
    "module": "xunfei-jar",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "xunfei-jar-1.0.0.aar",
          "url": "xunfei-jar-1.0.0.aar",
          "size": 3173088,
          "sha512": "a613d49407f3b91d4cc97218d4589b3edaeb600fa5f1b4a1abccfd7fafb0083688363cc5ffac6c72bcdd3199a2c3e19f477285c0dae23dcad1246ddec268d414",
          "sha256": "0d01afa2943dce9988624f2674b3e9eba8cbc39a8d28aa9534dda6956a81a309",
          "sha1": "dd570e7ac5df160e7cdc664a1b1bd4f2ccca8852",
          "md5": "a4ddb8b3c6cc690a9be2918e3013baa1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "xunfei-jar-1.0.0.aar",
          "url": "xunfei-jar-1.0.0.aar",
          "size": 3173088,
          "sha512": "a613d49407f3b91d4cc97218d4589b3edaeb600fa5f1b4a1abccfd7fafb0083688363cc5ffac6c72bcdd3199a2c3e19f477285c0dae23dcad1246ddec268d414",
          "sha256": "0d01afa2943dce9988624f2674b3e9eba8cbc39a8d28aa9534dda6956a81a309",
          "sha1": "dd570e7ac5df160e7cdc664a1b1bd4f2ccca8852",
          "md5": "a4ddb8b3c6cc690a9be2918e3013baa1"
        }
      ]
    }
  ]
}
