{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.middle",
    "module": "download-jar",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.timecat.component",
          "module": "setting",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "readonly",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "download",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "download-1.0.0.aar",
          "url": "download-1.0.0.aar",
          "size": 57167,
          "sha512": "ebb5b7121f8979d8d9c42cc309e2145427e67a97f2b7696789e81ec19c3dfc693997abe2364aa531506a4483d36ea7472f1d46901dadda4eee3f34cd167d5249",
          "sha256": "c7f8bdc9b8fcfcfb189ce320d656fc766f8dd396d5c9379c96d016d3b3e3cb92",
          "sha1": "dc8f4cfc21ba26e82e7d986cd9e9b8bedf72da2b",
          "md5": "63a555eb2cf89a17abd0ed33369d5dd8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.timecat.component",
          "module": "setting",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "readonly",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "download",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "download-1.0.0.aar",
          "url": "download-1.0.0.aar",
          "size": 57167,
          "sha512": "ebb5b7121f8979d8d9c42cc309e2145427e67a97f2b7696789e81ec19c3dfc693997abe2364aa531506a4483d36ea7472f1d46901dadda4eee3f34cd167d5249",
          "sha256": "c7f8bdc9b8fcfcfb189ce320d656fc766f8dd396d5c9379c96d016d3b3e3cb92",
          "sha1": "dc8f4cfc21ba26e82e7d986cd9e9b8bedf72da2b",
          "md5": "63a555eb2cf89a17abd0ed33369d5dd8"
        }
      ]
    }
  ]
}
