{
  "formatVersion": "1.1",
  "component": {
    "group": "GradleDependancyReport",
    "module": "plugin",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "report-1.0.0.jar",
          "url": "report-1.0.0.jar",
          "size": 2165539,
          "sha512": "392e766e2c9f647b2d9087c1055005d78f53a9abdadba10371eb3eba990573a7357632f6c8be6560e90a9df8087eda661ecc79878ba1364a1356cc340a0a041d",
          "sha256": "18421f0e05b9b3b71eca668742c063e919339845dcfe270adf5acf341dd9f7df",
          "sha1": "56c7dd609048b778d4e2f272ee03b1a3121f84c8",
          "md5": "c79618e80c6679bd766467bd466e1591"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "report-1.0.0.jar",
          "url": "report-1.0.0.jar",
          "size": 2165539,
          "sha512": "392e766e2c9f647b2d9087c1055005d78f53a9abdadba10371eb3eba990573a7357632f6c8be6560e90a9df8087eda661ecc79878ba1364a1356cc340a0a041d",
          "sha256": "18421f0e05b9b3b71eca668742c063e919339845dcfe270adf5acf341dd9f7df",
          "sha1": "56c7dd609048b778d4e2f272ee03b1a3121f84c8",
          "md5": "c79618e80c6679bd766467bd466e1591"
        }
      ]
    }
  ]
}
