{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.identity",
    "module": "data-jar",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "joda-time",
          "module": "joda-time",
          "version": {
            "requires": "2.10.10"
          }
        },
        {
          "group": "com.alibaba",
          "module": "fastjson",
          "version": {
            "requires": "1.2.51"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "data-1.1.0.aar",
          "url": "data-1.1.0.aar",
          "size": 358057,
          "sha512": "3c6abe77a3a0698d350ebd0d71c87de732fd29b12c8cca42e55b55103b0998c272948abc06386cda2f32603476c0cbbf154d8e8890d6b91ba4922034aaec1ee0",
          "sha256": "d6e99503464246622b2bdc4eb41bbbd5a60fbb47f4b521f9d5dd375f77b95a85",
          "sha1": "7780576692d6d6cadcc118956e1034f91dd6826e",
          "md5": "fbc52b13d95b9df0ba3398e7d80f442d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "joda-time",
          "module": "joda-time",
          "version": {
            "requires": "2.10.10"
          }
        },
        {
          "group": "com.alibaba",
          "module": "fastjson",
          "version": {
            "requires": "1.2.51"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "data-1.1.0.aar",
          "url": "data-1.1.0.aar",
          "size": 358057,
          "sha512": "3c6abe77a3a0698d350ebd0d71c87de732fd29b12c8cca42e55b55103b0998c272948abc06386cda2f32603476c0cbbf154d8e8890d6b91ba4922034aaec1ee0",
          "sha256": "d6e99503464246622b2bdc4eb41bbbd5a60fbb47f4b521f9d5dd375f77b95a85",
          "sha1": "7780576692d6d6cadcc118956e1034f91dd6826e",
          "md5": "fbc52b13d95b9df0ba3398e7d80f442d"
        }
      ]
    }
  ]
}
