{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.identity",
    "module": "data-jar",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "joda-time",
          "module": "joda-time",
          "version": {
            "requires": "2.10.10"
          }
        },
        {
          "group": "com.alibaba",
          "module": "fastjson",
          "version": {
            "requires": "1.2.51"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "data-1.1.0.aar",
          "url": "data-1.1.0.aar",
          "size": 350228,
          "sha512": "9c8fbf8932edc547d6de6c6841cb9b3311c8cc0b0c69cb3fbf7e70b50d8a6f8943505b1c609221fa5b328ca2006ce25944784e78842abc365085123d041db5a4",
          "sha256": "14353a2af43e0191f583c0b138af486e539ffd7d9bae9ec063348ce06881f563",
          "sha1": "705ad68b36016388f55899d0c0652b8c34731360",
          "md5": "d587e653a1160d6a59a41caf107d0239"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "joda-time",
          "module": "joda-time",
          "version": {
            "requires": "2.10.10"
          }
        },
        {
          "group": "com.alibaba",
          "module": "fastjson",
          "version": {
            "requires": "1.2.51"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "data-1.1.0.aar",
          "url": "data-1.1.0.aar",
          "size": 350228,
          "sha512": "9c8fbf8932edc547d6de6c6841cb9b3311c8cc0b0c69cb3fbf7e70b50d8a6f8943505b1c609221fa5b328ca2006ce25944784e78842abc365085123d041db5a4",
          "sha256": "14353a2af43e0191f583c0b138af486e539ffd7d9bae9ec063348ce06881f563",
          "sha1": "705ad68b36016388f55899d0c0652b8c34731360",
          "md5": "d587e653a1160d6a59a41caf107d0239"
        }
      ]
    }
  ]
}
