{
  "formatVersion": "1.1",
  "component": {
    "group": "com.facebook",
    "module": "jni-jar",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "jni-jar-1.0.0.aar",
          "url": "jni-jar-1.0.0.aar",
          "size": 1191184,
          "sha512": "6380758616596376a75c38eac9e3d4cd66a02271426d7fa14f6e227bd564edc5b692971946492af743afea216a47ff8bedf0f94d8cd263514d710a8a9c1d5656",
          "sha256": "39d7a78aea20948ef4acea2c3e98413e5cd27a0f01d43e310afacd4a76f6239e",
          "sha1": "1e016d68ce1d8cce6cd916a716efc6af16e35942",
          "md5": "ab2e121f1be14ee05deee92b33499310"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "jni-jar-1.0.0.aar",
          "url": "jni-jar-1.0.0.aar",
          "size": 1191184,
          "sha512": "6380758616596376a75c38eac9e3d4cd66a02271426d7fa14f6e227bd564edc5b692971946492af743afea216a47ff8bedf0f94d8cd263514d710a8a9c1d5656",
          "sha256": "39d7a78aea20948ef4acea2c3e98413e5cd27a0f01d43e310afacd4a76f6239e",
          "sha1": "1e016d68ce1d8cce6cd916a716efc6af16e35942",
          "md5": "ab2e121f1be14ee05deee92b33499310"
        }
      ]
    }
  ]
}
