{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.identity",
    "module": "markdown-jar",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "markdown-1.0.0.aar",
          "url": "markdown-1.0.0.aar",
          "size": 95802,
          "sha512": "f477e3559300e1d4fc5426cac4a82d52d73b363719625bd0c1c58e34086ca6b5b1bdc51e80d1eaa659fd05b26fa32b2d558f82a9f811f9544f844b5754ca54c7",
          "sha256": "0bbea7fd283cbbb7faf2e23bc5c65925de5b77f848f2ba3306e701af35245e70",
          "sha1": "bb34fc3a2c07eba960e5ccfb41e882c78a1cbbe2",
          "md5": "c0c7a93b96a8723704575ebff7870f50"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "markdown-1.0.0.aar",
          "url": "markdown-1.0.0.aar",
          "size": 95802,
          "sha512": "f477e3559300e1d4fc5426cac4a82d52d73b363719625bd0c1c58e34086ca6b5b1bdc51e80d1eaa659fd05b26fa32b2d558f82a9f811f9544f844b5754ca54c7",
          "sha256": "0bbea7fd283cbbb7faf2e23bc5c65925de5b77f848f2ba3306e701af35245e70",
          "sha1": "bb34fc3a2c07eba960e5ccfb41e882c78a1cbbe2",
          "md5": "c0c7a93b96a8723704575ebff7870f50"
        }
      ]
    }
  ]
}
