{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.data",
    "module": "room-jar",
    "version": "1.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.timecat.extend",
          "module": "arms",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "setting",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "data",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "joda-time",
          "module": "joda-time",
          "version": {
            "requires": "2.10.10"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "room-1.0.5.aar",
          "url": "room-1.0.5.aar",
          "size": 362195,
          "sha512": "e55d08dbec564a8b62123a5d51808b45f10ba703648ecb3a98875f68a48c8ff98949c1cc4ccad81dc97bff39027f5e2850985cc74f67c96e2d28d0bd95310b7c",
          "sha256": "a7b350e329db9d5c7c1400333d8a83e6557a77715d66eb0118f262ed30c01492",
          "sha1": "e2076bac52d6534b04ef446ed1710f009c82fa78",
          "md5": "4700bcaaef9b14b2ad05ef266919be59"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.timecat.extend",
          "module": "arms",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "setting",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "data",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "joda-time",
          "module": "joda-time",
          "version": {
            "requires": "2.10.10"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "room-1.0.5.aar",
          "url": "room-1.0.5.aar",
          "size": 362195,
          "sha512": "e55d08dbec564a8b62123a5d51808b45f10ba703648ecb3a98875f68a48c8ff98949c1cc4ccad81dc97bff39027f5e2850985cc74f67c96e2d28d0bd95310b7c",
          "sha256": "a7b350e329db9d5c7c1400333d8a83e6557a77715d66eb0118f262ed30c01492",
          "sha1": "e2076bac52d6534b04ef446ed1710f009c82fa78",
          "md5": "4700bcaaef9b14b2ad05ef266919be59"
        }
      ]
    }
  ]
}
