{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.data",
    "module": "room-jar",
    "version": "1.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.timecat.extend",
          "module": "arms",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "setting",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "data",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "joda-time",
          "module": "joda-time",
          "version": {
            "requires": "2.10.10"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "room-1.0.5.aar",
          "url": "room-1.0.5.aar",
          "size": 360347,
          "sha512": "f2561e52d8659f752b469aa450e1c2ff4ed08d8df4cd71315bfa050fc501a8137c470ce692ad7dcfdbf31769770b0d99ccf7110155efdf49d168878a59f32e96",
          "sha256": "ef9f91575151a58f6d6c846f12795a856b688441dffb22fd479d44dba80ea83f",
          "sha1": "4ac0bbfb2448c417c5892199be78a3f11593ba1c",
          "md5": "e82aafe008d2c81f816c5fd8ffe7015f"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.timecat.extend",
          "module": "arms",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "setting",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "data",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "joda-time",
          "module": "joda-time",
          "version": {
            "requires": "2.10.10"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "room-1.0.5.aar",
          "url": "room-1.0.5.aar",
          "size": 360347,
          "sha512": "f2561e52d8659f752b469aa450e1c2ff4ed08d8df4cd71315bfa050fc501a8137c470ce692ad7dcfdbf31769770b0d99ccf7110155efdf49d168878a59f32e96",
          "sha256": "ef9f91575151a58f6d6c846f12795a856b688441dffb22fd479d44dba80ea83f",
          "sha1": "4ac0bbfb2448c417c5892199be78a3f11593ba1c",
          "md5": "e82aafe008d2c81f816c5fd8ffe7015f"
        }
      ]
    }
  ]
}
