{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.shared",
    "module": "plugin-host-jar",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "router",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-host-1.0.0.aar",
          "url": "plugin-host-1.0.0.aar",
          "size": 18911,
          "sha512": "8e80662d93391242748b9bdbe312c09877f28ae4bf1f08b58e4557f73aee3a9e705fcfdb9d09aa3809491374492ae17f21eb5579dc2d63d56451c2b398f811e6",
          "sha256": "dc7600f3a4cac9ca43ceecbf4ac5376a26dc4b0e385100a97d7830449b09b2b7",
          "sha1": "6f06cba8320d949bd8271bbe3ecdeb78de95630e",
          "md5": "4605b003812609e02b111ca62f32cc1f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "router",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-host-1.0.0.aar",
          "url": "plugin-host-1.0.0.aar",
          "size": 18911,
          "sha512": "8e80662d93391242748b9bdbe312c09877f28ae4bf1f08b58e4557f73aee3a9e705fcfdb9d09aa3809491374492ae17f21eb5579dc2d63d56451c2b398f811e6",
          "sha256": "dc7600f3a4cac9ca43ceecbf4ac5376a26dc4b0e385100a97d7830449b09b2b7",
          "sha1": "6f06cba8320d949bd8271bbe3ecdeb78de95630e",
          "md5": "4605b003812609e02b111ca62f32cc1f"
        }
      ]
    }
  ]
}
