{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.middle",
    "module": "record-ext-jar",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "block",
          "version": {
            "requires": "+"
          }
        }
      ],
      "files": [
        {
          "name": "record-ext-1.0.0.aar",
          "url": "record-ext-1.0.0.aar",
          "size": 100840,
          "sha512": "348a91025a9b2bb9a6646cc65a8d9d3439a977942ee2a7804f8cb7f3503b89d409f4bc6510cffa053c7aec1de7fb00169abda364f1f0efe1209fe1f3881c1cc0",
          "sha256": "c21b66fa777a9fcc4bd1be9a35f9e8e29ba947d81f0ba73ed478d9a50bbecfdc",
          "sha1": "8afa42718f8d10205469482d5a009abe90565e29",
          "md5": "77712d2746b2d7b3e453920d6e1ea40a"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "block",
          "version": {
            "requires": "+"
          }
        }
      ],
      "files": [
        {
          "name": "record-ext-1.0.0.aar",
          "url": "record-ext-1.0.0.aar",
          "size": 100840,
          "sha512": "348a91025a9b2bb9a6646cc65a8d9d3439a977942ee2a7804f8cb7f3503b89d409f4bc6510cffa053c7aec1de7fb00169abda364f1f0efe1209fe1f3881c1cc0",
          "sha256": "c21b66fa777a9fcc4bd1be9a35f9e8e29ba947d81f0ba73ed478d9a50bbecfdc",
          "sha1": "8afa42718f8d10205469482d5a009abe90565e29",
          "md5": "77712d2746b2d7b3e453920d6e1ea40a"
        }
      ]
    }
  ]
}
