{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.middle",
    "module": "record-ext-jar",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "block",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "record-ext-1.0.0.aar",
          "url": "record-ext-1.0.0.aar",
          "size": 119148,
          "sha512": "27a702284c1a7fa93fde87ec01e933acd61143417c5c3b345dbd2e4474c47361226526e93eace936c1d838c2a1bb2cfd9ddf97b7848fe8722bc6b12ce35aae1b",
          "sha256": "dc92db41d3e070764d5d8149c443efd21bab1354d27c06311f87f826d1dc1088",
          "sha1": "24b59557b85f0363a806db22766dda9a4429808c",
          "md5": "a6014053f98070eb9bb9ee30c172ac59"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "block",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "record-ext-1.0.0.aar",
          "url": "record-ext-1.0.0.aar",
          "size": 119148,
          "sha512": "27a702284c1a7fa93fde87ec01e933acd61143417c5c3b345dbd2e4474c47361226526e93eace936c1d838c2a1bb2cfd9ddf97b7848fe8722bc6b12ce35aae1b",
          "sha256": "dc92db41d3e070764d5d8149c443efd21bab1354d27c06311f87f826d1dc1088",
          "sha1": "24b59557b85f0363a806db22766dda9a4429808c",
          "md5": "a6014053f98070eb9bb9ee30c172ac59"
        }
      ]
    }
  ]
}
