{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.middle",
    "module": "record-ext-jar",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "block",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "record-ext-1.0.0.aar",
          "url": "record-ext-1.0.0.aar",
          "size": 117493,
          "sha512": "c04519aecc355139caebd206341d3fb79986bec9a387838e39ed1f5f811600c10b5201a092b51ac941e9b131cb4a5bfd5c5f379aca20cfc778f0099da16da267",
          "sha256": "9d430cc6efd4d90e9961c8503afa72ff5b56aa84c64f5e54e28c577fddb29892",
          "sha1": "1440e9c32f93eb48b8505c322cf35151a96fa04e",
          "md5": "6dd14688e9ecd580e59fb95d75ebbe1d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "block",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "record-ext-1.0.0.aar",
          "url": "record-ext-1.0.0.aar",
          "size": 117493,
          "sha512": "c04519aecc355139caebd206341d3fb79986bec9a387838e39ed1f5f811600c10b5201a092b51ac941e9b131cb4a5bfd5c5f379aca20cfc778f0099da16da267",
          "sha256": "9d430cc6efd4d90e9961c8503afa72ff5b56aa84c64f5e54e28c577fddb29892",
          "sha1": "1440e9c32f93eb48b8505c322cf35151a96fa04e",
          "md5": "6dd14688e9ecd580e59fb95d75ebbe1d"
        }
      ]
    }
  ]
}
