{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.module",
    "module": "module-user-jar",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "block",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "form",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "selector",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.data",
          "module": "bmob",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "readonly",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.layout",
          "module": "ui",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "service",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "router",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.makeramen",
          "module": "roundedimageview",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.akexorcist",
          "module": "round-corner-progress-bar",
          "version": {
            "requires": "2.1.2"
          }
        },
        {
          "group": "com.github.CarGuo.RickText",
          "module": "textUtilsLib",
          "version": {
            "requires": "v2.1.5"
          }
        },
        {
          "group": "com.github.razerdp",
          "module": "PhotoContents",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.github.razir.progressbutton",
          "module": "progressbutton",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.github.chengzhicao",
          "module": "ChannelView",
          "version": {
            "requires": "v1.1.0"
          }
        },
        {
          "group": "com.effective.android",
          "module": "panelSwitchHelper-androidx",
          "version": {
            "requires": "1.3.13"
          }
        }
      ],
      "files": [
        {
          "name": "module-user-1.1.0.aar",
          "url": "module-user-1.1.0.aar",
          "size": 3249205,
          "sha512": "e0c27473a30c877355c336543143839098d1f9828889b6d6b974f05b8d0c2d016609be793f0a12a46d1c098070ab01db9427a90a519f1533ab53af4d74ca859a",
          "sha256": "1b50fbcad98b8cdf4abcffd98c3434064c57f15d8ee8d9c3dd00210c01bd5834",
          "sha1": "ba781399997c9eb5286fd5bfad4ec3ca42bdf0c6",
          "md5": "68d1ea7eb92cf850de1ec6ed726f9b00"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "block",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "form",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "selector",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.data",
          "module": "bmob",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "readonly",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.layout",
          "module": "ui",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "service",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "router",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.makeramen",
          "module": "roundedimageview",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.akexorcist",
          "module": "round-corner-progress-bar",
          "version": {
            "requires": "2.1.2"
          }
        },
        {
          "group": "com.github.CarGuo.RickText",
          "module": "textUtilsLib",
          "version": {
            "requires": "v2.1.5"
          }
        },
        {
          "group": "com.github.razerdp",
          "module": "PhotoContents",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.github.razir.progressbutton",
          "module": "progressbutton",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.github.chengzhicao",
          "module": "ChannelView",
          "version": {
            "requires": "v1.1.0"
          }
        },
        {
          "group": "com.effective.android",
          "module": "panelSwitchHelper-androidx",
          "version": {
            "requires": "1.3.13"
          }
        }
      ],
      "files": [
        {
          "name": "module-user-1.1.0.aar",
          "url": "module-user-1.1.0.aar",
          "size": 3249205,
          "sha512": "e0c27473a30c877355c336543143839098d1f9828889b6d6b974f05b8d0c2d016609be793f0a12a46d1c098070ab01db9427a90a519f1533ab53af4d74ca859a",
          "sha256": "1b50fbcad98b8cdf4abcffd98c3434064c57f15d8ee8d9c3dd00210c01bd5834",
          "sha1": "ba781399997c9eb5286fd5bfad4ec3ca42bdf0c6",
          "md5": "68d1ea7eb92cf850de1ec6ed726f9b00"
        }
      ]
    }
  ]
}
