{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.module",
    "module": "module-user-jar",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "block",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "form",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "selector",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.data",
          "module": "bmob",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "readonly",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.layout",
          "module": "ui",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "service",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "router",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.makeramen",
          "module": "roundedimageview",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.akexorcist",
          "module": "round-corner-progress-bar",
          "version": {
            "requires": "2.1.2"
          }
        },
        {
          "group": "com.github.CarGuo.RickText",
          "module": "textUtilsLib",
          "version": {
            "requires": "v2.1.5"
          }
        },
        {
          "group": "com.github.razerdp",
          "module": "PhotoContents",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.github.razir.progressbutton",
          "module": "progressbutton",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.github.chengzhicao",
          "module": "ChannelView",
          "version": {
            "requires": "v1.1.0"
          }
        },
        {
          "group": "com.effective.android",
          "module": "panelSwitchHelper-androidx",
          "version": {
            "requires": "1.3.13"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "module-user-1.1.0.aar",
          "url": "module-user-1.1.0.aar",
          "size": 3396288,
          "sha512": "6fa087aa2a516f3442a07d5ea073ff95eff58f1323160d36fc889d1adea9a9f607d0c93a146375cfec43d1409854fc538b3f60db349114e378652a26c0b25cdb",
          "sha256": "2eb405cc6c65c23d5f65c82be077cb2febc851a55a32034d84e655cf64f707ee",
          "sha1": "4d19317b6fa425ff811bb125b9be75956ecec07e",
          "md5": "5483af500877e5de3259a0c76c6e681c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "block",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "form",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "selector",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.data",
          "module": "bmob",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "readonly",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.layout",
          "module": "ui",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "service",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "router",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.makeramen",
          "module": "roundedimageview",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.akexorcist",
          "module": "round-corner-progress-bar",
          "version": {
            "requires": "2.1.2"
          }
        },
        {
          "group": "com.github.CarGuo.RickText",
          "module": "textUtilsLib",
          "version": {
            "requires": "v2.1.5"
          }
        },
        {
          "group": "com.github.razerdp",
          "module": "PhotoContents",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.github.razir.progressbutton",
          "module": "progressbutton",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.github.chengzhicao",
          "module": "ChannelView",
          "version": {
            "requires": "v1.1.0"
          }
        },
        {
          "group": "com.effective.android",
          "module": "panelSwitchHelper-androidx",
          "version": {
            "requires": "1.3.13"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "module-user-1.1.0.aar",
          "url": "module-user-1.1.0.aar",
          "size": 3396288,
          "sha512": "6fa087aa2a516f3442a07d5ea073ff95eff58f1323160d36fc889d1adea9a9f607d0c93a146375cfec43d1409854fc538b3f60db349114e378652a26c0b25cdb",
          "sha256": "2eb405cc6c65c23d5f65c82be077cb2febc851a55a32034d84e655cf64f707ee",
          "sha1": "4d19317b6fa425ff811bb125b9be75956ecec07e",
          "md5": "5483af500877e5de3259a0c76c6e681c"
        }
      ]
    }
  ]
}
