{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.page",
    "module": "dialog-jar",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.timecat.page",
          "module": "scene",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.page",
          "module": "navigation",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "dialog-jar-1.0.1.aar",
          "url": "dialog-jar-1.0.1.aar",
          "size": 67728,
          "sha512": "8f4b39777d3df9a85fda71a2c9a999ed1d507cbff15766b7b80fa1949440e995cf1010395eecf3a0ba82e62a05601261ab5395d7def6769580d655c20b9f03f8",
          "sha256": "009c5f85151b7955130a9746ece238915bca7c501756c6d7eaf0f0414542e965",
          "sha1": "c4c64964b98890c091c4a9f69b74fc8726df6348",
          "md5": "c75dfa34b7b1a69fa82f5e4b27553671"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.timecat.page",
          "module": "scene",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.page",
          "module": "navigation",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "dialog-jar-1.0.1.aar",
          "url": "dialog-jar-1.0.1.aar",
          "size": 67728,
          "sha512": "8f4b39777d3df9a85fda71a2c9a999ed1d507cbff15766b7b80fa1949440e995cf1010395eecf3a0ba82e62a05601261ab5395d7def6769580d655c20b9f03f8",
          "sha256": "009c5f85151b7955130a9746ece238915bca7c501756c6d7eaf0f0414542e965",
          "sha1": "c4c64964b98890c091c4a9f69b74fc8726df6348",
          "md5": "c75dfa34b7b1a69fa82f5e4b27553671"
        }
      ]
    }
  ]
}
