{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.middle",
    "module": "record-ext-jar",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "block",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "record-ext-jar-1.0.0.aar",
          "url": "record-ext-jar-1.0.0.aar",
          "size": 119153,
          "sha512": "07d3113db2e28f791f1591494c35afe9ed4fe3eec93031c38004d440f70b494e04feb838e141d97f46a223532df9faa6a440db16506fc9619f3aac1f627900dd",
          "sha256": "b0e7e73d6655c745f2ab0aa12e3125bc8282c40d506eb8153e704c08f03d6898",
          "sha1": "b4d0173579b6e748805b9bfa0ca5773f2459e93e",
          "md5": "5f0b9f8951947a5cd04912e005fd34a7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "block",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "record-ext-jar-1.0.0.aar",
          "url": "record-ext-jar-1.0.0.aar",
          "size": 119153,
          "sha512": "07d3113db2e28f791f1591494c35afe9ed4fe3eec93031c38004d440f70b494e04feb838e141d97f46a223532df9faa6a440db16506fc9619f3aac1f627900dd",
          "sha256": "b0e7e73d6655c745f2ab0aa12e3125bc8282c40d506eb8153e704c08f03d6898",
          "sha1": "b4d0173579b6e748805b9bfa0ca5773f2459e93e",
          "md5": "5f0b9f8951947a5cd04912e005fd34a7"
        }
      ]
    }
  ]
}
