{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.extend",
    "module": "image-preview-jar",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "com.davemorrissey.labs",
          "module": "subsampling-scale-image-view",
          "version": {
            "requires": "3.10.0"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "okhttp3-integration",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "image-preview-jar-1.0.0.aar",
          "url": "image-preview-jar-1.0.0.aar",
          "size": 228325,
          "sha512": "3d55c2f36d2c4e531ba7e4e702e57d84d92b7cf6f408ec34af9ef77601b3ed37724a553bd54056f09266f46c4a420e5eedde6852ed2f91866872856e04459584",
          "sha256": "37fb32fb9ca817503287f415b0dad24ae2fc627e973abe101b4801ba80543de1",
          "sha1": "f356ce2b370bb32fd7369a21840d9962726eb2ed",
          "md5": "95f64f178ffb35d3e46194e1189cc7b6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "com.davemorrissey.labs",
          "module": "subsampling-scale-image-view",
          "version": {
            "requires": "3.10.0"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "okhttp3-integration",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "image-preview-jar-1.0.0.aar",
          "url": "image-preview-jar-1.0.0.aar",
          "size": 228325,
          "sha512": "3d55c2f36d2c4e531ba7e4e702e57d84d92b7cf6f408ec34af9ef77601b3ed37724a553bd54056f09266f46c4a420e5eedde6852ed2f91866872856e04459584",
          "sha256": "37fb32fb9ca817503287f415b0dad24ae2fc627e973abe101b4801ba80543de1",
          "sha1": "f356ce2b370bb32fd7369a21840d9962726eb2ed",
          "md5": "95f64f178ffb35d3e46194e1189cc7b6"
        }
      ]
    }
  ]
}
