{
  "formatVersion": "1.1",
  "component": {
    "group": "skin.support",
    "module": "skin-support-appcompat-jar",
    "version": "4.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "skin-support-appcompat-4.0.6.aar",
          "url": "skin-support-appcompat-4.0.6.aar",
          "size": 98972,
          "sha512": "de85d457df6bb586553baacdc529ea3a8c0d31b23d3aff6cb99b3eb31d3882ec87c84d68cdb9b2e6b7c50eb90d2801bf54f017cba7d65724033e99ae3df9a69c",
          "sha256": "6814ec014b91760303ab18613bfad9abc943228e8ff1604381890e739aa71136",
          "sha1": "085cf0969d31a3b2b5805cea58bf8c2662475357",
          "md5": "7afd2724e47bc1651a3485276336613f"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "skin-support-appcompat-4.0.6.aar",
          "url": "skin-support-appcompat-4.0.6.aar",
          "size": 98972,
          "sha512": "de85d457df6bb586553baacdc529ea3a8c0d31b23d3aff6cb99b3eb31d3882ec87c84d68cdb9b2e6b7c50eb90d2801bf54f017cba7d65724033e99ae3df9a69c",
          "sha256": "6814ec014b91760303ab18613bfad9abc943228e8ff1604381890e739aa71136",
          "sha1": "085cf0969d31a3b2b5805cea58bf8c2662475357",
          "md5": "7afd2724e47bc1651a3485276336613f"
        }
      ]
    }
  ]
}
