{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.module",
    "module": "module-scarlet-jar",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.timecat.extend",
          "module": "markdown",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "block",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "form",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.github.bijoysingh",
          "module": "android-basics",
          "version": {
            "requires": "5.1.0-x"
          }
        },
        {
          "group": "com.github.bijoysingh",
          "module": "ui-basics",
          "version": {
            "requires": "1.0.0-x"
          }
        },
        {
          "group": "com.github.bijoysingh",
          "module": "floating-bubble",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.evernote",
          "module": "android-job",
          "version": {
            "requires": "1.2.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.facebook.litho",
          "module": "litho-core",
          "version": {
            "requires": "0.31.0"
          }
        },
        {
          "group": "com.facebook.litho",
          "module": "litho-widget",
          "version": {
            "requires": "0.31.0"
          }
        },
        {
          "group": "com.facebook.soloader",
          "module": "soloader",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "module-scarlet-1.1.0.aar",
          "url": "module-scarlet-1.1.0.aar",
          "size": 3447523,
          "sha512": "640e7ed81d15ff48ad973b80df640398afa4320e60a1835269931a8393ab5b84546de5d2dff4c16cdbc8ad326c1c4abd9a5bd13e6a185739265aa29eb2a8e480",
          "sha256": "41ce517f9be255829586a3e81d37a258ab0c2cbbefbe08a262ed53b35ac7171c",
          "sha1": "360f687e3e39bb74d7416ac55948152ad39745a2",
          "md5": "5e1dc5d9179af0338c005ffb615a382e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.timecat.extend",
          "module": "markdown",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "block",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "form",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.github.bijoysingh",
          "module": "android-basics",
          "version": {
            "requires": "5.1.0-x"
          }
        },
        {
          "group": "com.github.bijoysingh",
          "module": "ui-basics",
          "version": {
            "requires": "1.0.0-x"
          }
        },
        {
          "group": "com.github.bijoysingh",
          "module": "floating-bubble",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.evernote",
          "module": "android-job",
          "version": {
            "requires": "1.2.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.facebook.litho",
          "module": "litho-core",
          "version": {
            "requires": "0.31.0"
          }
        },
        {
          "group": "com.facebook.litho",
          "module": "litho-widget",
          "version": {
            "requires": "0.31.0"
          }
        },
        {
          "group": "com.facebook.soloader",
          "module": "soloader",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "com.google.android",
          "module": "flexbox",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.github.jkwiecien",
          "module": "EasyImage",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "module-scarlet-1.1.0.aar",
          "url": "module-scarlet-1.1.0.aar",
          "size": 3447523,
          "sha512": "640e7ed81d15ff48ad973b80df640398afa4320e60a1835269931a8393ab5b84546de5d2dff4c16cdbc8ad326c1c4abd9a5bd13e6a185739265aa29eb2a8e480",
          "sha256": "41ce517f9be255829586a3e81d37a258ab0c2cbbefbe08a262ed53b35ac7171c",
          "sha1": "360f687e3e39bb74d7416ac55948152ad39745a2",
          "md5": "5e1dc5d9179af0338c005ffb615a382e"
        }
      ]
    }
  ]
}
