{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.module",
    "module": "module-master-jar",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "block",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "form",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "selector",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "font",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "readonly",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "sdk",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "data",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.data",
          "module": "room",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "MView-same",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "MView-font",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "MLang",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "com.timecat.widget",
          "module": "board",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.widget",
          "module": "table",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.github.chengzhicao",
          "module": "ChannelView",
          "version": {
            "requires": "v1.1.0"
          }
        },
        {
          "group": "com.otaliastudios",
          "module": "autocomplete",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "xyz.aprildown",
          "module": "HmsPickerView",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.akexorcist",
          "module": "round-corner-progress-bar",
          "version": {
            "requires": "2.1.2"
          }
        },
        {
          "group": "com.github.iwgang",
          "module": "countdownview",
          "version": {
            "requires": "2.1.6"
          }
        },
        {
          "group": "io.github.razerdp",
          "module": "BasePopup",
          "version": {
            "requires": "3.1.4"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.mikepenz",
          "module": "materialdrawer",
          "version": {
            "requires": "8.0.3"
          }
        },
        {
          "group": "com.flyco.roundview",
          "module": "FlycoRoundView_Lib",
          "version": {
            "requires": "1.1.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "FlycoRoundView_Lib",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "com.github.florent37",
          "module": "viewtooltip",
          "version": {
            "requires": "1.1.8"
          }
        },
        {
          "group": "com.getkeepsafe.taptargetview",
          "module": "taptargetview",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.effective.android",
          "module": "panelSwitchHelper-androidx",
          "version": {
            "requires": "1.3.13"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "module-master-1.1.0.aar",
          "url": "module-master-1.1.0.aar",
          "size": 4389642,
          "sha512": "266f8505d671735dbd094544d0d0ec61540f646d72c268d1395d8e39bc21aaa22e3e21ae7190b313e7b0bfae81e5823be874827ba97881ee088ee5c519e75b83",
          "sha256": "5bbf07382e1a01b157a2f094c3ed53cb8d83e0311d94aa9ec4199e82bf891b8e",
          "sha1": "579df81da52caeb5ee0fbbe631aa40741d407522",
          "md5": "825da4f8e7fde57a6a5682ede0aa764d"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "block",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "form",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "selector",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "font",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "readonly",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "sdk",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "data",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.data",
          "module": "room",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "MView-same",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "MView-font",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "MLang",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "com.timecat.widget",
          "module": "board",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.widget",
          "module": "table",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.github.chengzhicao",
          "module": "ChannelView",
          "version": {
            "requires": "v1.1.0"
          }
        },
        {
          "group": "com.otaliastudios",
          "module": "autocomplete",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "xyz.aprildown",
          "module": "HmsPickerView",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.akexorcist",
          "module": "round-corner-progress-bar",
          "version": {
            "requires": "2.1.2"
          }
        },
        {
          "group": "com.github.iwgang",
          "module": "countdownview",
          "version": {
            "requires": "2.1.6"
          }
        },
        {
          "group": "io.github.razerdp",
          "module": "BasePopup",
          "version": {
            "requires": "3.1.4"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.mikepenz",
          "module": "materialdrawer",
          "version": {
            "requires": "8.0.3"
          }
        },
        {
          "group": "com.flyco.roundview",
          "module": "FlycoRoundView_Lib",
          "version": {
            "requires": "1.1.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "FlycoRoundView_Lib",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "com.github.florent37",
          "module": "viewtooltip",
          "version": {
            "requires": "1.1.8"
          }
        },
        {
          "group": "com.getkeepsafe.taptargetview",
          "module": "taptargetview",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.effective.android",
          "module": "panelSwitchHelper-androidx",
          "version": {
            "requires": "1.3.13"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "module-master-1.1.0.aar",
          "url": "module-master-1.1.0.aar",
          "size": 4389642,
          "sha512": "266f8505d671735dbd094544d0d0ec61540f646d72c268d1395d8e39bc21aaa22e3e21ae7190b313e7b0bfae81e5823be874827ba97881ee088ee5c519e75b83",
          "sha256": "5bbf07382e1a01b157a2f094c3ed53cb8d83e0311d94aa9ec4199e82bf891b8e",
          "sha1": "579df81da52caeb5ee0fbbe631aa40741d407522",
          "md5": "825da4f8e7fde57a6a5682ede0aa764d"
        }
      ]
    }
  ]
}
