{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.module",
    "module": "module-master-jar",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "block",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "form",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "selector",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "font",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "readonly",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "sdk",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "data",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.data",
          "module": "room",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "MView-same",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "MView-font",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "MLang",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "text",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "record-ext",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.widget",
          "module": "board",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.widget",
          "module": "table",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.github.chengzhicao",
          "module": "ChannelView",
          "version": {
            "requires": "v1.1.0"
          }
        },
        {
          "group": "com.otaliastudios",
          "module": "autocomplete",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.akexorcist",
          "module": "round-corner-progress-bar",
          "version": {
            "requires": "2.1.2"
          }
        },
        {
          "group": "com.github.iwgang",
          "module": "countdownview",
          "version": {
            "requires": "2.1.6"
          }
        },
        {
          "group": "io.github.razerdp",
          "module": "BasePopup",
          "version": {
            "requires": "3.1.4"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.media",
          "module": "media",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.mikepenz",
          "module": "materialdrawer",
          "version": {
            "requires": "8.0.3"
          }
        },
        {
          "group": "com.flyco.roundview",
          "module": "FlycoRoundView_Lib",
          "version": {
            "requires": "1.1.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "FlycoRoundView_Lib",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "com.github.florent37",
          "module": "viewtooltip",
          "version": {
            "requires": "1.1.8"
          }
        },
        {
          "group": "com.effective.android",
          "module": "panelSwitchHelper-androidx",
          "version": {
            "requires": "1.3.13"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "module-master-1.1.0.aar",
          "url": "module-master-1.1.0.aar",
          "size": 3829650,
          "sha512": "37adff97b4e5903e07dbc7d1b3d60be1b4690b7f260f61e7f54438f384397cda91bc5e2fc34339aad0b0d87a8a378bacc21b6606ea6030118067c8461935d186",
          "sha256": "d80dd54c99f223db31b8a3fbf7281eb7fca1bdc76f250a20069d3e4b8f019beb",
          "sha1": "7947c5209c5833d534d198ccf85ca1efb85ec38a",
          "md5": "2a9f8d72196abb024d92d87f918a5c02"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "block",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "form",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "selector",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "font",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "readonly",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "sdk",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "data",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.data",
          "module": "room",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "MView-same",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "MView-font",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "MLang",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "text",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "record-ext",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.widget",
          "module": "board",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.widget",
          "module": "table",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.github.chengzhicao",
          "module": "ChannelView",
          "version": {
            "requires": "v1.1.0"
          }
        },
        {
          "group": "com.otaliastudios",
          "module": "autocomplete",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.akexorcist",
          "module": "round-corner-progress-bar",
          "version": {
            "requires": "2.1.2"
          }
        },
        {
          "group": "com.github.iwgang",
          "module": "countdownview",
          "version": {
            "requires": "2.1.6"
          }
        },
        {
          "group": "io.github.razerdp",
          "module": "BasePopup",
          "version": {
            "requires": "3.1.4"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.media",
          "module": "media",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.mikepenz",
          "module": "materialdrawer",
          "version": {
            "requires": "8.0.3"
          }
        },
        {
          "group": "com.flyco.roundview",
          "module": "FlycoRoundView_Lib",
          "version": {
            "requires": "1.1.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "FlycoRoundView_Lib",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "com.github.florent37",
          "module": "viewtooltip",
          "version": {
            "requires": "1.1.8"
          }
        },
        {
          "group": "com.effective.android",
          "module": "panelSwitchHelper-androidx",
          "version": {
            "requires": "1.3.13"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "module-master-1.1.0.aar",
          "url": "module-master-1.1.0.aar",
          "size": 3829650,
          "sha512": "37adff97b4e5903e07dbc7d1b3d60be1b4690b7f260f61e7f54438f384397cda91bc5e2fc34339aad0b0d87a8a378bacc21b6606ea6030118067c8461935d186",
          "sha256": "d80dd54c99f223db31b8a3fbf7281eb7fca1bdc76f250a20069d3e4b8f019beb",
          "sha1": "7947c5209c5833d534d198ccf85ca1efb85ec38a",
          "md5": "2a9f8d72196abb024d92d87f918a5c02"
        }
      ]
    }
  ]
}
