{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.component",
    "module": "engine-js-jar",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.facebook",
          "module": "jni",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "engine-js-jar-1.0.0.aar",
          "url": "engine-js-jar-1.0.0.aar",
          "size": 8890831,
          "sha512": "f8f5cdaeaf091b17b78ac752daea34db77e181ce7b14c7cd9f2a0ed9efee56f0e63fbe7d35c31a94f5879bc4b74bb1ad1dcde2120976bc89b478b830a2b7c864",
          "sha256": "f035a963d024e241bf6438908ed7e9f192a9c7f4c918aac3fa14c669113cdc39",
          "sha1": "61b2e649df9e0a642a72c5df33adbbc81c973f9f",
          "md5": "6f935a9d92851b4c61ded29714000eb8"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.facebook",
          "module": "jni",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "engine-js-jar-1.0.0.aar",
          "url": "engine-js-jar-1.0.0.aar",
          "size": 8890831,
          "sha512": "f8f5cdaeaf091b17b78ac752daea34db77e181ce7b14c7cd9f2a0ed9efee56f0e63fbe7d35c31a94f5879bc4b74bb1ad1dcde2120976bc89b478b830a2b7c864",
          "sha256": "f035a963d024e241bf6438908ed7e9f192a9c7f4c918aac3fa14c669113cdc39",
          "sha1": "61b2e649df9e0a642a72c5df33adbbc81c973f9f",
          "md5": "6f935a9d92851b4c61ded29714000eb8"
        }
      ]
    }
  ]
}
