{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.element",
    "module": "listview-jar",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "eu.davidea",
          "module": "flexible-adapter",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "eu.davidea",
          "module": "flexible-adapter-ui",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "listview-1.0.0.aar",
          "url": "listview-1.0.0.aar",
          "size": 18607,
          "sha512": "90fd637a3fa49fd9725f6d32722944ee3e2838cd3740d2808da5bf5cc4954e2997f5a8a318c4b4c5649321c9ce666ff55d657907521b2116fc3c1e956dbb5a74",
          "sha256": "2063e5f43bd1753ee5d03ecccb0ac1b9804bc3e154462f598160564718562d68",
          "sha1": "6d87e8dcce2061bdb5cebd54efd7dca81a497cf3",
          "md5": "33b456de931b4f2b8cc6ea4122e1d3c2"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "eu.davidea",
          "module": "flexible-adapter",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "eu.davidea",
          "module": "flexible-adapter-ui",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "listview-1.0.0.aar",
          "url": "listview-1.0.0.aar",
          "size": 18607,
          "sha512": "90fd637a3fa49fd9725f6d32722944ee3e2838cd3740d2808da5bf5cc4954e2997f5a8a318c4b4c5649321c9ce666ff55d657907521b2116fc3c1e956dbb5a74",
          "sha256": "2063e5f43bd1753ee5d03ecccb0ac1b9804bc3e154462f598160564718562d68",
          "sha1": "6d87e8dcce2061bdb5cebd54efd7dca81a497cf3",
          "md5": "33b456de931b4f2b8cc6ea4122e1d3c2"
        }
      ]
    }
  ]
}
