{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.component",
    "module": "sdk-jar",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.timecat.extend",
          "module": "arms",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "font",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0-alpha01"
          }
        },
        {
          "group": "com.jaredrummler",
          "module": "android-device-names",
          "version": {
            "requires": "1.1.5"
          }
        },
        {
          "group": "com.blankj",
          "module": "utilcodex",
          "version": {
            "requires": "1.30.1"
          }
        },
        {
          "group": "joda-time",
          "module": "joda-time",
          "version": {
            "requires": "2.10.10"
          }
        },
        {
          "group": "io.reactivex",
          "module": "rxandroid",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "me.jessyan",
          "module": "retrofit-url-manager",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.12.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "support-v4"
            }
          ]
        },
        {
          "group": "com.umeng.umsdk",
          "module": "common",
          "version": {
            "requires": "9.4.2"
          }
        },
        {
          "group": "com.umeng.umsdk",
          "module": "asms",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.umeng.umsdk",
          "module": "apm",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-jar-1.1.0.aar",
          "url": "sdk-jar-1.1.0.aar",
          "size": 382219,
          "sha512": "6e7077caebc03e5870a055516b3f9e7114d80309f7189b6e68d61c513c51fded94dbffbb0c59c00591829b2d1c47f3e69c80375322caa81c2b40bb8f627e0203",
          "sha256": "88e8a7cd6c886ba84fc2c201a5e404e79b48eee2c810bb3c1d6a29b21ccfd2d6",
          "sha1": "fb1ce79872a9ce40ce3cab575c2c5fb6f99cf9a5",
          "md5": "39c16bc7a2bff4a696f4e960e4472608"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.timecat.extend",
          "module": "arms",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "font",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0-alpha01"
          }
        },
        {
          "group": "com.jaredrummler",
          "module": "android-device-names",
          "version": {
            "requires": "1.1.5"
          }
        },
        {
          "group": "com.blankj",
          "module": "utilcodex",
          "version": {
            "requires": "1.30.1"
          }
        },
        {
          "group": "joda-time",
          "module": "joda-time",
          "version": {
            "requires": "2.10.10"
          }
        },
        {
          "group": "io.reactivex",
          "module": "rxandroid",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "me.jessyan",
          "module": "retrofit-url-manager",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.12.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "support-v4"
            }
          ]
        },
        {
          "group": "com.umeng.umsdk",
          "module": "common",
          "version": {
            "requires": "9.4.2"
          }
        },
        {
          "group": "com.umeng.umsdk",
          "module": "asms",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.umeng.umsdk",
          "module": "apm",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-jar-1.1.0.aar",
          "url": "sdk-jar-1.1.0.aar",
          "size": 382219,
          "sha512": "6e7077caebc03e5870a055516b3f9e7114d80309f7189b6e68d61c513c51fded94dbffbb0c59c00591829b2d1c47f3e69c80375322caa81c2b40bb8f627e0203",
          "sha256": "88e8a7cd6c886ba84fc2c201a5e404e79b48eee2c810bb3c1d6a29b21ccfd2d6",
          "sha1": "fb1ce79872a9ce40ce3cab575c2c5fb6f99cf9a5",
          "md5": "39c16bc7a2bff4a696f4e960e4472608"
        }
      ]
    }
  ]
}
