{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.component",
    "module": "sdk-jar",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.timecat.extend",
          "module": "arms",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "font",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.jaredrummler",
          "module": "android-device-names",
          "version": {
            "requires": "1.1.5"
          }
        },
        {
          "group": "com.blankj",
          "module": "utilcodex",
          "version": {
            "requires": "1.30.1"
          }
        },
        {
          "group": "joda-time",
          "module": "joda-time",
          "version": {
            "requires": "2.10.10"
          }
        },
        {
          "group": "io.reactivex",
          "module": "rxandroid",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "me.jessyan",
          "module": "retrofit-url-manager",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.12.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "support-v4"
            }
          ]
        },
        {
          "group": "com.umeng.umsdk",
          "module": "common",
          "version": {
            "requires": "9.4.2"
          }
        },
        {
          "group": "com.umeng.umsdk",
          "module": "asms",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.umeng.umsdk",
          "module": "apm",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-jar-1.1.0.aar",
          "url": "sdk-jar-1.1.0.aar",
          "size": 391036,
          "sha512": "5b16aa7f7cf6d5294b288c0683a6d7defa726d0243f19e18a17332622a89a35731e5b86e454d8331070a51154730325421eb763ce88e62d51433b80871734985",
          "sha256": "937a50d4c90055042467ebc03af92576718c783726f130ebb8acd5f7d5467086",
          "sha1": "34f1e31ab91cd7942010d62eb2d5620449d20bf6",
          "md5": "4ba7c2525d172663ed8133ba6b8dc71c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.timecat.extend",
          "module": "arms",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "font",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.jaredrummler",
          "module": "android-device-names",
          "version": {
            "requires": "1.1.5"
          }
        },
        {
          "group": "com.blankj",
          "module": "utilcodex",
          "version": {
            "requires": "1.30.1"
          }
        },
        {
          "group": "joda-time",
          "module": "joda-time",
          "version": {
            "requires": "2.10.10"
          }
        },
        {
          "group": "io.reactivex",
          "module": "rxandroid",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "me.jessyan",
          "module": "retrofit-url-manager",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.12.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "support-v4"
            }
          ]
        },
        {
          "group": "com.umeng.umsdk",
          "module": "common",
          "version": {
            "requires": "9.4.2"
          }
        },
        {
          "group": "com.umeng.umsdk",
          "module": "asms",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.umeng.umsdk",
          "module": "apm",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-jar-1.1.0.aar",
          "url": "sdk-jar-1.1.0.aar",
          "size": 391036,
          "sha512": "5b16aa7f7cf6d5294b288c0683a6d7defa726d0243f19e18a17332622a89a35731e5b86e454d8331070a51154730325421eb763ce88e62d51433b80871734985",
          "sha256": "937a50d4c90055042467ebc03af92576718c783726f130ebb8acd5f7d5467086",
          "sha1": "34f1e31ab91cd7942010d62eb2d5620449d20bf6",
          "md5": "4ba7c2525d172663ed8133ba6b8dc71c"
        }
      ]
    }
  ]
}
