{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.identity",
    "module": "data-jar",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "joda-time",
          "module": "joda-time",
          "version": {
            "requires": "2.10.10"
          }
        },
        {
          "group": "com.alibaba",
          "module": "fastjson",
          "version": {
            "requires": "1.2.51"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "data-jar-1.1.0.aar",
          "url": "data-jar-1.1.0.aar",
          "size": 335171,
          "sha512": "3ccc046381a0c8b78a0874cb0da57570db071cc2c054f20f099478e3cf73613a577bc62b0e8dff59180de81080cbd68b32b48507ecd4198adcf93d3c15e0e145",
          "sha256": "a8e0573a9f7369491a18ec834780bed38c723db4bc6b00487e1759d81c6e469a",
          "sha1": "932b44bd661893415469dd401a049705316cabb6",
          "md5": "2b16ca5e886c6b465437c01ff528aff2"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "joda-time",
          "module": "joda-time",
          "version": {
            "requires": "2.10.10"
          }
        },
        {
          "group": "com.alibaba",
          "module": "fastjson",
          "version": {
            "requires": "1.2.51"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "data-jar-1.1.0.aar",
          "url": "data-jar-1.1.0.aar",
          "size": 335171,
          "sha512": "3ccc046381a0c8b78a0874cb0da57570db071cc2c054f20f099478e3cf73613a577bc62b0e8dff59180de81080cbd68b32b48507ecd4198adcf93d3c15e0e145",
          "sha256": "a8e0573a9f7369491a18ec834780bed38c723db4bc6b00487e1759d81c6e469a",
          "sha1": "932b44bd661893415469dd401a049705316cabb6",
          "md5": "2b16ca5e886c6b465437c01ff528aff2"
        }
      ]
    }
  ]
}
