{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.identity",
    "module": "data-jar",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "joda-time",
          "module": "joda-time",
          "version": {
            "requires": "2.10.10"
          }
        },
        {
          "group": "com.alibaba",
          "module": "fastjson",
          "version": {
            "requires": "1.2.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "data-jar-1.1.0.aar",
          "url": "data-jar-1.1.0.aar",
          "size": 329691,
          "sha512": "33c047f64c9a7567607bb1f703918fbf18a7ae98f68d467d13ea686190599df4923af081639d72a7657db458c501869527476ca0a929cf048edc75b4e3e0a182",
          "sha256": "4748b96dcc36f90fe3812b82ac9a5874a9b44811da35cd6addbf62381eabd94d",
          "sha1": "36876d9d16c342b50f5b0498c1be11c69f5dc5d7",
          "md5": "12a065c0393833673c3edb66dd02de46"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "joda-time",
          "module": "joda-time",
          "version": {
            "requires": "2.10.10"
          }
        },
        {
          "group": "com.alibaba",
          "module": "fastjson",
          "version": {
            "requires": "1.2.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "data-jar-1.1.0.aar",
          "url": "data-jar-1.1.0.aar",
          "size": 329691,
          "sha512": "33c047f64c9a7567607bb1f703918fbf18a7ae98f68d467d13ea686190599df4923af081639d72a7657db458c501869527476ca0a929cf048edc75b4e3e0a182",
          "sha256": "4748b96dcc36f90fe3812b82ac9a5874a9b44811da35cd6addbf62381eabd94d",
          "sha1": "36876d9d16c342b50f5b0498c1be11c69f5dc5d7",
          "md5": "12a065c0393833673c3edb66dd02de46"
        }
      ]
    }
  ]
}
