{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.identity",
    "module": "data-jar",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "joda-time",
          "module": "joda-time",
          "version": {
            "requires": "2.10.10"
          }
        },
        {
          "group": "com.alibaba",
          "module": "fastjson",
          "version": {
            "requires": "1.2.51"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "data-jar-1.1.0.aar",
          "url": "data-jar-1.1.0.aar",
          "size": 334430,
          "sha512": "1a06ba9ad5448bfdf47d692119893557e80247dcd265c2bfaef6f4fbd3b5b1fe2453ea23965cf322f56cb8e2a660271a022ecd827437ec168f7670ea6ed1a804",
          "sha256": "8172006c160cc1f81e4c30f152821baacf69829f368a9e3d60caa5459b1034f8",
          "sha1": "cd3b24a4842464f0483051a2b84cb7f04002259d",
          "md5": "8ab21f0afa9e33b1f9b237a2a2e38e63"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "joda-time",
          "module": "joda-time",
          "version": {
            "requires": "2.10.10"
          }
        },
        {
          "group": "com.alibaba",
          "module": "fastjson",
          "version": {
            "requires": "1.2.51"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "data-jar-1.1.0.aar",
          "url": "data-jar-1.1.0.aar",
          "size": 334430,
          "sha512": "1a06ba9ad5448bfdf47d692119893557e80247dcd265c2bfaef6f4fbd3b5b1fe2453ea23965cf322f56cb8e2a660271a022ecd827437ec168f7670ea6ed1a804",
          "sha256": "8172006c160cc1f81e4c30f152821baacf69829f368a9e3d60caa5459b1034f8",
          "sha1": "cd3b24a4842464f0483051a2b84cb7f04002259d",
          "md5": "8ab21f0afa9e33b1f9b237a2a2e38e63"
        }
      ]
    }
  ]
}
