{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.component",
    "module": "guide-view-jar",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "guide-view-1.0.0.aar",
          "url": "guide-view-1.0.0.aar",
          "size": 81190,
          "sha512": "70fbf7c5f7b5f88b2f35cd429105f2924a73cef1eaf336ba240b4e2ef74737ad806ade47c1cda181453fd6b689d099d972638c0e2606c1ee4fdaa132a814bc28",
          "sha256": "a4d75fcf4287c9095035d225177b11f7395a48991ecb608c7915b148a576f603",
          "sha1": "5c480271b6ff3f27ff036164969f120737b1c67a",
          "md5": "b2ae09d07bb07106ccc1ac112c6b6217"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "guide-view-1.0.0.aar",
          "url": "guide-view-1.0.0.aar",
          "size": 81190,
          "sha512": "70fbf7c5f7b5f88b2f35cd429105f2924a73cef1eaf336ba240b4e2ef74737ad806ade47c1cda181453fd6b689d099d972638c0e2606c1ee4fdaa132a814bc28",
          "sha256": "a4d75fcf4287c9095035d225177b11f7395a48991ecb608c7915b148a576f603",
          "sha1": "5c480271b6ff3f27ff036164969f120737b1c67a",
          "md5": "b2ae09d07bb07106ccc1ac112c6b6217"
        }
      ]
    }
  ]
}
