{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.component",
    "module": "guide-view-jar",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "guide-view-1.0.0.aar",
          "url": "guide-view-1.0.0.aar",
          "size": 76850,
          "sha512": "05a89969349897512ddd7a97e3a848d68ea050949ec6f8b6aa0f2532c606b534552f30a51b128bfccb18e568dad112e177fdf898a256e73603062030e1d4e096",
          "sha256": "9ad0ffe6572a36f9e431e434831551e2676650cfeabe0aae876aa4bbf7307aa6",
          "sha1": "59c3df7d64014a583972d3292ce1cdc4c9b0756f",
          "md5": "8f6898264567c2dcefd3664592a6a413"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "guide-view-1.0.0.aar",
          "url": "guide-view-1.0.0.aar",
          "size": 76850,
          "sha512": "05a89969349897512ddd7a97e3a848d68ea050949ec6f8b6aa0f2532c606b534552f30a51b128bfccb18e568dad112e177fdf898a256e73603062030e1d4e096",
          "sha256": "9ad0ffe6572a36f9e431e434831551e2676650cfeabe0aae876aa4bbf7307aa6",
          "sha1": "59c3df7d64014a583972d3292ce1cdc4c9b0756f",
          "md5": "8f6898264567c2dcefd3664592a6a413"
        }
      ]
    }
  ]
}
