{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.component",
    "module": "MView-core-jar",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "MView-core-1.0.1.aar",
          "url": "MView-core-1.0.1.aar",
          "size": 326299,
          "sha512": "a74f2158782a1abf64c1620517ab496dc96c749fe74d3bff60c96d0c733b8925d8aa19943fe2a72d5f14a0417d069024e30317aaf2025dbe162de5058a0261b5",
          "sha256": "0de97b1e6456eb8f171f15ecca0d1db485686f0789ad58739da22d54476efebf",
          "sha1": "6104500f9e96387e8760678ee7db5ce1c15d74e7",
          "md5": "aa87f5e204406065caaab9291f73dcc4"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "MView-core-1.0.1.aar",
          "url": "MView-core-1.0.1.aar",
          "size": 326299,
          "sha512": "a74f2158782a1abf64c1620517ab496dc96c749fe74d3bff60c96d0c733b8925d8aa19943fe2a72d5f14a0417d069024e30317aaf2025dbe162de5058a0261b5",
          "sha256": "0de97b1e6456eb8f171f15ecca0d1db485686f0789ad58739da22d54476efebf",
          "sha1": "6104500f9e96387e8760678ee7db5ce1c15d74e7",
          "md5": "aa87f5e204406065caaab9291f73dcc4"
        }
      ]
    }
  ]
}
