{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.layout",
    "module": "ui-jar",
    "version": "1.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.timecat.component",
          "module": "identity",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.data",
          "module": "system",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "sdk",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.element",
          "module": "listview",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.5.0-alpha01"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "androidx.dynamicanimation",
          "module": "dynamicanimation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.github.markomilos",
          "module": "paginate",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "4.1.0"
          }
        },
        {
          "group": "de.hdodenhof",
          "module": "circleimageview",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.github.CymChad",
          "module": "BaseRecyclerViewAdapterHelper",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "com.github.duanhong169",
          "module": "drawabletoolbox",
          "version": {
            "requires": "1.0.7"
          }
        },
        {
          "group": "com.github.sephiroth74",
          "module": "NumberSlidingPicker",
          "version": {
            "requires": "v1.0.3"
          }
        },
        {
          "group": "com.afollestad",
          "module": "vvalidator",
          "version": {
            "requires": "0.5.2"
          }
        },
        {
          "group": "eu.davidea",
          "module": "flipview",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.iwgang",
          "module": "countdownview",
          "version": {
            "requires": "2.1.6"
          }
        },
        {
          "group": "com.haibin",
          "module": "calendarview",
          "version": {
            "requires": "3.2.7"
          }
        },
        {
          "group": "com.github.githubwing",
          "module": "ByeBurger",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "com.github.florent37",
          "module": "viewtooltip",
          "version": {
            "requires": "1.1.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "ui-jar-1.0.7.aar",
          "url": "ui-jar-1.0.7.aar",
          "size": 1037388,
          "sha512": "a82f1dcc334b8ee58295b2b0fa855fc3094255756762baf59291d1d66bd8dc1fb899700126cb46facd5a6a7446f0df4c9ca97fd09a20a33f4a7a74975708b1e5",
          "sha256": "64dfa641c0bbd2c94cdc170e45dd05cf54ebb916dc20f3974414ccc6402779d2",
          "sha1": "109e5e0a3abc8e155a76a54bc6fdd271a0ddb2d3",
          "md5": "d3080eb915c3f3e7b4d97388e816b024"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "identity",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.data",
          "module": "system",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "sdk",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.element",
          "module": "listview",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.5.0-alpha01"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "androidx.dynamicanimation",
          "module": "dynamicanimation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.github.markomilos",
          "module": "paginate",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "4.1.0"
          }
        },
        {
          "group": "de.hdodenhof",
          "module": "circleimageview",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.github.CymChad",
          "module": "BaseRecyclerViewAdapterHelper",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "com.github.duanhong169",
          "module": "drawabletoolbox",
          "version": {
            "requires": "1.0.7"
          }
        },
        {
          "group": "com.github.sephiroth74",
          "module": "NumberSlidingPicker",
          "version": {
            "requires": "v1.0.3"
          }
        },
        {
          "group": "com.afollestad",
          "module": "vvalidator",
          "version": {
            "requires": "0.5.2"
          }
        },
        {
          "group": "eu.davidea",
          "module": "flipview",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.iwgang",
          "module": "countdownview",
          "version": {
            "requires": "2.1.6"
          }
        },
        {
          "group": "com.haibin",
          "module": "calendarview",
          "version": {
            "requires": "3.2.7"
          }
        },
        {
          "group": "com.github.githubwing",
          "module": "ByeBurger",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "com.github.florent37",
          "module": "viewtooltip",
          "version": {
            "requires": "1.1.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "ui-jar-1.0.7.aar",
          "url": "ui-jar-1.0.7.aar",
          "size": 1037388,
          "sha512": "a82f1dcc334b8ee58295b2b0fa855fc3094255756762baf59291d1d66bd8dc1fb899700126cb46facd5a6a7446f0df4c9ca97fd09a20a33f4a7a74975708b1e5",
          "sha256": "64dfa641c0bbd2c94cdc170e45dd05cf54ebb916dc20f3974414ccc6402779d2",
          "sha1": "109e5e0a3abc8e155a76a54bc6fdd271a0ddb2d3",
          "md5": "d3080eb915c3f3e7b4d97388e816b024"
        }
      ]
    }
  ]
}
