{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.layout",
    "module": "ui-jar",
    "version": "1.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.timecat.component",
          "module": "identity",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.data",
          "module": "system",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "sdk",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.element",
          "module": "listview",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.5.0-alpha01"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "androidx.dynamicanimation",
          "module": "dynamicanimation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.github.markomilos",
          "module": "paginate",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "4.1.0"
          }
        },
        {
          "group": "de.hdodenhof",
          "module": "circleimageview",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.github.CymChad",
          "module": "BaseRecyclerViewAdapterHelper",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "com.github.duanhong169",
          "module": "drawabletoolbox",
          "version": {
            "requires": "1.0.7"
          }
        },
        {
          "group": "com.github.sephiroth74",
          "module": "NumberSlidingPicker",
          "version": {
            "requires": "v1.0.3"
          }
        },
        {
          "group": "com.afollestad",
          "module": "vvalidator",
          "version": {
            "requires": "0.5.2"
          }
        },
        {
          "group": "eu.davidea",
          "module": "flipview",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.iwgang",
          "module": "countdownview",
          "version": {
            "requires": "2.1.6"
          }
        },
        {
          "group": "com.haibin",
          "module": "calendarview",
          "version": {
            "requires": "3.2.7"
          }
        },
        {
          "group": "com.github.chenBingX",
          "module": "SuperTextView",
          "version": {
            "requires": "v3.2.5"
          }
        },
        {
          "group": "com.github.zagum",
          "module": "Android-ExpandIcon",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.github.githubwing",
          "module": "ByeBurger",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "com.github.florent37",
          "module": "viewtooltip",
          "version": {
            "requires": "1.1.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "ui-jar-1.0.7.aar",
          "url": "ui-jar-1.0.7.aar",
          "size": 1039836,
          "sha512": "8aaf77b8c358623d7641193b81ea6a1f5f1b6f8a773acdac9220e1ae649a9628dfd7da218bb51f277bcacc59d1ed5cd9521e9d2f3f2719837bf95dbbc8362ac5",
          "sha256": "312082695d2deb62181d6e0f32199ee139ff9568f7018508cbda09922f10eb3a",
          "sha1": "cecf6f33b9e6f33681813ebad1bc0ee86796d0b9",
          "md5": "193c46f9fb470857eae6de606cb89aaf"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "identity",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.data",
          "module": "system",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "sdk",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.element",
          "module": "listview",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.5.0-alpha01"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "androidx.dynamicanimation",
          "module": "dynamicanimation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.github.markomilos",
          "module": "paginate",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "4.1.0"
          }
        },
        {
          "group": "de.hdodenhof",
          "module": "circleimageview",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.github.CymChad",
          "module": "BaseRecyclerViewAdapterHelper",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "com.github.duanhong169",
          "module": "drawabletoolbox",
          "version": {
            "requires": "1.0.7"
          }
        },
        {
          "group": "com.github.sephiroth74",
          "module": "NumberSlidingPicker",
          "version": {
            "requires": "v1.0.3"
          }
        },
        {
          "group": "com.afollestad",
          "module": "vvalidator",
          "version": {
            "requires": "0.5.2"
          }
        },
        {
          "group": "eu.davidea",
          "module": "flipview",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.iwgang",
          "module": "countdownview",
          "version": {
            "requires": "2.1.6"
          }
        },
        {
          "group": "com.haibin",
          "module": "calendarview",
          "version": {
            "requires": "3.2.7"
          }
        },
        {
          "group": "com.github.chenBingX",
          "module": "SuperTextView",
          "version": {
            "requires": "v3.2.5"
          }
        },
        {
          "group": "com.github.zagum",
          "module": "Android-ExpandIcon",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.github.githubwing",
          "module": "ByeBurger",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "com.github.florent37",
          "module": "viewtooltip",
          "version": {
            "requires": "1.1.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "ui-jar-1.0.7.aar",
          "url": "ui-jar-1.0.7.aar",
          "size": 1039836,
          "sha512": "8aaf77b8c358623d7641193b81ea6a1f5f1b6f8a773acdac9220e1ae649a9628dfd7da218bb51f277bcacc59d1ed5cd9521e9d2f3f2719837bf95dbbc8362ac5",
          "sha256": "312082695d2deb62181d6e0f32199ee139ff9568f7018508cbda09922f10eb3a",
          "sha1": "cecf6f33b9e6f33681813ebad1bc0ee86796d0b9",
          "md5": "193c46f9fb470857eae6de606cb89aaf"
        }
      ]
    }
  ]
}
