{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.layout",
    "module": "ui-jar",
    "version": "1.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "identity",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.data",
          "module": "system",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "sdk",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.element",
          "module": "listview",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "androidx.dynamicanimation",
          "module": "dynamicanimation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.github.markomilos",
          "module": "paginate",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "4.1.0"
          }
        },
        {
          "group": "de.hdodenhof",
          "module": "circleimageview",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.github.CymChad",
          "module": "BaseRecyclerViewAdapterHelper",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "com.github.duanhong169",
          "module": "drawabletoolbox",
          "version": {
            "requires": "1.0.7"
          }
        },
        {
          "group": "com.github.sephiroth74",
          "module": "NumberSlidingPicker",
          "version": {
            "requires": "v1.0.3"
          }
        },
        {
          "group": "com.afollestad",
          "module": "vvalidator",
          "version": {
            "requires": "0.5.2"
          }
        },
        {
          "group": "eu.davidea",
          "module": "flipview",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.iwgang",
          "module": "countdownview",
          "version": {
            "requires": "2.1.6"
          }
        },
        {
          "group": "com.haibin",
          "module": "calendarview",
          "version": {
            "requires": "3.2.7"
          }
        },
        {
          "group": "com.github.githubwing",
          "module": "ByeBurger",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "com.github.florent37",
          "module": "viewtooltip",
          "version": {
            "requires": "1.1.8"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ui-jar-1.0.7.aar",
          "url": "ui-jar-1.0.7.aar",
          "size": 1049599,
          "sha512": "8ed4a2ca876c7427704a201dc2d2e85dc042b05e1ebe34ff7b3a462a59b258da13728bad56592c8c3fce69ccdd8dfc347c9010059326d8dbdd0eb85c85f5fb46",
          "sha256": "3ddf3018ee1b70731c19a1a982e26b8f2fb6f61c0986d188daec8e7a2e6efeb4",
          "sha1": "3ecdb0a2dea66a84ed40d199489bf76383f0c1d8",
          "md5": "7b91209136856c64f629d8f548f68c5d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "identity",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.data",
          "module": "system",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "sdk",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.element",
          "module": "listview",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "androidx.dynamicanimation",
          "module": "dynamicanimation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.github.markomilos",
          "module": "paginate",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "4.1.0"
          }
        },
        {
          "group": "de.hdodenhof",
          "module": "circleimageview",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.github.CymChad",
          "module": "BaseRecyclerViewAdapterHelper",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "com.github.duanhong169",
          "module": "drawabletoolbox",
          "version": {
            "requires": "1.0.7"
          }
        },
        {
          "group": "com.github.sephiroth74",
          "module": "NumberSlidingPicker",
          "version": {
            "requires": "v1.0.3"
          }
        },
        {
          "group": "com.afollestad",
          "module": "vvalidator",
          "version": {
            "requires": "0.5.2"
          }
        },
        {
          "group": "eu.davidea",
          "module": "flipview",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.iwgang",
          "module": "countdownview",
          "version": {
            "requires": "2.1.6"
          }
        },
        {
          "group": "com.haibin",
          "module": "calendarview",
          "version": {
            "requires": "3.2.7"
          }
        },
        {
          "group": "com.github.githubwing",
          "module": "ByeBurger",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "com.github.florent37",
          "module": "viewtooltip",
          "version": {
            "requires": "1.1.8"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ui-jar-1.0.7.aar",
          "url": "ui-jar-1.0.7.aar",
          "size": 1049599,
          "sha512": "8ed4a2ca876c7427704a201dc2d2e85dc042b05e1ebe34ff7b3a462a59b258da13728bad56592c8c3fce69ccdd8dfc347c9010059326d8dbdd0eb85c85f5fb46",
          "sha256": "3ddf3018ee1b70731c19a1a982e26b8f2fb6f61c0986d188daec8e7a2e6efeb4",
          "sha1": "3ecdb0a2dea66a84ed40d199489bf76383f0c1d8",
          "md5": "7b91209136856c64f629d8f548f68c5d"
        }
      ]
    }
  ]
}
