{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.middle",
    "module": "download-jar",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "setting",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "readonly",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "download",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "download-jar-1.0.0.aar",
          "url": "download-jar-1.0.0.aar",
          "size": 58059,
          "sha512": "2179e3f8cdfd7b18e70aba55ce5376ea6bdc714f82ce98573eab31b6c499734f46c80377b8890b3f70d24a890bbe61838806d559d2921c67965e8b4d18f0f493",
          "sha256": "b9f6a657c5457fb0d7c31c39c0a6e5800bc56de1a84782151097fb00e1783a18",
          "sha1": "e57fe156c89fd9bd63b96b25bc358e3b37fea870",
          "md5": "b9e859a97a90d1be4ad7fd280d3e5b95"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "setting",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "readonly",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "download",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "download-jar-1.0.0.aar",
          "url": "download-jar-1.0.0.aar",
          "size": 58059,
          "sha512": "2179e3f8cdfd7b18e70aba55ce5376ea6bdc714f82ce98573eab31b6c499734f46c80377b8890b3f70d24a890bbe61838806d559d2921c67965e8b4d18f0f493",
          "sha256": "b9f6a657c5457fb0d7c31c39c0a6e5800bc56de1a84782151097fb00e1783a18",
          "sha1": "e57fe156c89fd9bd63b96b25bc358e3b37fea870",
          "md5": "b9e859a97a90d1be4ad7fd280d3e5b95"
        }
      ]
    }
  ]
}
