{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.middle",
    "module": "download-jar",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.timecat.component",
          "module": "setting",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "readonly",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "download",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "download-jar-1.0.0.aar",
          "url": "download-jar-1.0.0.aar",
          "size": 47455,
          "sha512": "adf8a68e7b1d9b1d4e856ae3585270404b45458e2822b7b51ad3b7bfa6d64d4fac1d865e2627ece0dbbc0d63781007a7de0049b243c93fbc71e0cf3ec5def140",
          "sha256": "4e1313601a283e55ddeb9b555e212aca5ff0f6e90bbc9a134ff0fe1c2e67d65a",
          "sha1": "719106ebc4986f025d2015d365e9cd55d91894d3",
          "md5": "2ee8e9882d7a9dcaf0314979c0844912"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.timecat.component",
          "module": "setting",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "readonly",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "download",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "download-jar-1.0.0.aar",
          "url": "download-jar-1.0.0.aar",
          "size": 47455,
          "sha512": "adf8a68e7b1d9b1d4e856ae3585270404b45458e2822b7b51ad3b7bfa6d64d4fac1d865e2627ece0dbbc0d63781007a7de0049b243c93fbc71e0cf3ec5def140",
          "sha256": "4e1313601a283e55ddeb9b555e212aca5ff0f6e90bbc9a134ff0fe1c2e67d65a",
          "sha1": "719106ebc4986f025d2015d365e9cd55d91894d3",
          "md5": "2ee8e9882d7a9dcaf0314979c0844912"
        }
      ]
    }
  ]
}
