{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.module",
    "module": "module-theme-jar",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "com.timecat.page",
          "module": "base",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.layout",
          "module": "ui",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "router",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "readonly",
          "version": {
            "requires": "+"
          }
        }
      ],
      "files": [
        {
          "name": "module-theme-jar-1.0.0.aar",
          "url": "module-theme-jar-1.0.0.aar",
          "size": 616792,
          "sha512": "4c106623a35a45f155ce728133d1afc1904b0bc89be5f8100c58e301dc6c11496d75fbdd09e6be583cd3813392f9be53779a90fdd50e1a23c40aac712aea0c48",
          "sha256": "fa4265a29f25f38e09ed836141971954527f19fae2f7ee56c6ade5a7d8ef454b",
          "sha1": "ffb18e9258d410f32f38ab367c0598c3a8e5dd93",
          "md5": "8e6f50ddd9a5718c85f6b63511c0ca4c"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "com.timecat.page",
          "module": "base",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.layout",
          "module": "ui",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "router",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "readonly",
          "version": {
            "requires": "+"
          }
        }
      ],
      "files": [
        {
          "name": "module-theme-jar-1.0.0.aar",
          "url": "module-theme-jar-1.0.0.aar",
          "size": 616792,
          "sha512": "4c106623a35a45f155ce728133d1afc1904b0bc89be5f8100c58e301dc6c11496d75fbdd09e6be583cd3813392f9be53779a90fdd50e1a23c40aac712aea0c48",
          "sha256": "fa4265a29f25f38e09ed836141971954527f19fae2f7ee56c6ade5a7d8ef454b",
          "sha1": "ffb18e9258d410f32f38ab367c0598c3a8e5dd93",
          "md5": "8e6f50ddd9a5718c85f6b63511c0ca4c"
        }
      ]
    }
  ]
}
