{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.extend",
    "module": "baidu-jar",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": null,
          "module": "ocrsdk",
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "ocrsdk",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "baidu-1.0.0.aar",
          "url": "baidu-1.0.0.aar",
          "size": 34639,
          "sha512": "36c27ca9bbdff5bbbccd45a77875c1d5ec7761ef8523dd145f315552f07b4e382f9180cc4c92bdf89d3d57b1dd06ad7af437fdbe6e4623aed36e0f3b94c6c25b",
          "sha256": "bbfe0d74edbff249ddcf8024e0181581bf87ec89522cf59b8361ea3877170351",
          "sha1": "482bb813bb93d9a46708be850d667257bce8856c",
          "md5": "c33ff3796e8da75d0fa1be18bcc129e9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": null,
          "module": "ocrsdk",
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "ocrsdk",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "baidu-1.0.0.aar",
          "url": "baidu-1.0.0.aar",
          "size": 34639,
          "sha512": "36c27ca9bbdff5bbbccd45a77875c1d5ec7761ef8523dd145f315552f07b4e382f9180cc4c92bdf89d3d57b1dd06ad7af437fdbe6e4623aed36e0f3b94c6c25b",
          "sha256": "bbfe0d74edbff249ddcf8024e0181581bf87ec89522cf59b8361ea3877170351",
          "sha1": "482bb813bb93d9a46708be850d667257bce8856c",
          "md5": "c33ff3796e8da75d0fa1be18bcc129e9"
        }
      ]
    }
  ]
}
