{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.extend",
    "module": "baidu-jar",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "baidu-1.0.0.aar",
          "url": "baidu-1.0.0.aar",
          "size": 34635,
          "sha512": "a567755bfc4ab4286439d93e1464dabbb8bd1ecb65e7a87391e5529da8879a2fa923b108af2cdc9e3ccda6dbb0a3bc4c572d26920bcb1cfcd3c32a531b18892a",
          "sha256": "15d77e0aa643afddc94cd7f774e9e39b2f14eb09e85a209704a2cff3803e86a1",
          "sha1": "a24d82dce12eba74a2f7d2bfff9e4b8015a39f10",
          "md5": "ab3bd6cbea40f9b789755b6f1738a4c5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "baidu-1.0.0.aar",
          "url": "baidu-1.0.0.aar",
          "size": 34635,
          "sha512": "a567755bfc4ab4286439d93e1464dabbb8bd1ecb65e7a87391e5529da8879a2fa923b108af2cdc9e3ccda6dbb0a3bc4c572d26920bcb1cfcd3c32a531b18892a",
          "sha256": "15d77e0aa643afddc94cd7f774e9e39b2f14eb09e85a209704a2cff3803e86a1",
          "sha1": "a24d82dce12eba74a2f7d2bfff9e4b8015a39f10",
          "md5": "ab3bd6cbea40f9b789755b6f1738a4c5"
        }
      ]
    }
  ]
}
