{
  "formatVersion": "1.1",
  "component": {
    "group": "com.facebook",
    "module": "jni-jar",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "jni-1.0.0.aar",
          "url": "jni-1.0.0.aar",
          "size": 1136722,
          "sha512": "a4a79d04629ef8fd392855614208f5a35125d5b9adb1d087256a2dd8f30af8652e665ccdbd0ebe79b6b7032adc66bf75b8c0ef12efb563599db7d3c91bc8e2ae",
          "sha256": "922af754432d41d01b4c7a069bcc26e92d54307cd7eb543f160e2e9d1c091920",
          "sha1": "cbb42f5005829f13d5e7485bff19f33126d97c36",
          "md5": "8cfe7ed7b7e7d50099d3b849ea50bdbf"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "jni-1.0.0.aar",
          "url": "jni-1.0.0.aar",
          "size": 1136722,
          "sha512": "a4a79d04629ef8fd392855614208f5a35125d5b9adb1d087256a2dd8f30af8652e665ccdbd0ebe79b6b7032adc66bf75b8c0ef12efb563599db7d3c91bc8e2ae",
          "sha256": "922af754432d41d01b4c7a069bcc26e92d54307cd7eb543f160e2e9d1c091920",
          "sha1": "cbb42f5005829f13d5e7485bff19f33126d97c36",
          "md5": "8cfe7ed7b7e7d50099d3b849ea50bdbf"
        }
      ]
    }
  ]
}
