{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.module",
    "module": "module-welcome-jar",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "com.timecat.page",
          "module": "base",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.layout",
          "module": "ui",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.data",
          "module": "system",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "router",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "service",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "anim",
          "version": {
            "requires": "+"
          }
        }
      ],
      "files": [
        {
          "name": "module-welcome-jar-1.1.0.aar",
          "url": "module-welcome-jar-1.1.0.aar",
          "size": 180175,
          "sha512": "372d8428de24aebe49c525dd1cd7f633b2d0d0b8d3b2c4b275966dbefe24f29aaccf73f110962b4a1a147bf7e44c65eb263550a92bed4090bdd2cd96f394e385",
          "sha256": "0f9506a2987813725cd66590f7214ff3844126a62afd4aa0e89fd1a28c9389a8",
          "sha1": "ab4cb9d4e4ad660d882c9a791c2ad903bd46d8c8",
          "md5": "be1a7ac861b95824e8eb19f35435e738"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "com.timecat.page",
          "module": "base",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.layout",
          "module": "ui",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.data",
          "module": "system",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "router",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "service",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "anim",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.jaredrummler",
          "module": "animated-svg-view",
          "version": {
            "requires": "1.0.5"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "MView-core",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "MView-intro",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "MView-font",
          "version": {
            "requires": "+"
          }
        }
      ],
      "files": [
        {
          "name": "module-welcome-jar-1.1.0.aar",
          "url": "module-welcome-jar-1.1.0.aar",
          "size": 180175,
          "sha512": "372d8428de24aebe49c525dd1cd7f633b2d0d0b8d3b2c4b275966dbefe24f29aaccf73f110962b4a1a147bf7e44c65eb263550a92bed4090bdd2cd96f394e385",
          "sha256": "0f9506a2987813725cd66590f7214ff3844126a62afd4aa0e89fd1a28c9389a8",
          "sha1": "ab4cb9d4e4ad660d882c9a791c2ad903bd46d8c8",
          "md5": "be1a7ac861b95824e8eb19f35435e738"
        }
      ]
    }
  ]
}
