{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.component",
    "module": "download-jar",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "download-jar-1.0.0.aar",
          "url": "download-jar-1.0.0.aar",
          "size": 98247,
          "sha512": "a6d4287ed93e0ce531ae4a09b314127b88248bfe2eaca8e42a179875a07c87f0235535f1e8bd810d50e8e4ad5397c807d3cba89341fc9028f13a362fb5b47d40",
          "sha256": "8aac1eb42c081e782aa33723d0e6a69e7d20d78bcd735afab23f4e94579da2eb",
          "sha1": "c88b8d2459ecab37979c4c378ecaf34dcbe0bbbe",
          "md5": "4ddb20640cac8dec84c99c5f5c402f9c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "download-jar-1.0.0.aar",
          "url": "download-jar-1.0.0.aar",
          "size": 98247,
          "sha512": "a6d4287ed93e0ce531ae4a09b314127b88248bfe2eaca8e42a179875a07c87f0235535f1e8bd810d50e8e4ad5397c807d3cba89341fc9028f13a362fb5b47d40",
          "sha256": "8aac1eb42c081e782aa33723d0e6a69e7d20d78bcd735afab23f4e94579da2eb",
          "sha1": "c88b8d2459ecab37979c4c378ecaf34dcbe0bbbe",
          "md5": "4ddb20640cac8dec84c99c5f5c402f9c"
        }
      ]
    }
  ]
}
