{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.identity",
    "module": "anim-jar",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "anim-1.0.1.aar",
          "url": "anim-1.0.1.aar",
          "size": 27270,
          "sha512": "9552ab9ca8e9d517da9177268ae0ea9c555b78321a01d2e9d73f56aaf9f30c25abe9d64bf487743aa62dedd87d692edbd08f0f73f34506ae0130db308ebe4a21",
          "sha256": "1fdd43efe0269796c022e673b5c8cb0b9e5a67b347c8a8342aed6b992e416bfa",
          "sha1": "dbd61576f2475ba5d28c2a04742694f6d4501363",
          "md5": "520bf098a44d0ab3341aabba3e6c0320"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "anim-1.0.1.aar",
          "url": "anim-1.0.1.aar",
          "size": 27270,
          "sha512": "9552ab9ca8e9d517da9177268ae0ea9c555b78321a01d2e9d73f56aaf9f30c25abe9d64bf487743aa62dedd87d692edbd08f0f73f34506ae0130db308ebe4a21",
          "sha256": "1fdd43efe0269796c022e673b5c8cb0b9e5a67b347c8a8342aed6b992e416bfa",
          "sha1": "dbd61576f2475ba5d28c2a04742694f6d4501363",
          "md5": "520bf098a44d0ab3341aabba3e6c0320"
        }
      ]
    }
  ]
}
