{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.module",
    "module": "module-browser-jar",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.timecat.middle",
          "module": "block",
          "version": {
            "requires": "+"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.timecat.middle",
          "module": "form",
          "version": {
            "requires": "+"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.timecat.data",
          "module": "bmob",
          "version": {
            "requires": "+"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.timecat.identity",
          "module": "readonly",
          "version": {
            "requires": "+"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.timecat.layout",
          "module": "ui",
          "version": {
            "requires": "+"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.timecat.identity",
          "module": "service",
          "version": {
            "requires": "+"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.timecat.component",
          "module": "router",
          "version": {
            "requires": "+"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.timecat.component",
          "module": "identity",
          "version": {
            "requires": "+"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.2.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.7.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.3.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.palette",
          "module": "palette",
          "version": {
            "requires": "1.0.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.2.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.13.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.anthonycr.mezzanine",
          "module": "mezzanine",
          "version": {
            "requires": "1.1.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.22.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "net.i2p.android",
          "module": "helper",
          "version": {
            "requires": "0.9.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            },
            {
              "group": "org.apache.httpcomponents",
              "module": "*"
            }
          ]
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxkotlin",
          "version": {
            "requires": "2.3.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "info.guardianproject.netcipher",
          "module": "netcipher",
          "version": {
            "requires": "2.0.0-alpha1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "info.guardianproject.netcipher",
          "module": "netcipher-webkit",
          "version": {
            "requires": "2.0.0-alpha1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.anthonycr.progress",
          "module": "animated-progress",
          "version": {
            "requires": "1.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "module-browser-1.1.0.aar",
          "url": "module-browser-1.1.0.aar",
          "size": 1670108,
          "sha512": "038aa138bf9c2db8e728982933bffabf1a50fb66006b39cfc17890900d6a8caa3207350770fa1337246418164799045da1c83b7658168d1feb7d72f5b669e5ca",
          "sha256": "b56ff8bcd7cc86d10713ff9954668d97d0d2bfaaa91c2a4c7da8856798ab4c15",
          "sha1": "3b9d72215eccfe940c25e7dc6e3af287001e1628",
          "md5": "5c9fa59b20ac9e2f7612750c97f07710"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.leakcanary",
          "module": "leakcanary-android-no-op",
          "version": {
            "requires": "1.6.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.timecat.middle",
          "module": "block",
          "version": {
            "requires": "+"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.timecat.middle",
          "module": "form",
          "version": {
            "requires": "+"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.timecat.data",
          "module": "bmob",
          "version": {
            "requires": "+"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.timecat.identity",
          "module": "readonly",
          "version": {
            "requires": "+"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.timecat.layout",
          "module": "ui",
          "version": {
            "requires": "+"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.timecat.identity",
          "module": "service",
          "version": {
            "requires": "+"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.timecat.component",
          "module": "router",
          "version": {
            "requires": "+"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.timecat.component",
          "module": "identity",
          "version": {
            "requires": "+"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.2.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.7.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.3.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.palette",
          "module": "palette",
          "version": {
            "requires": "1.0.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.2.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.13.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.anthonycr.mezzanine",
          "module": "mezzanine",
          "version": {
            "requires": "1.1.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.22.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "net.i2p.android",
          "module": "helper",
          "version": {
            "requires": "0.9.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            },
            {
              "group": "org.apache.httpcomponents",
              "module": "*"
            }
          ]
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxkotlin",
          "version": {
            "requires": "2.3.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "info.guardianproject.netcipher",
          "module": "netcipher",
          "version": {
            "requires": "2.0.0-alpha1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "info.guardianproject.netcipher",
          "module": "netcipher-webkit",
          "version": {
            "requires": "2.0.0-alpha1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "com.anthonycr.progress",
          "module": "animated-progress",
          "version": {
            "requires": "1.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "httpclient"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "module-browser-1.1.0.aar",
          "url": "module-browser-1.1.0.aar",
          "size": 1670108,
          "sha512": "038aa138bf9c2db8e728982933bffabf1a50fb66006b39cfc17890900d6a8caa3207350770fa1337246418164799045da1c83b7658168d1feb7d72f5b669e5ca",
          "sha256": "b56ff8bcd7cc86d10713ff9954668d97d0d2bfaaa91c2a4c7da8856798ab4c15",
          "sha1": "3b9d72215eccfe940c25e7dc6e3af287001e1628",
          "md5": "5c9fa59b20ac9e2f7612750c97f07710"
        }
      ]
    }
  ]
}
