{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.component",
    "module": "download-jar",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "download-1.0.0.aar",
          "url": "download-1.0.0.aar",
          "size": 98251,
          "sha512": "d955271c56a43b16654a11e3fef99fa1c3a42ab5090fa89c4d382daf4d0727abb317d1930bac37076eb0bbc3435d1f281b87689c2da1294d631e4952bfc9bc91",
          "sha256": "2f41a9b9a7b39675ffbf87403db102bddf08406d20910a8969bafe296c89a234",
          "sha1": "32aa600b52923b92a7f68b655e9f10596c4c4623",
          "md5": "fb21bdb383f438c2810a193e375f89d5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "download-1.0.0.aar",
          "url": "download-1.0.0.aar",
          "size": 98251,
          "sha512": "d955271c56a43b16654a11e3fef99fa1c3a42ab5090fa89c4d382daf4d0727abb317d1930bac37076eb0bbc3435d1f281b87689c2da1294d631e4952bfc9bc91",
          "sha256": "2f41a9b9a7b39675ffbf87403db102bddf08406d20910a8969bafe296c89a234",
          "sha1": "32aa600b52923b92a7f68b655e9f10596c4c4623",
          "md5": "fb21bdb383f438c2810a193e375f89d5"
        }
      ]
    }
  ]
}
