{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.module",
    "module": "module-developer-jar",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.timecat.data",
          "module": "system",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.data",
          "module": "bmob",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "block",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "module-developer-1.1.0.aar",
          "url": "module-developer-1.1.0.aar",
          "size": 165984,
          "sha512": "80a64490f34f8fcc332651ec518dd990a59e3270f3511b147331589fb0f966344805626ae1ba15b00b17cb32abecb0e5716f934102729d7c01d3a19bdcae09a0",
          "sha256": "89e552e7ea99c849d2303802cbf7a6e99292895d639688513a51a7bcbceb4bcd",
          "sha1": "ab07406160359995ce145d321b861f8b7d6ae58d",
          "md5": "dade2d3d8085a78509605f36e500679e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.didi.dokit",
          "module": "dokitx-no-op",
          "version": {
            "requires": "3.4.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.timecat.data",
          "module": "system",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.data",
          "module": "bmob",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "block",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "com.github.CymChad",
          "module": "BaseRecyclerViewAdapterHelper",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.github.iwgang",
          "module": "countdownview",
          "version": {
            "requires": "2.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "module-developer-1.1.0.aar",
          "url": "module-developer-1.1.0.aar",
          "size": 165984,
          "sha512": "80a64490f34f8fcc332651ec518dd990a59e3270f3511b147331589fb0f966344805626ae1ba15b00b17cb32abecb0e5716f934102729d7c01d3a19bdcae09a0",
          "sha256": "89e552e7ea99c849d2303802cbf7a6e99292895d639688513a51a7bcbceb4bcd",
          "sha1": "ab07406160359995ce145d321b861f8b7d6ae58d",
          "md5": "dade2d3d8085a78509605f36e500679e"
        }
      ]
    }
  ]
}
