{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.identity",
    "module": "resources-jar",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "resources-jar-1.0.0.aar",
          "url": "resources-jar-1.0.0.aar",
          "size": 2148360,
          "sha512": "ca8a2a7c0f1ac225c5b251148188496b6954f9ed718c319ee3b108397189233977a9cf13c9bfc8fcc4255c853bb40e21223e170be7fb60d3eec6516e2a2d0398",
          "sha256": "7521030c1fbec5e22d375aa5f0672f229020c6d426d76dd2f88faea6921ab961",
          "sha1": "08d8e1d04d7422e2b484a188d091cf600e310bd5",
          "md5": "43ee7ada455602dd3fec623d81137829"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "resources-jar-1.0.0.aar",
          "url": "resources-jar-1.0.0.aar",
          "size": 2148360,
          "sha512": "ca8a2a7c0f1ac225c5b251148188496b6954f9ed718c319ee3b108397189233977a9cf13c9bfc8fcc4255c853bb40e21223e170be7fb60d3eec6516e2a2d0398",
          "sha256": "7521030c1fbec5e22d375aa5f0672f229020c6d426d76dd2f88faea6921ab961",
          "sha1": "08d8e1d04d7422e2b484a188d091cf600e310bd5",
          "md5": "43ee7ada455602dd3fec623d81137829"
        }
      ]
    }
  ]
}
