{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.identity",
    "module": "resources-jar",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "resources-jar-1.0.0.aar",
          "url": "resources-jar-1.0.0.aar",
          "size": 2174192,
          "sha512": "f5f68489490680e06943ed265262ffafc3e30f01d878427a38d5756e81294b40746e63cbbd0fd299cea0c43f365c2c37a9ca0d08417537b87d0f3f09ad818f83",
          "sha256": "c2aaf80387edc4cc03140dc91e381aab8875880be8169df6e170e6c9296b06fd",
          "sha1": "830d5842d241e7a5d1ff0efc9d5113f4d9b2fd28",
          "md5": "f5a36d19407e4189fa1f0c5b74faf759"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "resources-jar-1.0.0.aar",
          "url": "resources-jar-1.0.0.aar",
          "size": 2174192,
          "sha512": "f5f68489490680e06943ed265262ffafc3e30f01d878427a38d5756e81294b40746e63cbbd0fd299cea0c43f365c2c37a9ca0d08417537b87d0f3f09ad818f83",
          "sha256": "c2aaf80387edc4cc03140dc91e381aab8875880be8169df6e170e6c9296b06fd",
          "sha1": "830d5842d241e7a5d1ff0efc9d5113f4d9b2fd28",
          "md5": "f5a36d19407e4189fa1f0c5b74faf759"
        }
      ]
    }
  ]
}
