{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.middle",
    "module": "block-jar",
    "version": "1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.timecat.identity",
          "module": "data",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "router",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "service",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "SelfXunfei",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.data",
          "module": "greendao",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.data",
          "module": "room",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.layout",
          "module": "ui",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.page",
          "module": "base",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "MView-same",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "com.google.android",
          "module": "flexbox",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.vmloft.library",
          "module": "vmtools",
          "version": {
            "requires": "0.10.5"
          }
        },
        {
          "group": "com.github.chrisbanes",
          "module": "PhotoView",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.gauravk.audiovisualizer",
          "module": "audiovisualizer",
          "version": {
            "requires": "0.9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.larswerkman",
          "module": "HoloColorPicker",
          "version": {
            "requires": "1.5"
          }
        },
        {
          "group": "de.hdodenhof",
          "module": "circleimageview",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.github.CymChad",
          "module": "BaseRecyclerViewAdapterHelper",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "io.github.razerdp",
          "module": "BasePopup",
          "version": {
            "requires": "3.1.4"
          }
        },
        {
          "group": "com.github.florent37",
          "module": "viewtooltip",
          "version": {
            "requires": "1.1.8"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "block-jar-1.1.2.aar",
          "url": "block-jar-1.1.2.aar",
          "size": 1361951,
          "sha512": "6780b84bef25133145f7e4c4dd51af00bf799ac973ae1386ce76f9ad9fbd8c0eabf2fde61f5ac3588d2dc3b2317a60891743eb7ebb3956f851df324cdd41f44a",
          "sha256": "423473edaa7762a0b1571fd892e1053e9c6f829633a4b8bf4a6b0c6f9240a8d5",
          "sha1": "0bb199e50eb46fd4f29f2bb233ad8f46f113d5ca",
          "md5": "c789687ff6186aba69e9a71f65dd31f2"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.timecat.identity",
          "module": "data",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "router",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.identity",
          "module": "service",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.component",
          "module": "SelfXunfei",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.data",
          "module": "greendao",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.data",
          "module": "room",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.layout",
          "module": "ui",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.page",
          "module": "base",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.timecat.middle",
          "module": "MView-same",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "com.google.android",
          "module": "flexbox",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.vmloft.library",
          "module": "vmtools",
          "version": {
            "requires": "0.10.5"
          }
        },
        {
          "group": "com.github.chrisbanes",
          "module": "PhotoView",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.gauravk.audiovisualizer",
          "module": "audiovisualizer",
          "version": {
            "requires": "0.9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.larswerkman",
          "module": "HoloColorPicker",
          "version": {
            "requires": "1.5"
          }
        },
        {
          "group": "de.hdodenhof",
          "module": "circleimageview",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.github.CymChad",
          "module": "BaseRecyclerViewAdapterHelper",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "io.github.razerdp",
          "module": "BasePopup",
          "version": {
            "requires": "3.1.4"
          }
        },
        {
          "group": "com.github.florent37",
          "module": "viewtooltip",
          "version": {
            "requires": "1.1.8"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "block-jar-1.1.2.aar",
          "url": "block-jar-1.1.2.aar",
          "size": 1361951,
          "sha512": "6780b84bef25133145f7e4c4dd51af00bf799ac973ae1386ce76f9ad9fbd8c0eabf2fde61f5ac3588d2dc3b2317a60891743eb7ebb3956f851df324cdd41f44a",
          "sha256": "423473edaa7762a0b1571fd892e1053e9c6f829633a4b8bf4a6b0c6f9240a8d5",
          "sha1": "0bb199e50eb46fd4f29f2bb233ad8f46f113d5ca",
          "md5": "c789687ff6186aba69e9a71f65dd31f2"
        }
      ]
    }
  ]
}
