{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.plugin",
    "module": "record-api-holder-jar",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.timecat.plugin",
          "module": "record-api",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.tencent.shadow.core",
          "module": "utils",
          "version": {
            "requires": "2.0.5"
          }
        },
        {
          "group": "com.tencent.shadow.core",
          "module": "common",
          "version": {
            "requires": "2.0.5"
          }
        },
        {
          "group": "com.tencent.shadow.dynamic",
          "module": "apk",
          "version": {
            "requires": "2.0.5"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "record-api-holder-jar-1.0.0.aar",
          "url": "record-api-holder-jar-1.0.0.aar",
          "size": 121461,
          "sha512": "c0d82831bf96c5361cf0a99b7ac9982ba6c6e781f90796f41b1f156470851507e40c22adb09e595757f939a69aa8782d933b6301473589543aaf6fddb7b85d9f",
          "sha256": "fd6309c461f8de215952c37cb316dc3d286c8ad1bf87603d6acd1be17a41c892",
          "sha1": "fbaa632d042481b745af763391380aa9fa4bdc0e",
          "md5": "090bf762be09587b4681d90e6f96e670"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.timecat.plugin",
          "module": "record-api",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.tencent.shadow.core",
          "module": "utils",
          "version": {
            "requires": "2.0.5"
          }
        },
        {
          "group": "com.tencent.shadow.core",
          "module": "common",
          "version": {
            "requires": "2.0.5"
          }
        },
        {
          "group": "com.tencent.shadow.dynamic",
          "module": "apk",
          "version": {
            "requires": "2.0.5"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "record-api-holder-jar-1.0.0.aar",
          "url": "record-api-holder-jar-1.0.0.aar",
          "size": 121461,
          "sha512": "c0d82831bf96c5361cf0a99b7ac9982ba6c6e781f90796f41b1f156470851507e40c22adb09e595757f939a69aa8782d933b6301473589543aaf6fddb7b85d9f",
          "sha256": "fd6309c461f8de215952c37cb316dc3d286c8ad1bf87603d6acd1be17a41c892",
          "sha1": "fbaa632d042481b745af763391380aa9fa4bdc0e",
          "md5": "090bf762be09587b4681d90e6f96e670"
        }
      ]
    }
  ]
}
