{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.plugin",
    "module": "record-api-holder-jar",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.timecat.plugin",
          "module": "record-api",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.tencent.shadow.core",
          "module": "utils",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.tencent.shadow.core",
          "module": "common",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.tencent.shadow.dynamic",
          "module": "apk",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "record-api-holder-jar-1.0.0.aar",
          "url": "record-api-holder-jar-1.0.0.aar",
          "size": 102454,
          "sha512": "96e5d60fb65c3bcbdeb217a8f4daa1a73a7f1e0d1347e6c0cf95a6cf9beb06f7e0a4473c386fcd3b67cbea0dcaa54da89bfabf84a471351615d9bf9107f87d6a",
          "sha256": "a6c3b27b75df02830b9b199a44fe369676f33b9adf5aa4b715c17652ae03112d",
          "sha1": "e28664502f7c2306687ab2c0adeed00e6a60a315",
          "md5": "fa8c2b857d9e2a5aac2de543c7e64207"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.timecat.plugin",
          "module": "record-api",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.tencent.shadow.core",
          "module": "utils",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.tencent.shadow.core",
          "module": "common",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.tencent.shadow.dynamic",
          "module": "apk",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "record-api-holder-jar-1.0.0.aar",
          "url": "record-api-holder-jar-1.0.0.aar",
          "size": 102454,
          "sha512": "96e5d60fb65c3bcbdeb217a8f4daa1a73a7f1e0d1347e6c0cf95a6cf9beb06f7e0a4473c386fcd3b67cbea0dcaa54da89bfabf84a471351615d9bf9107f87d6a",
          "sha256": "a6c3b27b75df02830b9b199a44fe369676f33b9adf5aa4b715c17652ae03112d",
          "sha1": "e28664502f7c2306687ab2c0adeed00e6a60a315",
          "md5": "fa8c2b857d9e2a5aac2de543c7e64207"
        }
      ]
    }
  ]
}
