{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.component",
    "module": "guide-api-jar",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "guide-api-jar-1.0.0.aar",
          "url": "guide-api-jar-1.0.0.aar",
          "size": 17442,
          "sha512": "cbc8bcaa953e11eb98b4f267296c966aab1b7628356e43f9a3c05a1a6bfcaec4030358118e41e7f3559a5f78c9b554e9e4ab8fd776efb9ef2bd332df39ee6871",
          "sha256": "67cbcc1c077257126d30661ec618981573d62f9333e9484c27316ec69ae9addb",
          "sha1": "fdeaa8a8fbac736c71b9e047b7f610ea42b81355",
          "md5": "79e74375db47e5963089f564dd2b287d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "guide-api-jar-1.0.0.aar",
          "url": "guide-api-jar-1.0.0.aar",
          "size": 17442,
          "sha512": "cbc8bcaa953e11eb98b4f267296c966aab1b7628356e43f9a3c05a1a6bfcaec4030358118e41e7f3559a5f78c9b554e9e4ab8fd776efb9ef2bd332df39ee6871",
          "sha256": "67cbcc1c077257126d30661ec618981573d62f9333e9484c27316ec69ae9addb",
          "sha1": "fdeaa8a8fbac736c71b9e047b7f610ea42b81355",
          "md5": "79e74375db47e5963089f564dd2b287d"
        }
      ]
    }
  ]
}
