{
  "formatVersion": "1.1",
  "component": {
    "group": "com.timecat.page",
    "module": "scene-jar",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-extensions",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "scene-jar-1.0.1.aar",
          "url": "scene-jar-1.0.1.aar",
          "size": 138405,
          "sha512": "ac7ce73b0e96cf5024e9d8cea5592725bc7c2be4b7c708ba2de804a013cac1dc2364d167b4997cc4056afc3dfee4fbde5ff5f208e02f437218e6929d054240b5",
          "sha256": "f302f55ea0ab197ae9c4fc8081b15b5928f9cf8ac3e4bfd63cfa6af00e0d42fd",
          "sha1": "58a61729519ceb2f541e6c402c0e5abd2ec3b491",
          "md5": "1516b49cdf92e928d7b90393e111e4c8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-extensions",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "scene-jar-1.0.1.aar",
          "url": "scene-jar-1.0.1.aar",
          "size": 138405,
          "sha512": "ac7ce73b0e96cf5024e9d8cea5592725bc7c2be4b7c708ba2de804a013cac1dc2364d167b4997cc4056afc3dfee4fbde5ff5f208e02f437218e6929d054240b5",
          "sha256": "f302f55ea0ab197ae9c4fc8081b15b5928f9cf8ac3e4bfd63cfa6af00e0d42fd",
          "sha1": "58a61729519ceb2f541e6c402c0e5abd2ec3b491",
          "md5": "1516b49cdf92e928d7b90393e111e4c8"
        }
      ]
    }
  ]
}
